{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"allowedFunctions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"maxAllowedPinAttempts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"pinPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinPolicy","preciseIdentifier":"c:objc(cs)ONGPinPolicy","text":"ONGPinPolicy"},{"kind":"text","text":"!)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientconfig\/init(allowedfunctions:maxallowedpinattempts:pinpolicy:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientconfig\/init(allowedfunctions:maxallowedpinattempts:pinpolicy:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientConfig\/init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"allowedFunctions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"maxAllowedPinAttempts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"pinPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGPinPolicy","preciseIdentifier":"c:objc(cs)ONGPinPolicy"},{"kind":"text","text":"!)"}],"title":"init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)ONGClientConfig(im)initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientConfig"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinPolicy":{"role":"symbol","title":"ONGPinPolicy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinPolicy"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinPolicy"}],"url":"\/documentation\/oneginisdkios\/ongpinpolicy"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientConfig/init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)":{"role":"symbol","title":"init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"!("},{"kind":"externalParam","text":"allowedFunctions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!, "},{"kind":"externalParam","text":"maxAllowedPinAttempts"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"pinPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGPinPolicy","preciseIdentifier":"c:objc(cs)ONGPinPolicy"},{"kind":"text","text":"!)"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientConfig\/init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"}],"url":"\/documentation\/oneginisdkios\/ongclientconfig\/init(allowedfunctions:maxallowedpinattempts:pinpolicy:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientConfig":{"role":"symbol","title":"ONGClientConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientConfig"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientConfig"}],"url":"\/documentation\/oneginisdkios\/ongclientconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAllowedFunctions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"allowedFunctions"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxAllowedPinAttempts:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"maxAllowedPinAttempts"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinPolicy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinPolicy","preciseIdentifier":"c:objc(cs)ONGPinPolicy","text":"ONGPinPolicy"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pinPolicy"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinPolicy\/title","value":"ONGPinPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinPolicy\/fragments","value":[{"kind":"identifier","text":"ONGPinPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientConfig~1init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)\/title","value":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientConfig~1init(allowedFunctions:maxAllowedPinAttempts:pinPolicy:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAllowedFunctions:maxAllowedPinAttempts:pinPolicy:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientConfig\/title","value":"ONGClientConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientConfig\/fragments","value":[{"kind":"identifier","text":"ONGClientConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}