{"variants":[{"paths":["\/documentation\/oneginisdkios\/appleidservice\/asauthorizationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/appleidservice\/asauthorizationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/ASAuthorizationControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithError:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"OneginiSDKiOS"}],"role":"collectionGroup","title":"ASAuthorizationControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService":{"role":"symbol","title":"AppleIdService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdService"}],"url":"\/documentation\/oneginisdkios\/appleidservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService/authorizationController(controller:didCompleteWithError:)":{"role":"symbol","title":"authorizationController(controller:didCompleteWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"url":"\/documentation\/oneginisdkios\/appleidservice\/authorizationcontroller(controller:didcompletewitherror:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService/authorizationController(controller:didCompleteWithAuthorization:)":{"role":"symbol","title":"authorizationController(controller:didCompleteWithAuthorization:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithAuthorization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorization","preciseIdentifier":"c:objc(cs)ASAuthorization"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithAuthorization:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}],"url":"\/documentation\/oneginisdkios\/appleidservice\/authorizationcontroller(controller:didcompletewithauthorization:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithAuthorization:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithError:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService\/title","value":"AppleIdService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService\/fragments","value":[{"kind":"identifier","text":"AppleIdService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithError:)\/title","value":"authorizationController:didCompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithAuthorization:)\/title","value":"authorizationController:didCompleteWithAuthorization:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithAuthorization:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithAuthorization:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}