{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/appleidservice\/authorizationcontroller(controller:didcompletewitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/appleidservice\/authorizationcontroller(controller:didcompletewitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ASAuthorizationControllerDelegate.authorizationController(controller:didCompleteWithError:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"role":"symbol","title":"authorizationController(controller:didCompleteWithError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@OneginiSDKiOS@objc(cs)AppleIdService(im)authorizationController:didCompleteWithError:","extendedModule":"OneginiSDKiOS","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/ASAuthorizationControllerDelegate-Implementations"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService/ASAuthorizationControllerDelegate-Implementations":{"role":"collectionGroup","title":"ASAuthorizationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/ASAuthorizationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/appleidservice\/asauthorizationcontrollerdelegate-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService":{"role":"symbol","title":"AppleIdService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdService"}],"url":"\/documentation\/oneginisdkios\/appleidservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdService/authorizationController(controller:didCompleteWithError:)":{"role":"symbol","title":"authorizationController(controller:didCompleteWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdService\/authorizationController(controller:didCompleteWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}],"url":"\/documentation\/oneginisdkios\/appleidservice\/authorizationcontroller(controller:didcompletewitherror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authorizationController:didCompleteWithError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"authorizationController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCompleteWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService\/title","value":"AppleIdService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService\/fragments","value":[{"kind":"identifier","text":"AppleIdService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithError:)\/title","value":"authorizationController:didCompleteWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdService~1authorizationController(controller:didCompleteWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationController:didCompleteWithError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}