{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generatePGPKeyPair"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUsername"},{"kind":"text","text":" "},{"kind":"internalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair","text":"ONGPGPKeyPair"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpgpcryptor\/generatepgpkeypair(withusername:password:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpgpcryptor\/generatepgpkeypair(withusername:password:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPCryptor\/generatePGPKeyPair(withUsername:password:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generatePGPKeyPair"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair"},{"kind":"text","text":"!"}],"title":"generatePGPKeyPair(withUsername:password:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGPGPCryptor(cm)generatePGPKeyPairWithUsername:password:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"generatePGPKeyPairWithUsername:password:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPCryptor"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPGPCryptor/generatePGPKeyPair(withUsername:password:)":{"role":"symbol","title":"generatePGPKeyPair(withUsername:password:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generatePGPKeyPair"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withUsername"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPCryptor\/generatePGPKeyPair(withUsername:password:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"generatePGPKeyPairWithUsername:password:"}],"url":"\/documentation\/oneginisdkios\/ongpgpcryptor\/generatepgpkeypair(withusername:password:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPGPKeyPair":{"role":"symbol","title":"ONGPGPKeyPair","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPGPKeyPair"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPKeyPair","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPGPKeyPair"}],"url":"\/documentation\/oneginisdkios\/ongpgpkeypair"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPGPCryptor":{"role":"symbol","title":"ONGPGPCryptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPGPCryptor"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPGPCryptor"}],"url":"\/documentation\/oneginisdkios\/ongpgpcryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"generatePGPKeyPairWithUsername:password:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"generatePGPKeyPairWithUsername:password:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair","text":"ONGPGPKeyPair"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generatePGPKeyPairWithUsername:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"username"},{"kind":"text","text":" "},{"kind":"identifier","text":"password:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"password"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPCryptor~1generatePGPKeyPair(withUsername:password:)\/title","value":"generatePGPKeyPairWithUsername:password:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPCryptor~1generatePGPKeyPair(withUsername:password:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"generatePGPKeyPairWithUsername:password:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPKeyPair\/title","value":"ONGPGPKeyPair"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPKeyPair\/fragments","value":[{"kind":"identifier","text":"ONGPGPKeyPair"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPCryptor\/title","value":"ONGPGPCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPGPCryptor\/fragments","value":[{"kind":"identifier","text":"ONGPGPCryptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}