{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationInvalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/configurationinvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/configurationinvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/configurationInvalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Token Server configuration is invalid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationInvalid"}],"title":"ONGGenericError.configurationInvalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGGenericError@ONGGenericErrorConfigurationInvalid","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError":{"role":"symbol","title":"ONGGenericError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}],"url":"\/documentation\/oneginisdkios\/onggenericerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/configurationInvalid":{"role":"symbol","title":"ONGGenericError.configurationInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationInvalid"}],"abstract":[{"type":"text","text":"The Token Server configuration is invalid."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/configurationInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/configurationinvalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGGenericErrorConfigurationInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/title","value":"ONGGenericError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1configurationInvalid\/title","value":"ONGGenericErrorConfigurationInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1configurationInvalid\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}