{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateTime"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/invaliddatetime"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/invaliddatetime"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/invalidDateTime","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The date or time used by the device is incorrect. Please check Date & Time Settings on the phone and sync them if necessary."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateTime"}],"title":"ONGGenericError.invalidDateTime","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGGenericError@ONGGenericErrorInvalidDateTime","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/invalidDateTime":{"role":"symbol","title":"ONGGenericError.invalidDateTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateTime"}],"abstract":[{"type":"text","text":"The date or time used by the device is incorrect. Please check Date & Time Settings on the phone and sync them if necessary."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/invalidDateTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/invaliddatetime"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError":{"role":"symbol","title":"ONGGenericError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}],"url":"\/documentation\/oneginisdkios\/onggenericerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGGenericErrorInvalidDateTime"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1invalidDateTime\/title","value":"ONGGenericErrorInvalidDateTime"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1invalidDateTime\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/title","value":"ONGGenericError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}