{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnectivityFailure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/networkconnectivityfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onggenericerror\/networkconnectivityfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/networkConnectivityFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Due to a problem with the device internet connection it was not possible to initiate the requested action."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnectivityFailure"}],"title":"ONGGenericError.networkConnectivityFailure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGGenericError@ONGGenericErrorNetworkConnectivityFailure","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/networkConnectivityFailure":{"role":"symbol","title":"ONGGenericError.networkConnectivityFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnectivityFailure"}],"abstract":[{"type":"text","text":"Due to a problem with the device internet connection it was not possible to initiate the requested action."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/networkConnectivityFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/networkconnectivityfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError":{"role":"symbol","title":"ONGGenericError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}],"url":"\/documentation\/oneginisdkios\/onggenericerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGGenericErrorNetworkConnectivityFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1networkConnectivityFailure\/title","value":"ONGGenericErrorNetworkConnectivityFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1networkConnectivityFailure\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/title","value":"ONGGenericError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}