{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol\/authorizationcontroller(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol\/authorizationcontroller(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol\/authorizationController(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"authorizationControllerWithDelegate:"}],"role":"symbol","title":"authorizationController(with:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"symbolKind":"method","externalID":"c:objc(pl)AppleIdAuthorizationControllerFactoryProtocol(im)authorizationControllerWithDelegate:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactoryProtocol/authorizationController(with:)":{"navigatorTitle":[{"kind":"identifier","text":"authorizationControllerWithDelegate:"}],"role":"symbol","title":"authorizationController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol\/authorizationController(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol\/authorizationcontroller(with:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactoryProtocol":{"role":"symbol","title":"AppleIdAuthorizationControllerFactoryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}],"url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authorizationControllerWithDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ASAuthorizationControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol~1authorizationController(with:)\/title","value":"authorizationControllerWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol~1authorizationController(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol\/title","value":"AppleIdAuthorizationControllerFactoryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol\/fragments","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}