{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/build()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/build()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/build()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The build instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" from the current parameters. Since the returned object is immutable any further parameter changes doesn’t"},{"type":"text","text":" "},{"type":"text","text":"have an effect on already build instances."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":"!"}],"title":"build()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGRequestBuilder(im)build","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"build"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder":{"role":"symbol","title":"ONGRequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"abstract":[{"type":"text","text":"Object responsible for easier "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestBuilder"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest":{"role":"symbol","title":"ONGResourceRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceRequest"}],"abstract":[{"type":"text","text":"The object that encapsulates arguments required for performing a network request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceRequest"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The build instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" from the current parameters. Since the returned object is immutable any further parameter changes doesn’t"},{"type":"text","text":" "},{"type":"text","text":"have an effect on already build instances."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/build()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"build"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/title","value":"ONGRequestBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/fragments","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/title","value":"ONGResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/fragments","value":[{"kind":"identifier","text":"ONGResourceRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}