{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMultipartData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"multipartData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData","text":"ONGMultipartData"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/setmultipartdata(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/setmultipartdata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMultipartData(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the multipartData for the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMultipartData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"title":"setMultipartData(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGRequestBuilder(im)setMultipartData:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"setMultipartData:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder":{"role":"symbol","title":"ONGRequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"abstract":[{"type":"text","text":"Object responsible for easier "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestBuilder"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setMultipartData(_:)":{"role":"symbol","title":"setMultipartData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMultipartData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the multipartData for the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMultipartData(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMultipartData:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setmultipartdata(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMultipartData":{"role":"symbol","title":"ONGMultipartData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMultipartData"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMultipartData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMultipartData"}],"url":"\/documentation\/oneginisdkios\/ongmultipartdata"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setMultipartData:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMultipartData:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"setMultipartData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<ONGMultipartData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"multipartData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/title","value":"ONGRequestBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/fragments","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMultipartData(_:)\/title","value":"setMultipartData:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMultipartData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMultipartData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMultipartData\/title","value":"ONGMultipartData"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMultipartData\/fragments","value":[{"kind":"identifier","text":"ONGMultipartData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}