{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParametersEncoding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"parametersEncoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding","text":"ONGParametersEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"ONGParametersEncodingJSON"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/setparametersencoding(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder\/setparametersencoding(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParametersEncoding(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the parametersEncoding for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParametersEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"title":"setParametersEncoding(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGRequestBuilder(im)setParametersEncoding:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"setParametersEncoding:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setParametersEncoding(_:)":{"role":"symbol","title":"setParametersEncoding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParametersEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the parametersEncoding for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParametersEncoding(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setParametersEncoding:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setparametersencoding(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder":{"role":"symbol","title":"ONGRequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"abstract":[{"type":"text","text":"Object responsible for easier "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestBuilder"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGParametersEncoding":{"role":"symbol","title":"ONGParametersEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGParametersEncoding"}],"abstract":[{"type":"text","text":"Supported types of parameters encoding during network request construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGParametersEncoding"}],"url":"\/documentation\/oneginisdkios\/ongparametersencoding"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setParametersEncoding:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setParametersEncoding:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"setParametersEncoding:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding","text":"ONGParametersEncoding"},{"kind":"text","text":")"},{"kind":"internalParam","text":"parametersEncoding"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParametersEncoding(_:)\/title","value":"setParametersEncoding:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParametersEncoding(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setParametersEncoding:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/title","value":"ONGRequestBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/fragments","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGParametersEncoding\/title","value":"ONGParametersEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGParametersEncoding\/fragments","value":[{"kind":"identifier","text":"ONGParametersEncoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}