{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteLocalData"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongdisconnectcontrollerprotocol\/deletelocaldata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongdisconnectcontrollerprotocol\/deletelocaldata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDisconnectControllerProtocol\/deleteLocalData()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"deleteLocalData"}],"role":"symbol","title":"deleteLocalData()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteLocalData"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)ONGDisconnectControllerProtocol(im)deleteLocalData","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDisconnectControllerProtocol"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDisconnectControllerProtocol/deleteLocalData()":{"navigatorTitle":[{"kind":"identifier","text":"deleteLocalData"}],"role":"symbol","title":"deleteLocalData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteLocalData"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDisconnectControllerProtocol\/deleteLocalData()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongdisconnectcontrollerprotocol\/deletelocaldata()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDisconnectControllerProtocol":{"role":"symbol","title":"ONGDisconnectControllerProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDisconnectControllerProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDisconnectControllerProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGDisconnectControllerProtocol"}],"url":"\/documentation\/oneginisdkios\/ongdisconnectcontrollerprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deleteLocalData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteLocalData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deleteLocalData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDisconnectControllerProtocol~1deleteLocalData()\/title","value":"deleteLocalData"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDisconnectControllerProtocol~1deleteLocalData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteLocalData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDisconnectControllerProtocol\/title","value":"ONGDisconnectControllerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDisconnectControllerProtocol\/fragments","value":[{"kind":"identifier","text":"ONGDisconnectControllerProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}