{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient","preciseIdentifier":"c:objc(cs)ONGClient","text":"ONGClient"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"retrieve them from "},{"type":"codeVoice","code":"OneginiConfigModel"},{"type":"text","text":" class (generated by SDK Configurator) - "},{"type":"codeVoice","code":"ONGSDKInitializationException"},{"type":"text","text":" will be thrown."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder\/build()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder\/build()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/build()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set up SDK and return configured instance of "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":" using builder’s values."},{"type":"text","text":" "},{"type":"text","text":"Subsequent calls will not take any effect on the instantiated "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClient","preciseIdentifier":"c:objc(cs)ONGClient"}],"title":"build()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGClientBuilder(im)build","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"build"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClient","preciseIdentifier":"c:objc(cs)ONGClient"}],"abstract":[{"type":"text","text":"Set up SDK and return configured instance of "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":" using builder’s values."},{"type":"text","text":" "},{"type":"text","text":"Subsequent calls will not take any effect on the instantiated "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/build()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient":{"role":"symbol","title":"ONGClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClient"}],"abstract":[{"type":"text","text":"Main entry point for the Onegini SDK. This class owns SDK’s configuration and such clients as "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":". In order to use any feature of the OneginiSDK "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":" needs to be called first."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClient"}],"url":"\/documentation\/oneginisdkios\/ongclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder":{"role":"symbol","title":"ONGClientBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"}],"abstract":[{"type":"codeVoice","code":"ONGClientBuilder"},{"type":"text","text":" is responsible for setting up SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientBuilder"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"build"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient","preciseIdentifier":"c:objc(cs)ONGClient","text":"ONGClient"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient\/title","value":"ONGClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient\/fragments","value":[{"kind":"identifier","text":"ONGClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/title","value":"ONGClientBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/fragments","value":[{"kind":"identifier","text":"ONGClientBuilder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}