{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setX509PEMCertificates"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method must be called before any service request is made, preferably after initialization."},{"type":"text","text":" "},{"type":"text","text":"If certificate verification fails prior to making a service request, an Exception is thrown."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To convert a DER encoded certificate to PEM, use the following openssl command:"},{"type":"text","text":" "},{"type":"text","text":"openssl x509 -in "},{"type":"text","text":".cer -inform der -out "},{"type":"text","text":".pem -outform pem"},{"type":"text","text":" "},{"type":"text","text":"Do not include the PEM files themselved in App bundle!"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder\/setx509pemcertificates(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder\/setx509pemcertificates(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setX509PEMCertificates(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For verification of the bundled DER encoded CA X509 certificates,"},{"type":"text","text":" "},{"type":"text","text":"the App must provide a list of matching PEM base64 encoded certificates for each bundled DER encoded CA X509 certificate to this client."},{"type":"text","text":" "},{"type":"text","text":"The PEM base64 encoded certificates must be stripped from their armor (remove —BEGIN CERTIFICATE— & —END CERTIFICATE—)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setX509PEMCertificates"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"setX509PEMCertificates(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGClientBuilder(im)setX509PEMCertificates:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"setX509PEMCertificates:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder":{"role":"symbol","title":"ONGClientBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"}],"abstract":[{"type":"codeVoice","code":"ONGClientBuilder"},{"type":"text","text":" is responsible for setting up SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientBuilder"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setX509PEMCertificates(_:)":{"role":"symbol","title":"setX509PEMCertificates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setX509PEMCertificates"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"For verification of the bundled DER encoded CA X509 certificates,"},{"type":"text","text":" "},{"type":"text","text":"the App must provide a list of matching PEM base64 encoded certificates for each bundled DER encoded CA X509 certificate to this client."},{"type":"text","text":" "},{"type":"text","text":"The PEM base64 encoded certificates must be stripped from their armor (remove —BEGIN CERTIFICATE— & —END CERTIFICATE—)"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setX509PEMCertificates(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setX509PEMCertificates:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setx509pemcertificates(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setX509PEMCertificates:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setX509PEMCertificates:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"setX509PEMCertificates:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"certificates"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/title","value":"ONGClientBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/fragments","value":[{"kind":"identifier","text":"ONGClientBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setX509PEMCertificates(_:)\/title","value":"setX509PEMCertificates:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setX509PEMCertificates(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setX509PEMCertificates:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}