{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identityProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider","text":"ONGIdentityProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned error will be either within the ONGGenericErrorDomain or the ONGRegistrationErrorDomain."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didfailtoregisterwith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didfailtoregisterwith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didFailToRegisterWith:error:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method called when registration action failed with error."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}],"role":"symbol","title":"userClient(_:didFailToRegisterWith:error:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)ONGRegistrationDelegate(im)userClient:didFailToRegisterWithIdentityProvider:error:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate":{"role":"symbol","title":"ONGRegistrationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete registration."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didFailToRegisterWith:error:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}],"role":"symbol","title":"userClient(_:didFailToRegisterWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when registration action failed with error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didFailToRegisterWith:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didfailtoregisterwith:error:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGIdentityProvider":{"role":"symbol","title":"ONGIdentityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGIdentityProvider"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGIdentityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGIdentityProvider"}],"url":"\/documentation\/oneginisdkios\/ongidentityprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userClient:didFailToRegisterWithIdentityProvider:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userClient:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailToRegisterWithIdentityProvider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider","text":"ONGIdentityProvider"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"identityProvider"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/title","value":"ONGRegistrationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didFailToRegisterWith:error:)\/title","value":"userClient:didFailToRegisterWithIdentityProvider:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didFailToRegisterWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGIdentityProvider\/title","value":"ONGIdentityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGIdentityProvider\/fragments","value":[{"kind":"identifier","text":"ONGIdentityProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}