{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveCustomRegistrationFinish"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge","text":"ONGCustomRegistrationChallenge"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivecustomregistrationfinish:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivecustomregistrationfinish:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationFinish:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method called when the second step of two step custom registration or one step custom registration requires a optional data to continue."},{"type":"text","text":" "},{"type":"text","text":"You now need to call the respondWithData:challenge: method of id"},{"type":"text","text":" instance, in order to provide optional data to the finish step and continue the two step registration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveCustomRegistrationFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge"},{"kind":"text","text":")"}],"title":"userClient(_:didReceiveCustomRegistrationFinish:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)ONGRegistrationDelegate(im)userClient:didReceiveCustomRegistrationFinishChallenge:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomRegistrationChallenge":{"role":"symbol","title":"ONGCustomRegistrationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomRegistrationChallenge"}],"abstract":[{"type":"text","text":"Represents custom registration challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomRegistrationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomRegistrationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcustomregistrationchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didReceiveCustomRegistrationFinish:)":{"role":"symbol","title":"userClient(_:didReceiveCustomRegistrationFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveCustomRegistrationFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when the second step of two step custom registration or one step custom registration requires a optional data to continue."},{"type":"text","text":" "},{"type":"text","text":"You now need to call the respondWithData:challenge: method of id"},{"type":"text","text":" instance, in order to provide optional data to the finish step and continue the two step registration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivecustomregistrationfinish:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate":{"role":"symbol","title":"ONGRegistrationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete registration."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userClient:didReceiveCustomRegistrationFinishChallenge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userClient:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveCustomRegistrationFinishChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge","text":"ONGCustomRegistrationChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomRegistrationChallenge\/title","value":"ONGCustomRegistrationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomRegistrationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCustomRegistrationChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationFinish:)\/title","value":"userClient:didReceiveCustomRegistrationFinishChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/title","value":"ONGRegistrationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}