{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localLogout"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onglogouterror\/locallogout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onglogouterror\/locallogout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGLogoutError\/localLogout","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user was only logged out on the device. The access token has not been invalidated on the server-side. This does not pose a problem but you might want to inform the end-user as he might be able to see that he\/she is still logged in through a web portal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localLogout"}],"title":"ONGLogoutError.localLogout","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGLogoutError@ONGLogoutErrorLocalLogout","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGLogoutErrorLocalLogout"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGLogoutError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGLogoutError":{"role":"symbol","title":"ONGLogoutError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGLogoutError"}],"abstract":[{"type":"text","text":"Error codes in ONGLogoutErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGLogoutError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGLogoutError"}],"url":"\/documentation\/oneginisdkios\/onglogouterror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGLogoutError/localLogout":{"role":"symbol","title":"ONGLogoutError.localLogout","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localLogout"}],"abstract":[{"type":"text","text":"The user was only logged out on the device. The access token has not been invalidated on the server-side. This does not pose a problem but you might want to inform the end-user as he might be able to see that he\/she is still logged in through a web portal."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGLogoutError\/localLogout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGLogoutErrorLocalLogout"}],"url":"\/documentation\/oneginisdkios\/onglogouterror\/locallogout"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGLogoutErrorLocalLogout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGLogoutErrorLocalLogout"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGLogoutErrorLocalLogout"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGLogoutError\/title","value":"ONGLogoutError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGLogoutError\/fragments","value":[{"kind":"identifier","text":"ONGLogoutError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGLogoutError~1localLogout\/title","value":"ONGLogoutErrorLocalLogout"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGLogoutError~1localLogout\/fragments","value":[{"kind":"identifier","text":"ONGLogoutErrorLocalLogout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}