{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongnetworktask\/request"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongnetworktask\/request"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask\/request","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The request, provided to the "},{"type":"codeVoice","code":"-[ONGUserClient fetchResource:completion:]"},{"type":"text","text":", "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchResource:completion:]"},{"type":"text","text":" and "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchUnauthenticatedResource:completion:]"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"}],"title":"request","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGNetworkTask(py)request","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"request"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTask/request":{"role":"symbol","title":"request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"}],"abstract":[{"type":"text","text":"The request, provided to the "},{"type":"codeVoice","code":"-[ONGUserClient fetchResource:completion:]"},{"type":"text","text":", "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchResource:completion:]"},{"type":"text","text":" and "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchUnauthenticatedResource:completion:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask\/request","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"request"}],"url":"\/documentation\/oneginisdkios\/ongnetworktask\/request"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest":{"role":"symbol","title":"ONGResourceRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceRequest"}],"abstract":[{"type":"text","text":"The object that encapsulates arguments required for performing a network request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceRequest"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTask":{"role":"symbol","title":"ONGNetworkTask","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGNetworkTask"}],"abstract":[{"type":"codeVoice","code":"ONGNetworkTask"},{"type":"text","text":" is a cancelable object, representing the actual network request."},{"type":"text","text":" "},{"type":"text","text":"It offers cancelling, pausing and resuming requests."},{"type":"text","text":" "},{"type":"text","text":"Produced by "},{"type":"codeVoice","code":"-[ONGUserClient fetchResource:completion:]"},{"type":"text","text":", "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchResource:completion:]"},{"type":"text","text":" and "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchUnauthenticatedResource:completion:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTask"}],"url":"\/documentation\/oneginisdkios\/ongnetworktask"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"request"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":" * "},{"kind":"identifier","text":"request"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask~1request\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask~1request\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/title","value":"ONGResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/fragments","value":[{"kind":"identifier","text":"ONGResourceRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/title","value":"ONGNetworkTask"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTask"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}