{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspend"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any attempt to suspend an already suspended, cancelled ("},{"type":"codeVoice","code":"ONGNetworkTaskStateCancelled"},{"type":"text","text":") or completed ("},{"type":"codeVoice","code":"ONGNetworkTaskStateCompleted"},{"type":"text","text":") task doesn’t have"},{"type":"text","text":" "},{"type":"text","text":"any effect."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongnetworktask\/suspend()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongnetworktask\/suspend()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask\/suspend()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Suspend running task. This moves a task from the "},{"type":"codeVoice","code":"ONGNetworkTaskStateRunning"},{"type":"text","text":" state to the "},{"type":"codeVoice","code":"ONGNetworkTaskStateSuspended"},{"type":"text","text":" state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspend"},{"kind":"text","text":"()"}],"title":"suspend()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGNetworkTask(im)suspend","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"suspend"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTask/suspend()":{"role":"symbol","title":"suspend()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"suspend"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Suspend running task. This moves a task from the "},{"type":"codeVoice","code":"ONGNetworkTaskStateRunning"},{"type":"text","text":" state to the "},{"type":"codeVoice","code":"ONGNetworkTaskStateSuspended"},{"type":"text","text":" state."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask\/suspend()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"suspend"}],"url":"\/documentation\/oneginisdkios\/ongnetworktask\/suspend()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTask":{"role":"symbol","title":"ONGNetworkTask","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGNetworkTask"}],"abstract":[{"type":"codeVoice","code":"ONGNetworkTask"},{"type":"text","text":" is a cancelable object, representing the actual network request."},{"type":"text","text":" "},{"type":"text","text":"It offers cancelling, pausing and resuming requests."},{"type":"text","text":" "},{"type":"text","text":"Produced by "},{"type":"codeVoice","code":"-[ONGUserClient fetchResource:completion:]"},{"type":"text","text":", "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchResource:completion:]"},{"type":"text","text":" and "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchUnauthenticatedResource:completion:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTask"}],"url":"\/documentation\/oneginisdkios\/ongnetworktask"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"suspend"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"suspend"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"suspend"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask~1suspend()\/title","value":"suspend"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask~1suspend()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"suspend"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/title","value":"ONGNetworkTask"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTask"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}