{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBiometricChallenge","preciseIdentifier":"c:objc(cs)ONGBiometricChallenge","text":"ONGBiometricChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest","text":"ONGMobileAuthRequest"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didreceive:for:)-5wwfy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didreceive:for:)-5wwfy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate\/userClient(_:didReceive:for:)-5wwfy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method called when authentication action requires TouchID or FaceID to continue. Its called before asking user for fingerprint or face."},{"type":"text","text":" "},{"type":"text","text":"If its not implemented SDK will fallback to PIN code confirmation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBiometricChallenge","preciseIdentifier":"c:objc(cs)ONGBiometricChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest"},{"kind":"text","text":")"}],"title":"userClient(_:didReceive:for:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)ONGMobileAuthRequestDelegate(im)userClient:didReceiveBiometricChallenge:forRequest:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:forRequest:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestDelegate":{"role":"symbol","title":"ONGMobileAuthRequestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete mobile authentication request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBiometricChallenge":{"role":"symbol","title":"ONGBiometricChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBiometricChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with biometric challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBiometricChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGBiometricChallenge"}],"url":"\/documentation\/oneginisdkios\/ongbiometricchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestDelegate/userClient(_:didReceive:for:)-5wwfy":{"role":"symbol","title":"userClient(_:didReceive:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBiometricChallenge","preciseIdentifier":"c:objc(cs)ONGBiometricChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action requires TouchID or FaceID to continue. Its called before asking user for fingerprint or face."},{"type":"text","text":" "},{"type":"text","text":"If its not implemented SDK will fallback to PIN code confirmation."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate\/userClient(_:didReceive:for:)-5wwfy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:forRequest:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didreceive:for:)-5wwfy"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequest":{"role":"symbol","title":"ONGMobileAuthRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthRequest"}],"abstract":[{"type":"text","text":"The class representing mobile authentication request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequest"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequest"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userClient:didReceiveBiometricChallenge:forRequest:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:forRequest:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userClient:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveBiometricChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBiometricChallenge","preciseIdentifier":"c:objc(cs)ONGBiometricChallenge","text":"ONGBiometricChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":" "},{"kind":"identifier","text":"forRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest","text":"ONGMobileAuthRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate\/title","value":"ONGMobileAuthRequestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBiometricChallenge\/title","value":"ONGBiometricChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBiometricChallenge\/fragments","value":[{"kind":"identifier","text":"ONGBiometricChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate~1userClient(_:didReceive:for:)-5wwfy\/title","value":"userClient:didReceiveBiometricChallenge:forRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate~1userClient(_:didReceive:for:)-5wwfy\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:forRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequest\/title","value":"ONGMobileAuthRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequest\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}