{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didHandle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest","text":"ONGMobileAuthRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"info"},{"kind":"text","text":" "},{"kind":"internalParam","text":"customAuthenticatorInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo","text":"ONGCustomInfo"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didhandle:authenticator:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didhandle:authenticator:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate\/userClient(_:didHandle:authenticator:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method called when mobile authentication request handled successfully."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didHandleMobileAuthRequest:authenticator:info:"}],"role":"symbol","title":"userClient(_:didHandle:authenticator:info:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didHandle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)ONGMobileAuthRequestDelegate(im)userClient:didHandleMobileAuthRequest:authenticator:info:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequest":{"role":"symbol","title":"ONGMobileAuthRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthRequest"}],"abstract":[{"type":"text","text":"The class representing mobile authentication request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequest"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestDelegate/userClient(_:didHandle:authenticator:info:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didHandleMobileAuthRequest:authenticator:info:"}],"role":"symbol","title":"userClient(_:didHandle:authenticator:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didHandle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method called when mobile authentication request handled successfully."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate\/userClient(_:didHandle:authenticator:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate\/userclient(_:didhandle:authenticator:info:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestDelegate":{"role":"symbol","title":"ONGMobileAuthRequestDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete mobile authentication request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequestdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticator":{"role":"symbol","title":"ONGAuthenticator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents an authenticator. Authenticator objects can be obtained using "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomInfo":{"role":"symbol","title":"ONGCustomInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomInfo"}],"abstract":[{"type":"text","text":"The class representing Custom Authenticator related response from Extension Engine."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomInfo"}],"url":"\/documentation\/oneginisdkios\/ongcustominfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userClient:didHandleMobileAuthRequest:authenticator:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didHandleMobileAuthRequest:authenticator:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userClient:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":" "},{"kind":"identifier","text":"didHandleMobileAuthRequest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGMobileAuthRequest","text":"ONGMobileAuthRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo","text":"ONGCustomInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customAuthenticatorInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequest\/title","value":"ONGMobileAuthRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequest\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate~1userClient(_:didHandle:authenticator:info:)\/title","value":"userClient:didHandleMobileAuthRequest:authenticator:info:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate~1userClient(_:didHandle:authenticator:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didHandleMobileAuthRequest:authenticator:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate\/title","value":"ONGMobileAuthRequestDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestDelegate\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequestDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/title","value":"ONGAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomInfo\/title","value":"ONGCustomInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomInfo\/fragments","value":[{"kind":"identifier","text":"ONGCustomInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}