{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebTokenService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebTokenServiceProtocol","text":"JSONWebTokenServiceProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/validateclientnetworkservice\/jsonwebtokenservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/validateclientnetworkservice\/jsonwebtokenservice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ValidateClientNetworkService\/jsonWebTokenService","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebTokenService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebTokenServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebTokenServiceProtocol"},{"kind":"text","text":"?"}],"title":"jsonWebTokenService","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)ValidateClientNetworkService(py)jsonWebTokenService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"jsonWebTokenService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ValidateClientNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ValidateClientNetworkService":{"role":"symbol","title":"ValidateClientNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidateClientNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ValidateClientNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidateClientNetworkService"}],"url":"\/documentation\/oneginisdkios\/validateclientnetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ValidateClientNetworkService/jsonWebTokenService":{"role":"symbol","title":"jsonWebTokenService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebTokenService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebTokenServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebTokenServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ValidateClientNetworkService\/jsonWebTokenService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jsonWebTokenService"}],"url":"\/documentation\/oneginisdkios\/validateclientnetworkservice\/jsonwebtokenservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenServiceProtocol":{"role":"symbol","title":"JSONWebTokenServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/jsonwebtokenserviceprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"jsonWebTokenService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"jsonWebTokenService"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<JSONWebTokenServiceProtocol>","preciseIdentifier":"c:Qoobjc(pl)JSONWebTokenServiceProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"jsonWebTokenService"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ValidateClientNetworkService\/title","value":"ValidateClientNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ValidateClientNetworkService\/fragments","value":[{"kind":"identifier","text":"ValidateClientNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ValidateClientNetworkService~1jsonWebTokenService\/title","value":"jsonWebTokenService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ValidateClientNetworkService~1jsonWebTokenService\/fragments","value":[{"kind":"identifier","text":"jsonWebTokenService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol\/title","value":"JSONWebTokenServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol\/fragments","value":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}