{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorInvalidMethod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorinvalidmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorinvalidmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidMethod","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"provided request method is not valid, use one of @“GET”, @“POST”, @“DELETE”, @“PUT”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorInvalidMethod"}],"title":"ONGFetchResourceImplicitlyError.implicitResourceErrorInvalidMethod","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchResourceImplicitlyError@ONGFetchImplicitResourceErrorInvalidMethod","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError":{"role":"symbol","title":"ONGFetchResourceImplicitlyError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/implicitResourceErrorInvalidMethod":{"role":"symbol","title":"ONGFetchResourceImplicitlyError.implicitResourceErrorInvalidMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorInvalidMethod"}],"abstract":[{"type":"text","text":"provided request method is not valid, use one of @“GET”, @“POST”, @“DELETE”, @“PUT”"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorinvalidmethod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchImplicitResourceErrorInvalidMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/title","value":"ONGFetchResourceImplicitlyError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidMethod\/title","value":"ONGFetchImplicitResourceErrorInvalidMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidMethod\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}