{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorUserNotAuthenticatedImplicitly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorusernotauthenticatedimplicitly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorusernotauthenticatedimplicitly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorUserNotAuthenticatedImplicitly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No user is currently authenticated implicitly, possibly due to the fact that the implicit access token has expired. A user must be authenticated in order to fetch resources."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorUserNotAuthenticatedImplicitly"}],"title":"ONGFetchResourceImplicitlyError.implicitResourceErrorUserNotAuthenticatedImplicitly","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchResourceImplicitlyError@ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError":{"role":"symbol","title":"ONGFetchResourceImplicitlyError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/implicitResourceErrorUserNotAuthenticatedImplicitly":{"role":"symbol","title":"ONGFetchResourceImplicitlyError.implicitResourceErrorUserNotAuthenticatedImplicitly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorUserNotAuthenticatedImplicitly"}],"abstract":[{"type":"text","text":"No user is currently authenticated implicitly, possibly due to the fact that the implicit access token has expired. A user must be authenticated in order to fetch resources."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorUserNotAuthenticatedImplicitly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorusernotauthenticatedimplicitly"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/title","value":"ONGFetchResourceImplicitlyError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorUserNotAuthenticatedImplicitly\/title","value":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorUserNotAuthenticatedImplicitly\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}