{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge","text":"ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUnderlyingError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":null,"code":["    within the cancellation error returned in the deregistration failure method."]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender\/cancel(_:withunderlyingerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender\/cancel(_:withunderlyingerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/cancel(_:withUnderlyingError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to cancel deregistration."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}],"role":"symbol","title":"cancel(_:withUnderlyingError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUnderlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)ONGCustomAuthDeregistrationChallengeSender(im)cancelChallenge:withUnderlyingError:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallengeSender":{"role":"symbol","title":"ONGCustomAuthDeregistrationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to deregistration of custom authenticator."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallenge":{"role":"symbol","title":"ONGCustomAuthDeregistrationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"abstract":[{"type":"text","text":"Represents deregistration challenge of custom authenticator. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallengeSender/cancel(_:withUnderlyingError:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}],"role":"symbol","title":"cancel(_:withUnderlyingError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUnderlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to cancel deregistration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/cancel(_:withUnderlyingError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender\/cancel(_:withunderlyingerror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cancelChallenge:withUnderlyingError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge","text":"ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":" "},{"kind":"identifier","text":"withUnderlyingError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"underlyingError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender\/title","value":"ONGCustomAuthDeregistrationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge\/title","value":"ONGCustomAuthDeregistrationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1cancel(_:withUnderlyingError:)\/title","value":"cancelChallenge:withUnderlyingError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1cancel(_:withUnderlyingError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}