{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payloadEncryptionDisabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpayloadencryptionerrorcode\/payloadencryptiondisabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpayloadencryptionerrorcode\/payloadencryptiondisabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPayloadEncryptionErrorCode\/payloadEncryptionDisabled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payloadEncryptionDisabled"}],"title":"ONGPayloadEncryptionErrorCode.payloadEncryptionDisabled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGPayloadEncryptionErrorCode@ONGPayloadEncryptionErrorPayloadEncryptionDisabled","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPayloadEncryptionErrorCode"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPayloadEncryptionErrorCode/payloadEncryptionDisabled":{"role":"symbol","title":"ONGPayloadEncryptionErrorCode.payloadEncryptionDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payloadEncryptionDisabled"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPayloadEncryptionErrorCode\/payloadEncryptionDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"}],"url":"\/documentation\/oneginisdkios\/ongpayloadencryptionerrorcode\/payloadencryptiondisabled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPayloadEncryptionErrorCode":{"role":"symbol","title":"ONGPayloadEncryptionErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPayloadEncryptionErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPayloadEncryptionErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongpayloadencryptionerrorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPayloadEncryptionErrorCode~1payloadEncryptionDisabled\/title","value":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPayloadEncryptionErrorCode~1payloadEncryptionDisabled\/fragments","value":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorPayloadEncryptionDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPayloadEncryptionErrorCode\/title","value":"ONGPayloadEncryptionErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPayloadEncryptionErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGPayloadEncryptionErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}