{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens","text":"ONGSessionTokens"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongoauthsessionmodel\/sessiontokens"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongoauthsessionmodel\/sessiontokens"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/sessionTokens","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"title":"sessionTokens","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGOAuthSessionModel(py)sessionTokens","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGSessionTokens":{"role":"symbol","title":"ONGSessionTokens","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGSessionTokens"}],"abstract":[{"type":"text","text":"Access token data transfer object, part of the OAUTH data model"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongsessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/sessionTokens":{"role":"symbol","title":"sessionTokens","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/sessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/sessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel":{"role":"symbol","title":"ONGOAuthSessionModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGOAuthSessionModel"}],"abstract":[{"type":"text","text":"This class provides access to session scope properties."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGOAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sessionTokens"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sessionTokens"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens","text":"ONGSessionTokens"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sessionTokens"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/title","value":"ONGSessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1sessionTokens\/title","value":"sessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1sessionTokens\/fragments","value":[{"kind":"identifier","text":"sessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel\/title","value":"ONGOAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"ONGOAuthSessionModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}