{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebKeySetService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebKeySetServiceProtocol","text":"JSONWebKeySetServiceProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/jsonwebkeysetservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/jsonwebkeysetservice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/jsonWebKeySetService","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebKeySetService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebKeySetServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebKeySetServiceProtocol"},{"kind":"text","text":"?"}],"title":"jsonWebKeySetService","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)ClientMigrationNetworkService(py)jsonWebKeySetService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"jsonWebKeySetService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService":{"role":"symbol","title":"ClientMigrationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientMigrationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientMigrationNetworkService"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebKeySetServiceProtocol":{"role":"symbol","title":"JSONWebKeySetServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/jsonwebkeysetserviceprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService/jsonWebKeySetService":{"role":"symbol","title":"jsonWebKeySetService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebKeySetService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebKeySetServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebKeySetServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/jsonWebKeySetService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jsonWebKeySetService"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/jsonwebkeysetservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"jsonWebKeySetService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"jsonWebKeySetService"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<JSONWebKeySetServiceProtocol>","preciseIdentifier":"c:Qoobjc(pl)JSONWebKeySetServiceProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"jsonWebKeySetService"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/title","value":"ClientMigrationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/fragments","value":[{"kind":"identifier","text":"ClientMigrationNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol\/title","value":"JSONWebKeySetServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol\/fragments","value":[{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1jsonWebKeySetService\/title","value":"jsonWebKeySetService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1jsonWebKeySetService\/fragments","value":[{"kind":"identifier","text":"jsonWebKeySetService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}