{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestMigrationChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials","text":"ONGClientCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientChallengeResponse","preciseIdentifier":"c:objc(cs)ONGClientChallengeResponse","text":"ONGClientChallengeResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestmigrationchallenge(clientcredentials:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestmigrationchallenge(clientcredentials:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/requestMigrationChallenge(clientCredentials:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestMigrationChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGClientChallengeResponse","preciseIdentifier":"c:objc(cs)ONGClientChallengeResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"requestMigrationChallenge(clientCredentials:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)ClientMigrationNetworkService(im)requestMigrationChallengeWithClientCredentials:completion:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"requestMigrationChallengeWithClientCredentials:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService/requestMigrationChallenge(clientCredentials:completion:)":{"role":"symbol","title":"requestMigrationChallenge(clientCredentials:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestMigrationChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGClientChallengeResponse","preciseIdentifier":"c:objc(cs)ONGClientChallengeResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/requestMigrationChallenge(clientCredentials:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestMigrationChallengeWithClientCredentials:completion:"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestmigrationchallenge(clientcredentials:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientCredentials":{"role":"symbol","title":"ONGClientCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientCredentials"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientCredentials"}],"url":"\/documentation\/oneginisdkios\/ongclientcredentials"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientChallengeResponse":{"role":"symbol","title":"ONGClientChallengeResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientChallengeResponse"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientChallengeResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientChallengeResponse"}],"url":"\/documentation\/oneginisdkios\/ongclientchallengeresponse"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService":{"role":"symbol","title":"ClientMigrationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientMigrationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientMigrationNetworkService"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requestMigrationChallengeWithClientCredentials:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestMigrationChallengeWithClientCredentials:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestMigrationChallengeWithClientCredentials:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials","text":"ONGClientCredentials"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientCredentials"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ONGClientChallengeResponse *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)ONGClientChallengeResponse#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1requestMigrationChallenge(clientCredentials:completion:)\/title","value":"requestMigrationChallengeWithClientCredentials:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1requestMigrationChallenge(clientCredentials:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestMigrationChallengeWithClientCredentials:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientCredentials\/title","value":"ONGClientCredentials"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientCredentials\/fragments","value":[{"kind":"identifier","text":"ONGClientCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientChallengeResponse\/title","value":"ONGClientChallengeResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientChallengeResponse\/fragments","value":[{"kind":"identifier","text":"ONGClientChallengeResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/title","value":"ClientMigrationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/fragments","value":[{"kind":"identifier","text":"ClientMigrationNetworkService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}