{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel","text":"ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestserializermodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestserializermodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/requestSerializerModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"title":"requestSerializerModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)ClientMigrationNetworkService(py)requestSerializerModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService":{"role":"symbol","title":"ClientMigrationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientMigrationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientMigrationNetworkService"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientMigrationNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientMigrationNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/clientmigrationnetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestSerializerModel":{"role":"symbol","title":"ONGRequestSerializerModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestSerializerModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/ongrequestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel","text":"ONGRequestSerializerModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requestSerializerModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/title","value":"ClientMigrationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService\/fragments","value":[{"kind":"identifier","text":"ClientMigrationNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientMigrationNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/title","value":"ONGRequestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/fragments","value":[{"kind":"identifier","text":"ONGRequestSerializerModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}