{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchunauthenticatedresourceerror\/invalidheaders"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchunauthenticatedresourceerror\/invalidheaders"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchUnauthenticatedResourceError\/invalidHeaders","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"provided request headers are not valid"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"title":"ONGFetchUnauthenticatedResourceError.invalidHeaders","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchUnauthenticatedResourceError@ONGFetchUnauthenticatedResourceErrorInvalidHeaders","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchUnauthenticatedResourceError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchUnauthenticatedResourceError":{"role":"symbol","title":"ONGFetchUnauthenticatedResourceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceError"}],"abstract":[{"type":"text","text":"Error codes in ONGFetchUnauthenticatedResource"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchUnauthenticatedResourceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceError"}],"url":"\/documentation\/oneginisdkios\/ongfetchunauthenticatedresourceerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchUnauthenticatedResourceError/invalidHeaders":{"role":"symbol","title":"ONGFetchUnauthenticatedResourceError.invalidHeaders","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"abstract":[{"type":"text","text":"provided request headers are not valid"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchUnauthenticatedResourceError\/invalidHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"}],"url":"\/documentation\/oneginisdkios\/ongfetchunauthenticatedresourceerror\/invalidheaders"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchUnauthenticatedResourceError\/title","value":"ONGFetchUnauthenticatedResourceError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchUnauthenticatedResourceError\/fragments","value":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchUnauthenticatedResourceError~1invalidHeaders\/title","value":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchUnauthenticatedResourceError~1invalidHeaders\/fragments","value":[{"kind":"identifier","text":"ONGFetchUnauthenticatedResourceErrorInvalidHeaders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}