{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthFinishRegistrationChallenge","text":"ONGCustomAuthFinishRegistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":null,"code":["    within the cancellation error returned in the registration failure method."]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcustomauthfinishregistrationchallengesender\/cancel(_:underlyingerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcustomauthfinishregistrationchallengesender\/cancel(_:underlyingerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallengeSender\/cancel(_:underlyingError:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to cancel registration."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:underlyingError:"}],"role":"symbol","title":"cancel(_:underlyingError:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCustomAuthFinishRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthFinishRegistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)ONGCustomAuthFinishRegistrationChallengeSender(im)cancelChallenge:underlyingError:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallengeSender"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishRegistrationChallengeSender/cancel(_:underlyingError:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:underlyingError:"}],"role":"symbol","title":"cancel(_:underlyingError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCustomAuthFinishRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthFinishRegistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to cancel registration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallengeSender\/cancel(_:underlyingError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcustomauthfinishregistrationchallengesender\/cancel(_:underlyingerror:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishRegistrationChallengeSender":{"role":"symbol","title":"ONGCustomAuthFinishRegistrationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to registration of custom authenticator."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthfinishregistrationchallengesender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishRegistrationChallenge":{"role":"symbol","title":"ONGCustomAuthFinishRegistrationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallenge"}],"abstract":[{"type":"text","text":"Represents registration challenge of custom authenticator. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthfinishregistrationchallenge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cancelChallenge:underlyingError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:underlyingError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthFinishRegistrationChallenge","text":"ONGCustomAuthFinishRegistrationChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlyingError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"underlyingError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallengeSender~1cancel(_:underlyingError:)\/title","value":"cancelChallenge:underlyingError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallengeSender~1cancel(_:underlyingError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:underlyingError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallengeSender\/title","value":"ONGCustomAuthFinishRegistrationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallenge\/title","value":"ONGCustomAuthFinishRegistrationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishRegistrationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthFinishRegistrationChallenge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}