{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorAuthenticatorNotSupported"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorauthenticatornotsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorauthenticatornotsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError\/deregistrationErrorAuthenticatorNotSupported","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The given authenticator is not supported."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorAuthenticatorNotSupported"}],"title":"ONGAuthenticatorDeregistrationError.deregistrationErrorAuthenticatorNotSupported","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGAuthenticatorDeregistrationError@ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationError":{"role":"symbol","title":"ONGAuthenticatorDeregistrationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"abstract":[{"type":"text","text":"Error codes in ONGAuthenticatorDeregistrationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationError/deregistrationErrorAuthenticatorNotSupported":{"role":"symbol","title":"ONGAuthenticatorDeregistrationError.deregistrationErrorAuthenticatorNotSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorAuthenticatorNotSupported"}],"abstract":[{"type":"text","text":"The given authenticator is not supported."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError\/deregistrationErrorAuthenticatorNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorauthenticatornotsupported"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/title","value":"ONGAuthenticatorDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError~1deregistrationErrorAuthenticatorNotSupported\/title","value":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError~1deregistrationErrorAuthenticatorNotSupported\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorAuthenticatorNotSupported"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}