{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorDeregisteredLocally"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorderegisteredlocally"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorderegisteredlocally"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError\/deregistrationErrorDeregisteredLocally","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authenticator was deregister only locally. It was not deregister on the server side."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorDeregisteredLocally"}],"title":"ONGAuthenticatorDeregistrationError.deregistrationErrorDeregisteredLocally","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGAuthenticatorDeregistrationError@ONGAuthenticatorDeregistrationErrorDeregisteredLocally","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationError/deregistrationErrorDeregisteredLocally":{"role":"symbol","title":"ONGAuthenticatorDeregistrationError.deregistrationErrorDeregisteredLocally","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregistrationErrorDeregisteredLocally"}],"abstract":[{"type":"text","text":"Authenticator was deregister only locally. It was not deregister on the server side."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError\/deregistrationErrorDeregisteredLocally","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror\/deregistrationerrorderegisteredlocally"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationError":{"role":"symbol","title":"ONGAuthenticatorDeregistrationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"abstract":[{"type":"text","text":"Error codes in ONGAuthenticatorDeregistrationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError~1deregistrationErrorDeregisteredLocally\/title","value":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError~1deregistrationErrorDeregisteredLocally\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationErrorDeregisteredLocally"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/title","value":"ONGAuthenticatorDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}