{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrationIdConflict"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientregistrationerrorcode\/registrationidconflict"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientregistrationerrorcode\/registrationidconflict"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientRegistrationErrorCode\/registrationIdConflict","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrationIdConflict"}],"title":"ONGClientRegistrationErrorCode.registrationIdConflict","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGClientRegistrationErrorCode@ONGClientRegistrationErrorRegistrationIdConflict","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGClientRegistrationErrorRegistrationIdConflict"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientRegistrationErrorCode"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientRegistrationErrorCode":{"role":"symbol","title":"ONGClientRegistrationErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientRegistrationErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientRegistrationErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientRegistrationErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongclientregistrationerrorcode"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientRegistrationErrorCode/registrationIdConflict":{"role":"symbol","title":"ONGClientRegistrationErrorCode.registrationIdConflict","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"registrationIdConflict"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientRegistrationErrorCode\/registrationIdConflict","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientRegistrationErrorRegistrationIdConflict"}],"url":"\/documentation\/oneginisdkios\/ongclientregistrationerrorcode\/registrationidconflict"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGClientRegistrationErrorRegistrationIdConflict"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGClientRegistrationErrorRegistrationIdConflict"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGClientRegistrationErrorRegistrationIdConflict"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientRegistrationErrorCode\/title","value":"ONGClientRegistrationErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientRegistrationErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGClientRegistrationErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientRegistrationErrorCode~1registrationIdConflict\/title","value":"ONGClientRegistrationErrorRegistrationIdConflict"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientRegistrationErrorCode~1registrationIdConflict\/fragments","value":[{"kind":"identifier","text":"ONGClientRegistrationErrorRegistrationIdConflict"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}