{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallengeSender","preciseIdentifier":"c:objc(pl)ONGCustomAuthFinishAuthenticationChallengeSender","text":"ONGCustomAuthFinishAuthenticationChallengeSender"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcustomauthfinishauthenticationchallenge\/sender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcustomauthfinishauthenticationchallenge\/sender"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallenge\/sender","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sender awaiting for response to the authenticate with custom authenticator challenge."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomAuthFinishAuthenticationChallengeSender","preciseIdentifier":"c:objc(pl)ONGCustomAuthFinishAuthenticationChallengeSender"}],"title":"sender","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGCustomAuthFinishAuthenticationChallenge(py)sender","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"sender"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallenge"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishAuthenticationChallenge/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomAuthFinishAuthenticationChallengeSender","preciseIdentifier":"c:objc(pl)ONGCustomAuthFinishAuthenticationChallengeSender"}],"abstract":[{"type":"text","text":"Sender awaiting for response to the authenticate with custom authenticator challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallenge\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthfinishauthenticationchallenge\/sender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishAuthenticationChallenge":{"role":"symbol","title":"ONGCustomAuthFinishAuthenticationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with custom authenticator challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthfinishauthenticationchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthFinishAuthenticationChallengeSender":{"role":"symbol","title":"ONGCustomAuthFinishAuthenticationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to authentication with Custom Authenticator."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthFinishAuthenticationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthfinishauthenticationchallengesender"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sender"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<ONGCustomAuthFinishAuthenticationChallengeSender>","preciseIdentifier":"c:Qoobjc(pl)ONGCustomAuthFinishAuthenticationChallengeSender"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sender"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallenge~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallenge~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallenge\/title","value":"ONGCustomAuthFinishAuthenticationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallengeSender\/title","value":"ONGCustomAuthFinishAuthenticationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthFinishAuthenticationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthFinishAuthenticationChallengeSender"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}