{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelAssembly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","preciseIdentifier":"c:objc(cs)ONGModelAssembly","text":"ONGModelAssembly"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongassembly\/modelassembly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongassembly\/modelassembly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAssembly\/modelAssembly","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelAssembly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGModelAssembly","preciseIdentifier":"c:objc(cs)ONGModelAssembly"},{"kind":"text","text":"!"}],"title":"modelAssembly","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGAssembly(py)modelAssembly","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"modelAssembly"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAssembly"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAssembly":{"role":"symbol","title":"ONGAssembly","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAssembly"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAssembly"}],"url":"\/documentation\/oneginisdkios\/ongassembly"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly":{"role":"symbol","title":"ONGModelAssembly","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGModelAssembly"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAssembly/modelAssembly":{"role":"symbol","title":"modelAssembly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modelAssembly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGModelAssembly","preciseIdentifier":"c:objc(cs)ONGModelAssembly"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAssembly\/modelAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modelAssembly"}],"url":"\/documentation\/oneginisdkios\/ongassembly\/modelassembly"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modelAssembly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modelAssembly"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","preciseIdentifier":"c:objc(cs)ONGModelAssembly","text":"ONGModelAssembly"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modelAssembly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAssembly\/title","value":"ONGAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAssembly\/fragments","value":[{"kind":"identifier","text":"ONGAssembly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/title","value":"ONGModelAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/fragments","value":[{"kind":"identifier","text":"ONGModelAssembly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAssembly~1modelAssembly\/title","value":"modelAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAssembly~1modelAssembly\/fragments","value":[{"kind":"identifier","text":"modelAssembly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}