{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceerror\/invalidheaders"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceerror\/invalidheaders"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceError\/invalidHeaders","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"provided request headers are not valid"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"title":"ONGFetchResourceError.invalidHeaders","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchResourceError@ONGFetchResourceErrorInvalidHeaders","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceErrorInvalidHeaders"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceError":{"role":"symbol","title":"ONGFetchResourceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceError"}],"abstract":[{"type":"text","text":"Error codes in ONGFetchResourceErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceError"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceError/invalidHeaders":{"role":"symbol","title":"ONGFetchResourceError.invalidHeaders","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidHeaders"}],"abstract":[{"type":"text","text":"provided request headers are not valid"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceError\/invalidHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceErrorInvalidHeaders"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceerror\/invalidheaders"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchResourceErrorInvalidHeaders"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceErrorInvalidHeaders"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchResourceErrorInvalidHeaders"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceError\/title","value":"ONGFetchResourceError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceError\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceError~1invalidHeaders\/title","value":"ONGFetchResourceErrorInvalidHeaders"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceError~1invalidHeaders\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceErrorInvalidHeaders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}