{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel","text":"ONGClientIdModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/clientidmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/clientidmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/clientIdModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"?"}],"title":"clientIdModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)SubmitSignatureNetworkService(py)clientIdModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientIdModel":{"role":"symbol","title":"ONGClientIdModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientIdModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientIdModel"}],"url":"\/documentation\/oneginisdkios\/ongclientidmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService":{"role":"symbol","title":"SubmitSignatureNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/clientIdModel":{"role":"symbol","title":"clientIdModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/clientIdModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/clientidmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clientIdModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientIdModel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel","text":"ONGClientIdModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"clientIdModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientIdModel\/title","value":"ONGClientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientIdModel\/fragments","value":[{"kind":"identifier","text":"ONGClientIdModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1clientIdModel\/title","value":"clientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1clientIdModel\/fragments","value":[{"kind":"identifier","text":"clientIdModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}