{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationCryptor","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationCryptor","text":"ONGMobileAuthenticationCryptor"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthenticationcryptor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthenticationcryptor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthenticationCryptor","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationCryptor","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationCryptor"},{"kind":"text","text":"?"}],"title":"mobileAuthenticationCryptor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)SubmitSignatureNetworkService(py)mobileAuthenticationCryptor","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/mobileAuthenticationCryptor":{"role":"symbol","title":"mobileAuthenticationCryptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationCryptor","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationCryptor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthenticationCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthenticationcryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationCryptor":{"role":"symbol","title":"ONGMobileAuthenticationCryptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationCryptor"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationCryptor"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationcryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService":{"role":"symbol","title":"SubmitSignatureNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mobileAuthenticationCryptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationCryptor","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationCryptor","text":"ONGMobileAuthenticationCryptor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mobileAuthenticationCryptor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthenticationCryptor\/title","value":"mobileAuthenticationCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthenticationCryptor\/fragments","value":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationCryptor\/title","value":"ONGMobileAuthenticationCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationCryptor\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationCryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}