{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel","preciseIdentifier":"c:objc(cs)ONGMobileAuthModel","text":"ONGMobileAuthModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthModel","preciseIdentifier":"c:objc(cs)ONGMobileAuthModel"},{"kind":"text","text":"?"}],"title":"mobileAuthModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)SubmitSignatureNetworkService(py)mobileAuthModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"mobileAuthModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel":{"role":"symbol","title":"ONGMobileAuthModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthModel"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService":{"role":"symbol","title":"SubmitSignatureNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/mobileAuthModel":{"role":"symbol","title":"mobileAuthModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthModel","preciseIdentifier":"c:objc(cs)ONGMobileAuthModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mobileAuthModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mobileAuthModel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel","preciseIdentifier":"c:objc(cs)ONGMobileAuthModel","text":"ONGMobileAuthModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mobileAuthModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel\/title","value":"ONGMobileAuthModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthModel\/title","value":"mobileAuthModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthModel\/fragments","value":[{"kind":"identifier","text":"mobileAuthModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}