{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rsaCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRSACryptor","preciseIdentifier":"c:objc(cs)ONGRSACryptor","text":"ONGRSACryptor"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/rsacryptor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/rsacryptor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/rsaCryptor","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rsaCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRSACryptor","preciseIdentifier":"c:objc(cs)ONGRSACryptor"},{"kind":"text","text":"?"}],"title":"rsaCryptor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)SubmitSignatureNetworkService(py)rsaCryptor","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"rsaCryptor"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService":{"role":"symbol","title":"SubmitSignatureNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRSACryptor":{"role":"symbol","title":"ONGRSACryptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRSACryptor"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRSACryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRSACryptor"}],"url":"\/documentation\/oneginisdkios\/ongrsacryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/rsaCryptor":{"role":"symbol","title":"rsaCryptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rsaCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRSACryptor","preciseIdentifier":"c:objc(cs)ONGRSACryptor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/rsaCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rsaCryptor"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/rsacryptor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rsaCryptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rsaCryptor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRSACryptor","preciseIdentifier":"c:objc(cs)ONGRSACryptor","text":"ONGRSACryptor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rsaCryptor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRSACryptor\/title","value":"ONGRSACryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRSACryptor\/fragments","value":[{"kind":"identifier","text":"ONGRSACryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1rsaCryptor\/title","value":"rsaCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1rsaCryptor\/fragments","value":[{"kind":"identifier","text":"rsaCryptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}