{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod","text":"ONGMobileAuthenticationMethod"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenticationtype\/method"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenticationtype\/method"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationType\/method","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod"}],"title":"method","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGMobileAuthenticationType(py)method","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"method"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationType"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationType/method":{"role":"symbol","title":"method","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationType\/method","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"method"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationtype\/method"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod":{"role":"symbol","title":"ONGMobileAuthenticationMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationType":{"role":"symbol","title":"ONGMobileAuthenticationType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationType"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationType"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"method"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"method"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod","text":"ONGMobileAuthenticationMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"method"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationType~1method\/title","value":"method"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationType~1method\/fragments","value":[{"kind":"identifier","text":"method"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/title","value":"ONGMobileAuthenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationType\/title","value":"ONGMobileAuthenticationType"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationType\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}