{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender","preciseIdentifier":"c:objc(pl)ONGBrowserRegistrationChallengeSender","text":"ONGBrowserRegistrationChallengeSender"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongbrowserregistrationchallenge\/sender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongbrowserregistrationchallenge\/sender"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallenge\/sender","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sender awaiting for response to the browser registration challenge."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBrowserRegistrationChallengeSender","preciseIdentifier":"c:objc(pl)ONGBrowserRegistrationChallengeSender"}],"title":"sender","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGBrowserRegistrationChallenge(py)sender","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"sender"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallenge"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallenge/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBrowserRegistrationChallengeSender","preciseIdentifier":"c:objc(pl)ONGBrowserRegistrationChallengeSender"}],"abstract":[{"type":"text","text":"Sender awaiting for response to the browser registration challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallenge\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallenge\/sender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallenge":{"role":"symbol","title":"ONGBrowserRegistrationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallenge"}],"abstract":[{"type":"text","text":"Represents browser registration challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGBrowserRegistrationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallengeSender":{"role":"symbol","title":"ONGBrowserRegistrationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to browser registration challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sender"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<ONGBrowserRegistrationChallengeSender>","preciseIdentifier":"c:Qoobjc(pl)ONGBrowserRegistrationChallengeSender"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sender"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallenge~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallenge~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallenge\/title","value":"ONGBrowserRegistrationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGBrowserRegistrationChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender\/title","value":"ONGBrowserRegistrationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}