{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol\/authorizationController(with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}],"title":"AppleIdAuthorizationControllerFactoryProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)AppleIdAuthorizationControllerFactoryProtocol","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactoryProtocol/authorizationController(with:)":{"navigatorTitle":[{"kind":"identifier","text":"authorizationControllerWithDelegate:"}],"role":"symbol","title":"authorizationController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol\/authorizationController(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol\/authorizationcontroller(with:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactory":{"role":"symbol","title":"AppleIdAuthorizationControllerFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}],"url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactory"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactoryProtocol":{"role":"symbol","title":"AppleIdAuthorizationControllerFactoryProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}],"url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactoryprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AppleIdAuthorizationControllerFactoryProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactoryProtocol\/authorizationController(with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol~1authorizationController(with:)\/title","value":"authorizationControllerWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol~1authorizationController(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory\/title","value":"AppleIdAuthorizationControllerFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory\/fragments","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol\/title","value":"AppleIdAuthorizationControllerFactoryProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactoryProtocol\/fragments","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactoryProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}