{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/clientregistrationnetworkservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/clientregistrationnetworkservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebKeySetService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebTokenService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestClientChallenge(with:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"title":"ClientRegistrationNetworkService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OneginiSDKiOS@objc(cs)ClientRegistrationNetworkService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/jsonWebKeySetService":{"role":"symbol","title":"jsonWebKeySetService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebKeySetService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebKeySetServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebKeySetServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebKeySetService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jsonWebKeySetService"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/jsonwebkeysetservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/requestClientChallenge(with:completion:)":{"role":"symbol","title":"requestClientChallenge(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestClientChallenge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGClientChallengeResponse","preciseIdentifier":"c:objc(cs)ONGClientChallengeResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestClientChallenge(with:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestClientChallengeWith:completion:"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/requestclientchallenge(with:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)":{"role":"symbol","title":"requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestRegistrationResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"publicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challengeSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestRegistrationResponseWith:publicKey:privateKey:challengeSignature:completion:"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/requestregistrationresponse(with:publickey:privatekey:challengesignature:completion:)"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService":{"role":"symbol","title":"ClientRegistrationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/oAuthSessionModel":{"role":"symbol","title":"oAuthSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/oAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/oauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/jsonWebTokenService":{"role":"symbol","title":"jsonWebTokenService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonWebTokenService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONWebTokenServiceProtocol","preciseIdentifier":"c:objc(pl)JSONWebTokenServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebTokenService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"jsonWebTokenService"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/jsonwebtokenservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/init"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ClientRegistrationNetworkService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebKeySetService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/jsonWebTokenService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/init","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestClientChallenge(with:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRegistrationNetworkService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1jsonWebKeySetService\/title","value":"jsonWebKeySetService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1jsonWebKeySetService\/fragments","value":[{"kind":"identifier","text":"jsonWebKeySetService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestClientChallenge(with:completion:)\/title","value":"requestClientChallengeWith:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestClientChallenge(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestClientChallengeWith:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)\/title","value":"requestRegistrationResponseWith:publicKey:privateKey:challengeSignature:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestRegistrationResponse(with:publicKey:privateKey:challengeSignature:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestRegistrationResponseWith:publicKey:privateKey:challengeSignature:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService\/title","value":"ClientRegistrationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService\/fragments","value":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1oAuthSessionModel\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1oAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1jsonWebTokenService\/title","value":"jsonWebTokenService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1jsonWebTokenService\/fragments","value":[{"kind":"identifier","text":"jsonWebTokenService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}