{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchDataNetworkService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/fetchdatanetworkservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/fetchdatanetworkservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchDataNetworkService"}],"title":"FetchDataNetworkService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OneginiSDKiOS@objc(cs)FetchDataNetworkService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"FetchDataNetworkService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService":{"role":"symbol","title":"FetchDataNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchDataNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FetchDataNetworkService"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice\/init"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService/fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)":{"role":"symbol","title":"fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchMobileAuthPayload"},{"kind":"text","text":"("},{"kind":"externalParam","text":"transactionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchMobileAuthPayloadWithTransactionId:clientId:profileId:completion:"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice\/fetchmobileauthpayload(transactionid:clientid:profileid:completion:)"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService/oAuthSessionModel":{"role":"symbol","title":"oAuthSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/oAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice\/oauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FetchDataNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/fetchdatanetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FetchDataNetworkService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FetchDataNetworkService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FetchDataNetworkService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FetchDataNetworkService\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchDataNetworkService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService\/title","value":"FetchDataNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService\/fragments","value":[{"kind":"identifier","text":"FetchDataNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)\/title","value":"fetchMobileAuthPayloadWithTransactionId:clientId:profileId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1fetchMobileAuthPayload(transactionId:clientId:profileId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchMobileAuthPayloadWithTransactionId:clientId:profileId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1oAuthSessionModel\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1oAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FetchDataNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}