{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"FILENAME_PRIMER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/filename_primer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/filename_primer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FILENAME_PRIMER","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"FILENAME_PRIMER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"title":"FILENAME_PRIMER","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:ONGAbuseDetection.h@2774@macro@FILENAME_PRIMER","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"FILENAME_PRIMER"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/FILENAME_PRIMER":{"role":"symbol","title":"FILENAME_PRIMER","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"FILENAME_PRIMER"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/FILENAME_PRIMER","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FILENAME_PRIMER"}],"url":"\/documentation\/oneginisdkios\/filename_primer"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Macro"},{"op":"replace","path":"\/metadata\/title","value":"FILENAME_PRIMER"},{"op":"replace","path":"\/metadata\/symbolKind","value":"macro"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"#define"},{"kind":"text","text":" "},{"kind":"identifier","text":"FILENAME_PRIMER"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1FILENAME_PRIMER\/title","value":"FILENAME_PRIMER"}],"traits":[{"interfaceLanguage":"occ"}]}]}