{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenServiceProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/jsonwebtokenserviceprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/jsonwebtokenserviceprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol\/generateJWT(withPayload:privateKey:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}],"title":"JSONWebTokenServiceProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)JSONWebTokenServiceProtocol","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenServiceProtocol/generateJWT(withPayload:privateKey:)":{"navigatorTitle":[{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}],"role":"symbol","title":"generateJWT(withPayload:privateKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWT"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol\/generateJWT(withPayload:privateKey:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/jsonwebtokenserviceprotocol\/generatejwt(withpayload:privatekey:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenServiceProtocol":{"role":"symbol","title":"JSONWebTokenServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/jsonwebtokenserviceprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenService":{"role":"symbol","title":"JSONWebTokenService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebTokenService"}],"url":"\/documentation\/oneginisdkios\/jsonwebtokenservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"JSONWebTokenServiceProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenServiceProtocol\/generateJWT(withPayload:privateKey:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenServiceProtocol"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol~1generateJWT(withPayload:privateKey:)\/title","value":"generateJWTWithPayload:privateKey:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol~1generateJWT(withPayload:privateKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol\/title","value":"JSONWebTokenServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenServiceProtocol\/fragments","value":[{"kind":"identifier","text":"JSONWebTokenServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService\/title","value":"JSONWebTokenService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService\/fragments","value":[{"kind":"identifier","text":"JSONWebTokenService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}