{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticatortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticatortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/PIN","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/custom","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/touchID"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/biometric"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorType"}],"title":"ONGAuthenticatorType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGAuthenticatorType","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorType"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType":{"role":"symbol","title":"ONGAuthenticatorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorType"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorType"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatortype"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/touchID":{"role":"symbol","title":"ONGAuthenticatorType.touchID","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchID"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/touchID","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorTouchID"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/touchid"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/biometric":{"role":"symbol","title":"biometric","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometric"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorType","preciseIdentifier":"c:@E@ONGAuthenticatorType"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/biometric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorBiometric"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/biometric"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/custom":{"role":"symbol","title":"ONGAuthenticatorType.custom","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/custom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorCustom"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/custom"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorType/PIN":{"role":"symbol","title":"ONGAuthenticatorType.PIN","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"PIN"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/PIN","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorPIN"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatortype\/pin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticatorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGAuthenticatorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/PIN","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/biometric","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/custom","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorType\/touchID"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType\/title","value":"ONGAuthenticatorType"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1touchID\/title","value":"ONGAuthenticatorTouchID"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1touchID\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorTouchID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1biometric\/title","value":"ONGAuthenticatorBiometric"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1biometric\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorBiometric"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1custom\/title","value":"ONGAuthenticatorCustom"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1custom\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorCustom"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1PIN\/title","value":"ONGAuthenticatorPIN"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorType~1PIN\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorPIN"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}