{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete authentication."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationDelegate"}],"title":"ONGAuthenticationDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGAuthenticationDelegate","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didAuthenticateUser:authenticator:info:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didFailToAuthenticateUser:authenticator:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-3audo","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-4pwc8","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-883u1","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didStartAuthenticationForUser:authenticator:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didReceive:)-4pwc8":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCustomAuthFinishAuthenticationChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomAuthFinishAuthenticationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthFinishAuthenticationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action requires Custom Authenticator data to continue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-4pwc8","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didreceive:)-4pwc8"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didFailToAuthenticateUser:authenticator:error:)":{"role":"symbol","title":"userClient(_:didFailToAuthenticateUser:authenticator:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToAuthenticateUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action failed with error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didFailToAuthenticateUser:authenticator:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didFailToAuthenticateUser:authenticator:error:"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didfailtoauthenticateuser:authenticator:error:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didAuthenticateUser:authenticator:info:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didAuthenticateUser:authenticator:info:"}],"role":"symbol","title":"userClient(_:didAuthenticateUser:authenticator:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didAuthenticateUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method called when authentication action is completed with success."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didAuthenticateUser:authenticator:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didauthenticateuser:authenticator:info:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didStartAuthenticationForUser:authenticator:)":{"role":"symbol","title":"userClient(_:didStartAuthenticationForUser:authenticator:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartAuthenticationForUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action is started."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didStartAuthenticationForUser:authenticator:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didStartAuthenticationForUser:authenticator:"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didstartauthenticationforuser:authenticator:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate":{"role":"symbol","title":"ONGAuthenticationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete authentication."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didReceive:)-3audo":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBiometricChallenge","preciseIdentifier":"c:objc(cs)ONGBiometricChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action requires TouchID or FaceID to continue. Its called before asking user for fingerprint or face."},{"type":"text","text":" "},{"type":"text","text":"If its not implemented SDK will continue automatically."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-3audo","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didreceive:)-3audo"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationDelegate/userClient(_:didReceive:)-883u1":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceivePinChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when authentication action requires PIN code to continue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-883u1","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongauthenticationdelegate\/userclient(_:didreceive:)-883u1"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticationDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGAuthenticationDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didAuthenticateUser:authenticator:info:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didFailToAuthenticateUser:authenticator:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-3audo","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-4pwc8","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didReceive:)-883u1","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationDelegate\/userClient(_:didStartAuthenticationForUser:authenticator:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-4pwc8\/title","value":"userClient:didReceiveCustomAuthFinishAuthenticationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-4pwc8\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCustomAuthFinishAuthenticationChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didFailToAuthenticateUser:authenticator:error:)\/title","value":"userClient:didFailToAuthenticateUser:authenticator:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didFailToAuthenticateUser:authenticator:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didFailToAuthenticateUser:authenticator:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didAuthenticateUser:authenticator:info:)\/title","value":"userClient:didAuthenticateUser:authenticator:info:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didAuthenticateUser:authenticator:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didAuthenticateUser:authenticator:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didStartAuthenticationForUser:authenticator:)\/title","value":"userClient:didStartAuthenticationForUser:authenticator:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didStartAuthenticationForUser:authenticator:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didStartAuthenticationForUser:authenticator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate\/title","value":"ONGAuthenticationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-3audo\/title","value":"userClient:didReceiveBiometricChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-3audo\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveBiometricChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-883u1\/title","value":"userClient:didReceivePinChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationDelegate~1userClient(_:didReceive:)-883u1\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceivePinChallenge:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}