{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to browser registration challenge."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}],"title":"ONGBrowserRegistrationChallengeSender","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGBrowserRegistrationChallengeSender","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/cancel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/respond(with:challenge:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallengeSender":{"role":"symbol","title":"ONGBrowserRegistrationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to browser registration challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallengeSender/cancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:"}],"role":"symbol","title":"cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGBrowserRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGBrowserRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to cancel challenge"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/cancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender\/cancel(_:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBrowserRegistrationChallengeSender/respond(with:challenge:)":{"navigatorTitle":[{"kind":"identifier","text":"respondWithURL:challenge:"}],"role":"symbol","title":"respond(with:challenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBrowserRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGBrowserRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method providing the URL to the SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/respond(with:challenge:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongbrowserregistrationchallengesender\/respond(with:challenge:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGBrowserRegistrationChallengeSender"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/cancel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBrowserRegistrationChallengeSender\/respond(with:challenge:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender\/title","value":"ONGBrowserRegistrationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGBrowserRegistrationChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender~1cancel(_:)\/title","value":"cancelChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender~1respond(with:challenge:)\/title","value":"respondWithURL:challenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBrowserRegistrationChallengeSender~1respond(with:challenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"respondWithURL:challenge:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}