{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientValidationResponse"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientvalidationresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientvalidationresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientConfig","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientId","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/profiles"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientValidationResponse"}],"title":"ONGClientValidationResponse","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGClientValidationResponse","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGClientValidationResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/customAuthenticators":{"role":"symbol","title":"customAuthenticators","fragments":[{"kind":"identifier","text":"customAuthenticators"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/customAuthenticators","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/customauthenticators"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/identityProviders":{"role":"symbol","title":"identityProviders","fragments":[{"kind":"identifier","text":"identityProviders"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/identityProviders","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/identityproviders"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/enabledCustomAuthenticators":{"role":"symbol","title":"enabledCustomAuthenticators","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enabledCustomAuthenticators"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/enabledCustomAuthenticators","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enabledCustomAuthenticators"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/enabledcustomauthenticators"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/clientConfig":{"role":"symbol","title":"clientConfig","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientConfig","preciseIdentifier":"c:objc(cs)ONGClientConfig"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientConfig"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/clientconfig"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse":{"role":"symbol","title":"ONGClientValidationResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientValidationResponse"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientValidationResponse"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/clientId":{"role":"symbol","title":"clientId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientId"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/clientid"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/profiles":{"role":"symbol","title":"profiles","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profiles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/profiles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"profiles"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/profiles"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientValidationResponse/customAuthenticatorsForProfile:":{"role":"symbol","title":"customAuthenticatorsForProfile:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customAuthenticatorsForProfile:"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/customAuthenticatorsForProfile:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customAuthenticatorsForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongclientvalidationresponse\/customauthenticatorsforprofile:"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGClientValidationResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGClientValidationResponse"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGClientValidationResponse"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientConfig","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/clientId","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/customAuthenticators","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/identityProviders","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/profiles"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/customAuthenticatorsForProfile:","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientValidationResponse\/enabledCustomAuthenticators"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientValidationResponse"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1clientConfig\/title","value":"clientConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1clientConfig\/fragments","value":[{"kind":"identifier","text":"clientConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse\/title","value":"ONGClientValidationResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse\/fragments","value":[{"kind":"identifier","text":"ONGClientValidationResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1clientId\/title","value":"clientId"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1clientId\/fragments","value":[{"kind":"identifier","text":"clientId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1profiles\/title","value":"profiles"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientValidationResponse~1profiles\/fragments","value":[{"kind":"identifier","text":"profiles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}