{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongchangepindelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongchangepindelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete change PIN action."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinDelegate"}],"title":"ONGChangePinDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGChangePinDelegate","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGChangePinDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didChangePinForUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didFailToChangePinForUser:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-6mszn","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-864ae","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didStartPinChangeForUser:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate/userClient(_:didReceive:)-864ae":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCreatePinChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when change PIN action requires new PIN code to continue."},{"type":"text","text":" "},{"type":"text","text":"New PIN must be compliant with PIN policy defined by the token server."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-864ae","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepindelegate\/userclient(_:didreceive:)-864ae"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate/userClient(_:didFailToChangePinForUser:error:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didFailToChangePinForUser:error:"}],"role":"symbol","title":"userClient(_:didFailToChangePinForUser:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToChangePinForUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when change PIN action failed with an error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didFailToChangePinForUser:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepindelegate\/userclient(_:didfailtochangepinforuser:error:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate/userClient(_:didReceive:)-6mszn":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceivePinChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when change PIN action requires authentication with PIN code to continue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-6mszn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepindelegate\/userclient(_:didreceive:)-6mszn"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate":{"role":"symbol","title":"ONGChangePinDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete change PIN action."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGChangePinDelegate"}],"url":"\/documentation\/oneginisdkios\/ongchangepindelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate/userClient(_:didChangePinForUser:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didChangePinForUser:"}],"role":"symbol","title":"userClient(_:didChangePinForUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangePinForUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when change PIN action is completed with success."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didChangePinForUser:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepindelegate\/userclient(_:didchangepinforuser:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinDelegate/userClient(_:didStartPinChangeForUser:)":{"role":"symbol","title":"userClient(_:didStartPinChangeForUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartPinChangeForUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when change PIN action is started."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didStartPinChangeForUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didStartPinChangeForUser:"}],"url":"\/documentation\/oneginisdkios\/ongchangepindelegate\/userclient(_:didstartpinchangeforuser:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGChangePinDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGChangePinDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGChangePinDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didChangePinForUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didFailToChangePinForUser:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-6mszn","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didReceive:)-864ae","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinDelegate\/userClient(_:didStartPinChangeForUser:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didReceive:)-864ae\/title","value":"userClient:didReceiveCreatePinChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didReceive:)-864ae\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCreatePinChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didFailToChangePinForUser:error:)\/title","value":"userClient:didFailToChangePinForUser:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didFailToChangePinForUser:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didFailToChangePinForUser:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didReceive:)-6mszn\/title","value":"userClient:didReceivePinChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didReceive:)-6mszn\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceivePinChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate\/title","value":"ONGChangePinDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate\/fragments","value":[{"kind":"identifier","text":"ONGChangePinDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didChangePinForUser:)\/title","value":"userClient:didChangePinForUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didChangePinForUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didChangePinForUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didStartPinChangeForUser:)\/title","value":"userClient:didStartPinChangeForUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinDelegate~1userClient(_:didStartPinChangeForUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didStartPinChangeForUser:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}