{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClient"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclient"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Main entry point for the Onegini SDK. This class owns SDK’s configuration and such clients as "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":". In order to use any feature of the OneginiSDK "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":" needs to be called first."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClient"}],"title":"ONGClient","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGClient","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGClient"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/configModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/deviceClient","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/userClient"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/reset(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/start(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/sharedInstance()"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/userClient":{"role":"symbol","title":"userClient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"}],"abstract":[{"type":"text","text":"Instance of "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" used for user-related features access. Once SDK has been configured, "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"text","text":"can be access either by calling this property or by "},{"type":"codeVoice","code":"-[ONGUserClient sharedInstance]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/userClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient"}],"url":"\/documentation\/oneginisdkios\/ongclient\/userclient"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient":{"role":"symbol","title":"ONGClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClient"}],"abstract":[{"type":"text","text":"Main entry point for the Onegini SDK. This class owns SDK’s configuration and such clients as "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":". In order to use any feature of the OneginiSDK "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":" needs to be called first."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClient"}],"url":"\/documentation\/oneginisdkios\/ongclient"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/deviceClient":{"role":"symbol","title":"deviceClient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGDeviceClient","preciseIdentifier":"c:objc(cs)ONGDeviceClient"}],"abstract":[{"type":"text","text":"Instance of "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":" used for device and network-related features. Once SDK has been configured, "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":" "},{"type":"text","text":"can be access either by calling this property or by "},{"type":"codeVoice","code":"-[ONGDeviceClient sharedInstance]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/deviceClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deviceClient"}],"url":"\/documentation\/oneginisdkios\/ongclient\/deviceclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/start(_:)":{"role":"symbol","title":"start(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Is a mandatory first call on ONGClient which is returned by "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/start(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start:"}],"url":"\/documentation\/oneginisdkios\/ongclient\/start(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/sharedInstance()":{"role":"symbol","title":"sharedInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Access to the initialized and configured instance of the "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":". Before calling this method You have to initialize"},{"type":"text","text":" "},{"type":"text","text":"SDK by calling "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/sharedInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/oneginisdkios\/ongclient\/sharedinstance()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/configModel":{"role":"symbol","title":"configModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGConfigModel","preciseIdentifier":"c:objc(cs)ONGConfigModel"}],"abstract":[{"type":"text","text":"The ConfigModel used to configure OneginiSDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/configModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configModel"}],"url":"\/documentation\/oneginisdkios\/ongclient\/configmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClient/reset(_:)":{"role":"symbol","title":"reset(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Reset to the state the SDK had just after completing the start method. Errors passed to the block will be within the ONGGenericErrorDomain."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/reset(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reset:"}],"url":"\/documentation\/oneginisdkios\/ongclient\/reset(_:)"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGClient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGClient"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGClient"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/configModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/deviceClient","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/userClient"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/reset(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/start(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClient\/sharedInstance()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClient"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1userClient\/title","value":"userClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1userClient\/fragments","value":[{"kind":"identifier","text":"userClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient\/title","value":"ONGClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient\/fragments","value":[{"kind":"identifier","text":"ONGClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1deviceClient\/title","value":"deviceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1deviceClient\/fragments","value":[{"kind":"identifier","text":"deviceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1start(_:)\/title","value":"start:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1start(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1sharedInstance()\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1sharedInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1configModel\/title","value":"configModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1configModel\/fragments","value":[{"kind":"identifier","text":"configModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1reset(_:)\/title","value":"reset:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClient~1reset(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reset:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}