{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents deregistration challenge of custom authenticator. It provides all information about the challenge and a sender awaiting for a response."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"title":"ONGCustomAuthDeregistrationChallenge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGCustomAuthDeregistrationChallenge","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/authenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/userProfile"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallenge/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomAuthDeregistrationChallengeSender","preciseIdentifier":"c:objc(pl)ONGCustomAuthDeregistrationChallengeSender"}],"abstract":[{"type":"text","text":"Sender awaiting response to the deregistration challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge\/sender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallenge":{"role":"symbol","title":"ONGCustomAuthDeregistrationChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"abstract":[{"type":"text","text":"Represents deregistration challenge of custom authenticator. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallenge/userProfile":{"role":"symbol","title":"userProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"}],"abstract":[{"type":"text","text":"User profile for which deregistration challenge was sent."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/userProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userProfile"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge\/userprofile"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallenge/authenticator":{"role":"symbol","title":"authenticator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"}],"abstract":[{"type":"text","text":"Authenticator to be deregistered."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/authenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticator"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallenge\/authenticator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGCustomAuthDeregistrationChallenge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/authenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallenge\/userProfile"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge\/title","value":"ONGCustomAuthDeregistrationChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1userProfile\/title","value":"userProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1userProfile\/fragments","value":[{"kind":"identifier","text":"userProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1authenticator\/title","value":"authenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallenge~1authenticator\/fragments","value":[{"kind":"identifier","text":"authenticator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}