{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallenge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallenge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallenge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents create PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallenge"}],"title":"ONGCreatePinChallenge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGCreatePinChallenge","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallenge"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/error","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/pinLength","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/userProfile"]}],"references":{"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallengeSender","preciseIdentifier":"c:objc(pl)ONGCreatePinChallengeSender"}],"abstract":[{"type":"text","text":"Sender awaiting for response to the create PIN challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge\/sender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error describing cause of failure of previous challenge response."},{"type":"text","text":" "},{"type":"text","text":"Possible error domains: ONGPinValidationErrorDomain, ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"error"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge\/error"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge/userProfile":{"role":"symbol","title":"userProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"}],"abstract":[{"type":"text","text":"User profile for which create PIN challenge was sent."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/userProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userProfile"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge\/userprofile"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge":{"role":"symbol","title":"ONGCreatePinChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallenge"}],"abstract":[{"type":"text","text":"Represents create PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge/pinLength":{"role":"symbol","title":"pinLength","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinLength"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Required length for a new PIN."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/pinLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pinLength"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge\/pinlength"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGCreatePinChallenge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallenge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGCreatePinChallenge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/error","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/pinLength","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge\/userProfile"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallenge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1error\/title","value":"error"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1error\/fragments","value":[{"kind":"identifier","text":"error"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1userProfile\/title","value":"userProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1userProfile\/fragments","value":[{"kind":"identifier","text":"userProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge\/title","value":"ONGCreatePinChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1pinLength\/title","value":"pinLength"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge~1pinLength\/fragments","value":[{"kind":"identifier","text":"pinLength"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}