{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallengeSender"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallengesender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallengesender"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to create PIN challenge."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallengeSender"}],"title":"ONGCreatePinChallengeSender","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGCreatePinChallengeSender","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/cancel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/respond(withCreatedPin:challenge:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallengeSender/cancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:"}],"role":"symbol","title":"cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to cancel challenge"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/cancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcreatepinchallengesender\/cancel(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallengeSender":{"role":"symbol","title":"ONGCreatePinChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to create PIN challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallengesender"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallengeSender/respond(withCreatedPin:challenge:)":{"navigatorTitle":[{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}],"role":"symbol","title":"respond(withCreatedPin:challenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCreatedPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method providing the PIN to the SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/respond(withCreatedPin:challenge:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcreatepinchallengesender\/respond(withcreatedpin:challenge:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGCreatePinChallengeSender"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/cancel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/respond(withCreatedPin:challenge:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallengeSender"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1cancel(_:)\/title","value":"cancelChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender\/title","value":"ONGCreatePinChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1respond(withCreatedPin:challenge:)\/title","value":"respondWithCreatedPin:challenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1respond(withCreatedPin:challenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}