{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongchangepinerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongchangepinerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes in ONGChangePinErrorDomain"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinError"}],"title":"ONGChangePinError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGChangePinError","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGChangePinError"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/pinChangeErrorUserNotAuthenticated"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinError/pinChangeErrorUserNotAuthenticated":{"role":"symbol","title":"ONGChangePinError.pinChangeErrorUserNotAuthenticated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinChangeErrorUserNotAuthenticated"}],"abstract":[{"type":"text","text":"No user is currently authenticated, possibly due to the fact that the access token has expired. A user must be authenticated in order to change PIN."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/pinChangeErrorUserNotAuthenticated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinChangeErrorUserNotAuthenticated"}],"url":"\/documentation\/oneginisdkios\/ongchangepinerror\/pinchangeerrorusernotauthenticated"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinError":{"role":"symbol","title":"ONGChangePinError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinError"}],"abstract":[{"type":"text","text":"Error codes in ONGChangePinErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGChangePinError"}],"url":"\/documentation\/oneginisdkios\/ongchangepinerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorCode":{"role":"symbol","title":"ONGErrorCode","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongerrorcode"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepinerror\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepinerror\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGChangePinError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongchangepinerror\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGChangePinError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGChangePinError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGChangePinError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGChangePinError\/pinChangeErrorUserNotAuthenticated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGChangePinError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode","text":"ONGErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinError~1pinChangeErrorUserNotAuthenticated\/title","value":"ONGPinChangeErrorUserNotAuthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinError~1pinChangeErrorUserNotAuthenticated\/fragments","value":[{"kind":"identifier","text":"ONGPinChangeErrorUserNotAuthenticated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinError\/title","value":"ONGChangePinError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGChangePinError\/fragments","value":[{"kind":"identifier","text":"ONGChangePinError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/title","value":"ONGErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}