{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to deregistration of custom authenticator."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}],"title":"ONGCustomAuthDeregistrationChallengeSender","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGCustomAuthDeregistrationChallengeSender","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/cancel(_:withUnderlyingError:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/continue(with:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallengeSender/continue(with:)":{"navigatorTitle":[{"kind":"identifier","text":"continueWithChallenge:"}],"role":"symbol","title":"continue(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`continue`"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to continue deregistration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/continue(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender\/continue(with:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallengeSender":{"role":"symbol","title":"ONGCustomAuthDeregistrationChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to deregistration of custom authenticator."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomAuthDeregistrationChallengeSender/cancel(_:withUnderlyingError:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}],"role":"symbol","title":"cancel(_:withUnderlyingError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGCustomAuthDeregistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomAuthDeregistrationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withUnderlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method to cancel deregistration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/cancel(_:withUnderlyingError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcustomauthderegistrationchallengesender\/cancel(_:withunderlyingerror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGCustomAuthDeregistrationChallengeSender"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/cancel(_:withUnderlyingError:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomAuthDeregistrationChallengeSender\/continue(with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1continue(with:)\/title","value":"continueWithChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1continue(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"continueWithChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender\/title","value":"ONGCustomAuthDeregistrationChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCustomAuthDeregistrationChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1cancel(_:withUnderlyingError:)\/title","value":"cancelChallenge:withUnderlyingError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomAuthDeregistrationChallengeSender~1cancel(_:withUnderlyingError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:withUnderlyingError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}