{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SDK setup:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In order to instantiate SDK you have to set at least "},{"type":"codeVoice","code":"configModel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"X509PEMCertificates"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If one or both are not set, "},{"type":"codeVoice","code":"ONGClientBuilder"},{"type":"text","text":" will try to retrieve missing values from "},{"type":"codeVoice","code":"OneginiConfigModel"},{"type":"text","text":" class"},{"type":"text","text":" "},{"type":"text","text":"generated by SDK configurator tool. If it is impossible to locate "},{"type":"codeVoice","code":"OneginiConfigModel"},{"type":"text","text":" - SDK can not be configured"},{"type":"text","text":" "},{"type":"text","text":"correctly and exception is raised."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongclientbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"ONGClientBuilder"},{"type":"text","text":" is responsible for setting up SDK."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"}],"title":"ONGClientBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGClientBuilder","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGClientBuilder"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/build()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/buildAndWait(forProtectedData:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setAdditionalResourceUrls(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setConfigModel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setDeviceConfigCacheDuration(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setHttpRequestTimeout(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setServerPublicKey(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setStoreCookies(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setX509PEMCertificates(_:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setDeviceConfigCacheDuration(_:)":{"role":"symbol","title":"setDeviceConfigCacheDuration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDeviceConfigCacheDuration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"To reduce frequency of client validation calls, device config stays cached for specified period of time."},{"type":"text","text":" "},{"type":"text","text":"Setting cache duration to negative or 0 value will disable caching."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setDeviceConfigCacheDuration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDeviceConfigCacheDuration:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setdeviceconfigcacheduration(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setConfigModel(_:)":{"role":"symbol","title":"setConfigModel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setConfigModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGConfigModel","preciseIdentifier":"c:objc(cs)ONGConfigModel"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Set instance of "},{"type":"codeVoice","code":"ONGConfigModel"},{"type":"text","text":" used for SDK configuration. This value can not be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setConfigModel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setConfigModel:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setconfigmodel(_:)"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/buildAndWait(forProtectedData:)":{"role":"symbol","title":"buildAndWait(forProtectedData:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildAndWait"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProtectedData"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGClient","preciseIdentifier":"c:objc(cs)ONGClient"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Set up SDK, wait for the protected data to be available and return configured instance of "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":" using builder’s values."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/buildAndWait(forProtectedData:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildAndWaitForProtectedData:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/buildandwait(forprotecteddata:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setAdditionalResourceUrls(_:)":{"role":"symbol","title":"setAdditionalResourceUrls(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setAdditionalResourceUrls"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Set  additional (optional) array of resource URLs used for the SDK configuration."},{"type":"text","text":" "},{"type":"text","text":"This has to be set from the code, before calling "},{"type":"codeVoice","code":"build()"},{"type":"text","text":" function."},{"type":"text","text":" "},{"type":"text","text":"Can be used when the certficate used for pinning covers additional URLs."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setAdditionalResourceUrls(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setAdditionalResourceUrls:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setadditionalresourceurls(_:)"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setX509PEMCertificates(_:)":{"role":"symbol","title":"setX509PEMCertificates(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setX509PEMCertificates"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"For verification of the bundled DER encoded CA X509 certificates,"},{"type":"text","text":" "},{"type":"text","text":"the App must provide a list of matching PEM base64 encoded certificates for each bundled DER encoded CA X509 certificate to this client."},{"type":"text","text":" "},{"type":"text","text":"The PEM base64 encoded certificates must be stripped from their armor (remove —BEGIN CERTIFICATE— & —END CERTIFICATE—)"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setX509PEMCertificates(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setX509PEMCertificates:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setx509pemcertificates(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder":{"role":"symbol","title":"ONGClientBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"}],"abstract":[{"type":"codeVoice","code":"ONGClientBuilder"},{"type":"text","text":" is responsible for setting up SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientBuilder"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setServerPublicKey(_:)":{"role":"symbol","title":"setServerPublicKey(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setServerPublicKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"The hexadecimal server public key used to perform a Payload Encryption handshake. Can be nil if Payload Encryption is not used."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setServerPublicKey(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setServerPublicKey:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setserverpublickey(_:)"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setHttpRequestTimeout(_:)":{"role":"symbol","title":"setHttpRequestTimeout(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHttpRequestTimeout"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Configure the HTTP request timeout for all HTTP requests made by the SDK. This goes for both the HTTP calls made by the SDK as for the resource requests"},{"type":"text","text":" "},{"type":"text","text":"that are made using the SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setHttpRequestTimeout(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setHttpRequestTimeout:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/sethttprequesttimeout(_:)"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/setStoreCookies(_:)":{"role":"symbol","title":"setStoreCookies(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setStoreCookies"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flag instructing SDK to store cookies between requests. "},{"type":"codeVoice","code":"YES"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setStoreCookies(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setStoreCookies:"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/setstorecookies(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClient","preciseIdentifier":"c:objc(cs)ONGClient"}],"abstract":[{"type":"text","text":"Set up SDK and return configured instance of "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":" using builder’s values."},{"type":"text","text":" "},{"type":"text","text":"Subsequent calls will not take any effect on the instantiated "},{"type":"codeVoice","code":"ONGClient"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/oneginisdkios\/ongclientbuilder\/build()"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGClientBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGClientBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGClientBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/build()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/buildAndWait(forProtectedData:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setAdditionalResourceUrls(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setConfigModel(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setDeviceConfigCacheDuration(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setHttpRequestTimeout(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setServerPublicKey(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setStoreCookies(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientBuilder\/setX509PEMCertificates(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setDeviceConfigCacheDuration(_:)\/title","value":"setDeviceConfigCacheDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setDeviceConfigCacheDuration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDeviceConfigCacheDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setConfigModel(_:)\/title","value":"setConfigModel:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setConfigModel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setConfigModel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1buildAndWait(forProtectedData:)\/title","value":"buildAndWaitForProtectedData:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1buildAndWait(forProtectedData:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildAndWaitForProtectedData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setAdditionalResourceUrls(_:)\/title","value":"setAdditionalResourceUrls:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setAdditionalResourceUrls(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAdditionalResourceUrls:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setX509PEMCertificates(_:)\/title","value":"setX509PEMCertificates:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setX509PEMCertificates(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setX509PEMCertificates:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/title","value":"ONGClientBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder\/fragments","value":[{"kind":"identifier","text":"ONGClientBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setServerPublicKey(_:)\/title","value":"setServerPublicKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setServerPublicKey(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setServerPublicKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setHttpRequestTimeout(_:)\/title","value":"setHttpRequestTimeout:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setHttpRequestTimeout(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHttpRequestTimeout:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setStoreCookies(_:)\/title","value":"setStoreCookies:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1setStoreCookies(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setStoreCookies:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}