{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeviceClient"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongdeviceclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongdeviceclient"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/authenticateDevice(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/clientId()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchUnauthenticatedResource(_:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/sharedInstance()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeviceClient"}],"title":"ONGDeviceClient","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGDeviceClient","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGDeviceClient"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/clientId()":{"role":"symbol","title":"clientId()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Returns the clientId for the registered device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/clientId()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientIdWithError:"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/clientid()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient":{"role":"symbol","title":"ONGDeviceClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeviceClient"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGDeviceClient"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/sharedInstance()":{"role":"symbol","title":"sharedInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGDeviceClient","preciseIdentifier":"c:objc(cs)ONGDeviceClient"}],"abstract":[{"type":"text","text":"Access to the initialized and configured instance of the "},{"type":"codeVoice","code":"ONGDeviceClient"},{"type":"text","text":". Before calling this method You have to initialize"},{"type":"text","text":" "},{"type":"text","text":"SDK by calling "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/sharedInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/sharedinstance()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/fetchResource(_:completion:)":{"role":"symbol","title":"fetchResource(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Perform an authenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediately (synchronously)."},{"type":"text","text":" "},{"type":"text","text":"The device needs to be authenticated, otherwise SDK will return the "},{"type":"codeVoice","code":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"},{"type":"text","text":" error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchResource(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchResource:completion:"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/fetchresource(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/fetchUnauthenticatedResource(_:completion:)":{"role":"symbol","title":"fetchUnauthenticatedResource(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUnauthenticatedResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Perform an unauthenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediately (synchronously)."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchUnauthenticatedResource(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/fetchunauthenticatedresource(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/authenticateDevice(_:completion:)":{"role":"symbol","title":"authenticateDevice(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticateDevice"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Performs device authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/authenticateDevice(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticateDevice:completion:"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/authenticatedevice(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGDeviceClient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGDeviceClient"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGDeviceClient"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/authenticateDevice(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/clientId()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchUnauthenticatedResource(_:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/sharedInstance()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeviceClient"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1clientId()\/title","value":"clientIdWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1clientId()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientIdWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient\/title","value":"ONGDeviceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient\/fragments","value":[{"kind":"identifier","text":"ONGDeviceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1sharedInstance()\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1sharedInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchResource(_:completion:)\/title","value":"fetchResource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchResource(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchResource:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchUnauthenticatedResource(_:completion:)\/title","value":"fetchUnauthenticatedResource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchUnauthenticatedResource(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1authenticateDevice(_:completion:)\/title","value":"authenticateDevice:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1authenticateDevice(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticateDevice:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}