{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextToString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongerrorcontexttostring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongerrorcontexttostring(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContextToString(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"ONGErrorContextToString(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@ONGErrorContextToString","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextToString"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContextToString(_:)":{"role":"symbol","title":"ONGErrorContextToString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContextToString(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextToString"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontexttostring(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext":{"role":"symbol","title":"ONGErrorContext","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContext"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"ONGErrorContextToString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextToString"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ONGErrorContextToString"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"},{"kind":"text","text":" "},{"kind":"internalParam","text":"context"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContextToString(_:)\/title","value":"ONGErrorContextToString"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContextToString(_:)\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextToString"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/title","value":"ONGErrorContext"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/fragments","value":[{"kind":"identifier","text":"ONGErrorContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}