{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationMethod","preciseIdentifier":"c:@E@ONGAuthenticationMethod","text":"ONGAuthenticationMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongerrorcontextfromauthenticationmethod(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongerrorcontextfromauthenticationmethod(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContextFromAuthenticationMethod(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticationMethod","preciseIdentifier":"c:@E@ONGAuthenticationMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"}],"title":"ONGErrorContextFromAuthenticationMethod(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@ONGErrorContextFromAuthenticationMethod","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext":{"role":"symbol","title":"ONGErrorContext","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContext"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContextFromAuthenticationMethod(_:)":{"role":"symbol","title":"ONGErrorContextFromAuthenticationMethod(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticationMethod","preciseIdentifier":"c:@E@ONGAuthenticationMethod"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContextFromAuthenticationMethod(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontextfromauthenticationmethod(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationMethod":{"role":"symbol","title":"ONGAuthenticationMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationMethod"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationMethod"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationmethod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"ONGErrorContextFromAuthenticationMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationMethod","preciseIdentifier":"c:@E@ONGAuthenticationMethod","text":"ONGAuthenticationMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"method"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/title","value":"ONGErrorContext"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/fragments","value":[{"kind":"identifier","text":"ONGErrorContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContextFromAuthenticationMethod(_:)\/title","value":"ONGErrorContextFromAuthenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContextFromAuthenticationMethod(_:)\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextFromAuthenticationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationMethod\/title","value":"ONGAuthenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationMethod\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationMethod"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}