{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidHeaders","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidMethod","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorUserNotAuthenticatedImplicitly"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"title":"ONGFetchResourceImplicitlyError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGFetchResourceImplicitlyError","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorCode":{"role":"symbol","title":"ONGErrorCode","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongerrorcode"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/implicitResourceErrorInvalidMethod":{"role":"symbol","title":"ONGFetchResourceImplicitlyError.implicitResourceErrorInvalidMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorInvalidMethod"}],"abstract":[{"type":"text","text":"provided request method is not valid, use one of @“GET”, @“POST”, @“DELETE”, @“PUT”"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorinvalidmethod"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/implicitResourceErrorInvalidHeaders":{"role":"symbol","title":"ONGFetchResourceImplicitlyError.implicitResourceErrorInvalidHeaders","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorInvalidHeaders"}],"abstract":[{"type":"text","text":"provided request headers are not valid"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidHeaders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidHeaders"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorinvalidheaders"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/implicitResourceErrorUserNotAuthenticatedImplicitly":{"role":"symbol","title":"ONGFetchResourceImplicitlyError.implicitResourceErrorUserNotAuthenticatedImplicitly","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitResourceErrorUserNotAuthenticatedImplicitly"}],"abstract":[{"type":"text","text":"No user is currently authenticated implicitly, possibly due to the fact that the implicit access token has expired. A user must be authenticated in order to fetch resources."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorUserNotAuthenticatedImplicitly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/implicitresourceerrorusernotauthenticatedimplicitly"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchResourceImplicitlyError":{"role":"symbol","title":"ONGFetchResourceImplicitlyError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}],"url":"\/documentation\/oneginisdkios\/ongfetchresourceimplicitlyerror"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchResourceImplicitlyError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidHeaders","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorInvalidMethod","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchResourceImplicitlyError\/implicitResourceErrorUserNotAuthenticatedImplicitly"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode","text":"ONGErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/title","value":"ONGErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidMethod\/title","value":"ONGFetchImplicitResourceErrorInvalidMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidMethod\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidHeaders\/title","value":"ONGFetchImplicitResourceErrorInvalidHeaders"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorInvalidHeaders\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorInvalidHeaders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorUserNotAuthenticatedImplicitly\/title","value":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError~1implicitResourceErrorUserNotAuthenticatedImplicitly\/fragments","value":[{"kind":"identifier","text":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/title","value":"ONGFetchResourceImplicitlyError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchResourceImplicitlyError\/fragments","value":[{"kind":"identifier","text":"ONGFetchResourceImplicitlyError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}