{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onggenericerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onggenericerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"title":"ONGGenericError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGGenericError","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionAlreadyInProgress","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionCancelled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/appIntegrityFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/configurationInvalid","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/dataStorageNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceDeregistered","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/invalidDateTime","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/networkConnectivityFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedApplication","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/protectedDataStorageNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/requestInvalid","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/serverNotReachable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unknown","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unrecoverableDataState","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/userDeregistered"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorCode":{"role":"symbol","title":"ONGErrorCode","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongerrorcode"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/outdatedApplication":{"role":"symbol","title":"ONGGenericError.outdatedApplication","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outdatedApplication"}],"abstract":[{"type":"text","text":"The Token Server denotes that the current app is no longer valid and can no longer be used. The end-user must update the application. Updating the SDK configuration might also solve the problem."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedApplication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorOutdatedApplication"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/outdatedapplication"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/onggenericerror\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/actionAlreadyInProgress":{"role":"symbol","title":"ONGGenericError.actionAlreadyInProgress","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionAlreadyInProgress"}],"abstract":[{"type":"text","text":"Another action already in progress and can not be performed concurrently."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionAlreadyInProgress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorActionAlreadyInProgress"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/actionalreadyinprogress"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/onggenericerror\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/outdatedOS":{"role":"symbol","title":"ONGGenericError.outdatedOS","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"outdatedOS"}],"abstract":[{"type":"text","text":"The Token Server does not allow this application to run on the current OS version. Instruct the user to update the OS."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedOS","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorOutdatedOS"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/outdatedos"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/actionCancelled":{"role":"symbol","title":"ONGGenericError.actionCancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionCancelled"}],"abstract":[{"type":"text","text":"Requested action was cancelled."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionCancelled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorActionCancelled"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/actioncancelled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/unrecoverableDataState":{"role":"symbol","title":"ONGGenericError.unrecoverableDataState","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unrecoverableDataState"}],"abstract":[{"type":"text","text":"The data storage is corrupted and cannot be recovered or cleared."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unrecoverableDataState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorUnrecoverableDataState"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/unrecoverabledatastate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/onggenericerror\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/unknown":{"role":"symbol","title":"ONGGenericError.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"An unknown error occurred"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorUnknown"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/unknown"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/userDeregistered":{"role":"symbol","title":"ONGGenericError.userDeregistered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDeregistered"}],"abstract":[{"type":"text","text":"The user account is deregistered from the device. The user supplied the wrong PIN for too many times. All local data associated with the user profile has been removed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/userDeregistered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorUserDeregistered"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/userderegistered"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/configurationInvalid":{"role":"symbol","title":"ONGGenericError.configurationInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configurationInvalid"}],"abstract":[{"type":"text","text":"The Token Server configuration is invalid."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/configurationInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/configurationinvalid"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/protectedDataStorageNotAvailable":{"role":"symbol","title":"ONGGenericError.protectedDataStorageNotAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"protectedDataStorageNotAvailable"}],"abstract":[{"type":"text","text":"The protected data storage could not be accessed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/protectedDataStorageNotAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorProtectedDataStorageNotAvailable"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/protecteddatastoragenotavailable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/serverNotReachable":{"role":"symbol","title":"ONGGenericError.serverNotReachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverNotReachable"}],"abstract":[{"type":"text","text":"Check the Onegini SDK configuration for the correct server URL."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/serverNotReachable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorServerNotReachable"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/servernotreachable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/requestInvalid":{"role":"symbol","title":"ONGGenericError.requestInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestInvalid"}],"abstract":[{"type":"text","text":"The request to the Token Server was invalid. Please verify that the Token Server configuration is correct and that no reverse proxy is interfering with the connection."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/requestInvalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorRequestInvalid"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/requestinvalid"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/dataStorageNotAvailable":{"role":"symbol","title":"ONGGenericError.dataStorageNotAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataStorageNotAvailable"}],"abstract":[{"type":"text","text":"The data storage could not be accessed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/dataStorageNotAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorDataStorageNotAvailable"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/datastoragenotavailable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/invalidDateTime":{"role":"symbol","title":"ONGGenericError.invalidDateTime","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateTime"}],"abstract":[{"type":"text","text":"The date or time used by the device is incorrect. Please check Date & Time Settings on the phone and sync them if necessary."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/invalidDateTime","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/invaliddatetime"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/networkConnectivityFailure":{"role":"symbol","title":"ONGGenericError.networkConnectivityFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkConnectivityFailure"}],"abstract":[{"type":"text","text":"Due to a problem with the device internet connection it was not possible to initiate the requested action."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/networkConnectivityFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/networkconnectivityfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError":{"role":"symbol","title":"ONGGenericError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}],"url":"\/documentation\/oneginisdkios\/onggenericerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/deviceRegistrationFailure":{"role":"symbol","title":"ONGGenericError.deviceRegistrationFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceRegistrationFailure"}],"abstract":[{"type":"text","text":"The device could not be registered with the Token Server, verify that the SDK configuration, Token Server configuration and security features are correctly configured."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceRegistrationFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorDeviceRegistrationFailure"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/deviceregistrationfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/deviceDeregistered":{"role":"symbol","title":"ONGGenericError.deviceDeregistered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceDeregistered"}],"abstract":[{"type":"text","text":"The device registration was removed from the Token Server. All locally stored data is removed from the device and the user needs to register again."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceDeregistered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorDeviceDeregistered"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/devicederegistered"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError/appIntegrityFailure":{"role":"symbol","title":"ONGGenericError.appIntegrityFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appIntegrityFailure"}],"abstract":[{"type":"text","text":"Application integrity check failed. Please verify application signature on the Token Server."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/appIntegrityFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericErrorAppIntegrityFailure"}],"url":"\/documentation\/oneginisdkios\/onggenericerror\/appintegrityfailure"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGGenericError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGGenericError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionAlreadyInProgress","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/actionCancelled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/appIntegrityFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/configurationInvalid","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/dataStorageNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceDeregistered","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/deviceRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/invalidDateTime","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/networkConnectivityFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedApplication","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/outdatedOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/protectedDataStorageNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/requestInvalid","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/serverNotReachable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unknown","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/unrecoverableDataState","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError\/userDeregistered"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode","text":"ONGErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/title","value":"ONGErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1outdatedApplication\/title","value":"ONGGenericErrorOutdatedApplication"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1outdatedApplication\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorOutdatedApplication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1actionAlreadyInProgress\/title","value":"ONGGenericErrorActionAlreadyInProgress"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1actionAlreadyInProgress\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorActionAlreadyInProgress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1outdatedOS\/title","value":"ONGGenericErrorOutdatedOS"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1outdatedOS\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorOutdatedOS"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1actionCancelled\/title","value":"ONGGenericErrorActionCancelled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1actionCancelled\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorActionCancelled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1unrecoverableDataState\/title","value":"ONGGenericErrorUnrecoverableDataState"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1unrecoverableDataState\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorUnrecoverableDataState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1unknown\/title","value":"ONGGenericErrorUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1unknown\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1userDeregistered\/title","value":"ONGGenericErrorUserDeregistered"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1userDeregistered\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorUserDeregistered"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1configurationInvalid\/title","value":"ONGGenericErrorConfigurationInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1configurationInvalid\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorConfigurationInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1protectedDataStorageNotAvailable\/title","value":"ONGGenericErrorProtectedDataStorageNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1protectedDataStorageNotAvailable\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorProtectedDataStorageNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1serverNotReachable\/title","value":"ONGGenericErrorServerNotReachable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1serverNotReachable\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorServerNotReachable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1requestInvalid\/title","value":"ONGGenericErrorRequestInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1requestInvalid\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorRequestInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1dataStorageNotAvailable\/title","value":"ONGGenericErrorDataStorageNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1dataStorageNotAvailable\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorDataStorageNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1invalidDateTime\/title","value":"ONGGenericErrorInvalidDateTime"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1invalidDateTime\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorInvalidDateTime"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1networkConnectivityFailure\/title","value":"ONGGenericErrorNetworkConnectivityFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1networkConnectivityFailure\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorNetworkConnectivityFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/title","value":"ONGGenericError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1deviceRegistrationFailure\/title","value":"ONGGenericErrorDeviceRegistrationFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1deviceRegistrationFailure\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorDeviceRegistrationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1deviceDeregistered\/title","value":"ONGGenericErrorDeviceDeregistered"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1deviceDeregistered\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorDeviceDeregistered"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1appIntegrityFailure\/title","value":"ONGGenericErrorAppIntegrityFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError~1appIntegrityFailure\/fragments","value":[{"kind":"identifier","text":"ONGGenericErrorAppIntegrityFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}