{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGisMainBundle64Bit"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongismainbundle64bit()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongismainbundle64bit()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGisMainBundle64Bit()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGisMainBundle64Bit"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"ONGisMainBundle64Bit()","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:ONGAbuseDetection.h@F@ONGisMainBundle64Bit","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGisMainBundle64Bit"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGisMainBundle64Bit()":{"role":"symbol","title":"ONGisMainBundle64Bit()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGisMainBundle64Bit"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGisMainBundle64Bit()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGisMainBundle64Bit"}],"url":"\/documentation\/oneginisdkios\/ongismainbundle64bit()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"ONGisMainBundle64Bit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGisMainBundle64Bit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGisMainBundle64Bit"},{"kind":"text","text":"()"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGisMainBundle64Bit()\/title","value":"ONGisMainBundle64Bit"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGisMainBundle64Bit()\/fragments","value":[{"kind":"identifier","text":"ONGisMainBundle64Bit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}