{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGKeychainManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongkeychainmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongkeychainmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/appId()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteBiometricRefreshToken(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteKeyPair()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePayloadEncryptionStatusFlag()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePreferredAuthenticator(forProfileId:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteRefreshToken(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteSDKDataVersion()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUUID()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUsedPinAttempts(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchBiometricRefreshToken(forProfile:prompt:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchRefreshToken(withPin:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchSDKDataVersion()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchUsedPinAttempts(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/generateKeyPair()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/getUUID()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isBiometricRefreshTokenStored(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isRefreshTokenStored(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/payloadEncryptionEnabled()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/preferredAuthenticator(forProfileId:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/privateKey()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/publicKey(fromPrivateKey:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/setPayloadEncryptionEnabled(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeBiometricRefreshToken(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storePreferredAuthenticator(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeRefreshToken(_:pin:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeSDKDataVersion(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeUsedPinAttempts(_:profile:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGKeychainManager"}],"title":"ONGKeychainManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGKeychainManager","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGKeychainManager"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/fetchRefreshToken(withPin:profile:)":{"role":"symbol","title":"fetchRefreshToken(withPin:profile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchRefreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchRefreshToken(withPin:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchRefreshTokenWithPin:profile:error:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/fetchrefreshtoken(withpin:profile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/isRefreshTokenStored(forProfile:)":{"role":"symbol","title":"isRefreshTokenStored(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRefreshTokenStored"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isRefreshTokenStored(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRefreshTokenStoredForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/isrefreshtokenstored(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteRefreshToken(forProfile:)":{"role":"symbol","title":"deleteRefreshToken(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteRefreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteRefreshToken(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteRefreshTokenForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deleterefreshtoken(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/isBiometricRefreshTokenStored(forProfile:)":{"role":"symbol","title":"isBiometricRefreshTokenStored(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isBiometricRefreshTokenStored"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isBiometricRefreshTokenStored(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isBiometricRefreshTokenStoredForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/isbiometricrefreshtokenstored(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/setPayloadEncryptionEnabled(_:)":{"role":"symbol","title":"setPayloadEncryptionEnabled(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPayloadEncryptionEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/setPayloadEncryptionEnabled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPayloadEncryptionEnabled:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/setpayloadencryptionenabled(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/fetchBiometricRefreshToken(forProfile:prompt:error:)":{"role":"symbol","title":"fetchBiometricRefreshToken(forProfile:prompt:error:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchBiometricRefreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"prompt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchBiometricRefreshToken(forProfile:prompt:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchBiometricRefreshTokenForProfile:prompt:error:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/fetchbiometricrefreshtoken(forprofile:prompt:error:)"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/storePreferredAuthenticator(_:profile:)":{"role":"symbol","title":"storePreferredAuthenticator(_:profile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storePreferredAuthenticator"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storePreferredAuthenticator(_:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storePreferredAuthenticator:profile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/storepreferredauthenticator(_:profile:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteSDKDataVersion()":{"role":"symbol","title":"deleteSDKDataVersion()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteSDKDataVersion"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteSDKDataVersion()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteSDKDataVersion"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deletesdkdataversion()"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/generateKeyPair()":{"role":"symbol","title":"generateKeyPair()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateKeyPair"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/generateKeyPair()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"generateKeyPairWithError:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/generatekeypair()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteUUID()":{"role":"symbol","title":"deleteUUID()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteUUID"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUUID()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteUUID"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deleteuuid()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/privateKey()":{"role":"symbol","title":"privateKey()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateKey"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/privateKey()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"privateKeyWithError:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/privatekey()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/payloadEncryptionEnabled()":{"role":"symbol","title":"payloadEncryptionEnabled()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"payloadEncryptionEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/payloadEncryptionEnabled()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"payloadEncryptionEnabled"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/payloadencryptionenabled()"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/preferredAuthenticator(forProfileId:)":{"role":"symbol","title":"preferredAuthenticator(forProfileId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredAuthenticator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/preferredAuthenticator(forProfileId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredAuthenticatorForProfileId:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/preferredauthenticator(forprofileid:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/publicKey(fromPrivateKey:)":{"role":"symbol","title":"publicKey(fromPrivateKey:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"publicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromPrivateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/publicKey(fromPrivateKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publicKeyFromPrivateKey:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/publickey(fromprivatekey:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/storeSDKDataVersion(_:)":{"role":"symbol","title":"storeSDKDataVersion(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeSDKDataVersion"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeSDKDataVersion(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeSDKDataVersion:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/storesdkdataversion(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteUsedPinAttempts(forProfile:)":{"role":"symbol","title":"deleteUsedPinAttempts(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteUsedPinAttempts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUsedPinAttempts(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteUsedPinAttemptsForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deleteusedpinattempts(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deletePreferredAuthenticator(forProfileId:)":{"role":"symbol","title":"deletePreferredAuthenticator(forProfileId:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletePreferredAuthenticator"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePreferredAuthenticator(forProfileId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deletePreferredAuthenticatorForProfileId:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deletepreferredauthenticator(forprofileid:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deletePayloadEncryptionStatusFlag()":{"role":"symbol","title":"deletePayloadEncryptionStatusFlag()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletePayloadEncryptionStatusFlag"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePayloadEncryptionStatusFlag()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deletePayloadEncryptionStatusFlag"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deletepayloadencryptionstatusflag()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/storeUsedPinAttempts(_:profile:)":{"role":"symbol","title":"storeUsedPinAttempts(_:profile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeUsedPinAttempts"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeUsedPinAttempts(_:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeUsedPinAttempts:profile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/storeusedpinattempts(_:profile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager":{"role":"symbol","title":"ONGKeychainManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGKeychainManager"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGKeychainManager"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/storeRefreshToken(_:pin:profile:)":{"role":"symbol","title":"storeRefreshToken(_:pin:profile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeRefreshToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeRefreshToken(_:pin:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeRefreshToken:pin:profile:error:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/storerefreshtoken(_:pin:profile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/appId()":{"role":"symbol","title":"appId()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appId"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/appId()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appId"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/appid()"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/storeBiometricRefreshToken(_:profile:)":{"role":"symbol","title":"storeBiometricRefreshToken(_:profile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeBiometricRefreshToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeBiometricRefreshToken(_:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeBiometricRefreshToken:profile:error:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/storebiometricrefreshtoken(_:profile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteKeyPair()":{"role":"symbol","title":"deleteKeyPair()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteKeyPair"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteKeyPair()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteKeyPairWithError:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deletekeypair()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/deleteBiometricRefreshToken(forProfile:)":{"role":"symbol","title":"deleteBiometricRefreshToken(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBiometricRefreshToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteBiometricRefreshToken(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteBiometricRefreshTokenForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/deletebiometricrefreshtoken(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/fetchSDKDataVersion()":{"role":"symbol","title":"fetchSDKDataVersion()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSDKDataVersion"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchSDKDataVersion()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchSDKDataVersion"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/fetchsdkdataversion()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/fetchUsedPinAttempts(forProfile:)":{"role":"symbol","title":"fetchUsedPinAttempts(forProfile:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUsedPinAttempts"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchUsedPinAttempts(forProfile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchUsedPinAttemptsForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/fetchusedpinattempts(forprofile:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManager/getUUID()":{"role":"symbol","title":"getUUID()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUUID"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/getUUID()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUUID:"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanager\/getuuid()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGKeychainManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGKeychainManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGKeychainManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/appId()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteBiometricRefreshToken(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteKeyPair()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePayloadEncryptionStatusFlag()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deletePreferredAuthenticator(forProfileId:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteRefreshToken(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteSDKDataVersion()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUUID()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/deleteUsedPinAttempts(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchBiometricRefreshToken(forProfile:prompt:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchRefreshToken(withPin:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchSDKDataVersion()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/fetchUsedPinAttempts(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/generateKeyPair()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/getUUID()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isBiometricRefreshTokenStored(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/isRefreshTokenStored(forProfile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/payloadEncryptionEnabled()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/preferredAuthenticator(forProfileId:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/privateKey()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/publicKey(fromPrivateKey:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/setPayloadEncryptionEnabled(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeBiometricRefreshToken(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storePreferredAuthenticator(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeRefreshToken(_:pin:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeSDKDataVersion(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManager\/storeUsedPinAttempts(_:profile:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGKeychainManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchRefreshToken(withPin:profile:)\/title","value":"fetchRefreshTokenWithPin:profile:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchRefreshToken(withPin:profile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchRefreshTokenWithPin:profile:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1isRefreshTokenStored(forProfile:)\/title","value":"isRefreshTokenStoredForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1isRefreshTokenStored(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isRefreshTokenStoredForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteRefreshToken(forProfile:)\/title","value":"deleteRefreshTokenForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteRefreshToken(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteRefreshTokenForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1isBiometricRefreshTokenStored(forProfile:)\/title","value":"isBiometricRefreshTokenStoredForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1isBiometricRefreshTokenStored(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isBiometricRefreshTokenStoredForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1setPayloadEncryptionEnabled(_:)\/title","value":"setPayloadEncryptionEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1setPayloadEncryptionEnabled(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setPayloadEncryptionEnabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchBiometricRefreshToken(forProfile:prompt:error:)\/title","value":"fetchBiometricRefreshTokenForProfile:prompt:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchBiometricRefreshToken(forProfile:prompt:error:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchBiometricRefreshTokenForProfile:prompt:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storePreferredAuthenticator(_:profile:)\/title","value":"storePreferredAuthenticator:profile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storePreferredAuthenticator(_:profile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"storePreferredAuthenticator:profile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteSDKDataVersion()\/title","value":"deleteSDKDataVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteSDKDataVersion()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteSDKDataVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1generateKeyPair()\/title","value":"generateKeyPairWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1generateKeyPair()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"generateKeyPairWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteUUID()\/title","value":"deleteUUID"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteUUID()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteUUID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1privateKey()\/title","value":"privateKeyWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1privateKey()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"privateKeyWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1payloadEncryptionEnabled()\/title","value":"payloadEncryptionEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1payloadEncryptionEnabled()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"payloadEncryptionEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1preferredAuthenticator(forProfileId:)\/title","value":"preferredAuthenticatorForProfileId:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1preferredAuthenticator(forProfileId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"preferredAuthenticatorForProfileId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1publicKey(fromPrivateKey:)\/title","value":"publicKeyFromPrivateKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1publicKey(fromPrivateKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"publicKeyFromPrivateKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeSDKDataVersion(_:)\/title","value":"storeSDKDataVersion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeSDKDataVersion(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"storeSDKDataVersion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteUsedPinAttempts(forProfile:)\/title","value":"deleteUsedPinAttemptsForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteUsedPinAttempts(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteUsedPinAttemptsForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deletePreferredAuthenticator(forProfileId:)\/title","value":"deletePreferredAuthenticatorForProfileId:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deletePreferredAuthenticator(forProfileId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deletePreferredAuthenticatorForProfileId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deletePayloadEncryptionStatusFlag()\/title","value":"deletePayloadEncryptionStatusFlag"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deletePayloadEncryptionStatusFlag()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deletePayloadEncryptionStatusFlag"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeUsedPinAttempts(_:profile:)\/title","value":"storeUsedPinAttempts:profile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeUsedPinAttempts(_:profile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"storeUsedPinAttempts:profile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager\/title","value":"ONGKeychainManager"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager\/fragments","value":[{"kind":"identifier","text":"ONGKeychainManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeRefreshToken(_:pin:profile:)\/title","value":"storeRefreshToken:pin:profile:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeRefreshToken(_:pin:profile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"storeRefreshToken:pin:profile:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1appId()\/title","value":"appId"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1appId()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"appId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeBiometricRefreshToken(_:profile:)\/title","value":"storeBiometricRefreshToken:profile:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1storeBiometricRefreshToken(_:profile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"storeBiometricRefreshToken:profile:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteKeyPair()\/title","value":"deleteKeyPairWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteKeyPair()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteKeyPairWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteBiometricRefreshToken(forProfile:)\/title","value":"deleteBiometricRefreshTokenForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1deleteBiometricRefreshToken(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"deleteBiometricRefreshTokenForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchSDKDataVersion()\/title","value":"fetchSDKDataVersion"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchSDKDataVersion()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchSDKDataVersion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchUsedPinAttempts(forProfile:)\/title","value":"fetchUsedPinAttemptsForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1fetchUsedPinAttempts(forProfile:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fetchUsedPinAttemptsForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1getUUID()\/title","value":"getUUID:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManager~1getUUID()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getUUID:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}