{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/clientPGPKeyPair(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteClientPGPKeyPair(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deletePGPKeys(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteServerPGPPublicKey(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/isProfileEnrolled(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/serverPGPPublicKey(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeClientPGPKeyPair(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeServerPGPPublicKey(_:profile:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthModel"}],"title":"ONGMobileAuthModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGMobileAuthModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/storeServerPGPPublicKey(_:profile:)":{"role":"symbol","title":"storeServerPGPPublicKey(_:profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeServerPGPPublicKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeServerPGPPublicKey(_:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeServerPGPPublicKey:profile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/storeserverpgppublickey(_:profile:)"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/deleteServerPGPPublicKey(for:)":{"role":"symbol","title":"deleteServerPGPPublicKey(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteServerPGPPublicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteServerPGPPublicKey(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteServerPGPPublicKeyForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/deleteserverpgppublickey(for:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/isProfileEnrolled(forMobileAuth:)":{"role":"symbol","title":"isProfileEnrolled(forMobileAuth:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isProfileEnrolled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMobileAuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/isProfileEnrolled(forMobileAuth:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isProfileEnrolledForMobileAuth:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/isprofileenrolled(formobileauth:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/deletePGPKeys(for:)":{"role":"symbol","title":"deletePGPKeys(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletePGPKeys"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deletePGPKeys(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deletePGPKeysForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/deletepgpkeys(for:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/deleteClientPGPKeyPair(for:)":{"role":"symbol","title":"deleteClientPGPKeyPair(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteClientPGPKeyPair"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteClientPGPKeyPair(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteClientPGPKeyPairForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/deleteclientpgpkeypair(for:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/clientPGPKeyPair(for:)":{"role":"symbol","title":"clientPGPKeyPair(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientPGPKeyPair"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/clientPGPKeyPair(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientPGPKeyPairForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/clientpgpkeypair(for:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/serverPGPPublicKey(for:)":{"role":"symbol","title":"serverPGPPublicKey(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverPGPPublicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/serverPGPPublicKey(for:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverPGPPublicKeyForProfile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/serverpgppublickey(for:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel":{"role":"symbol","title":"ONGMobileAuthModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthModel"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthModel/storeClientPGPKeyPair(_:profile:)":{"role":"symbol","title":"storeClientPGPKeyPair(_:profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeClientPGPKeyPair"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGPGPKeyPair","preciseIdentifier":"c:objc(cs)ONGPGPKeyPair"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeClientPGPKeyPair(_:profile:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeClientPGPKeyPair:profile:"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthmodel\/storeclientpgpkeypair(_:profile:)"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGMobileAuthModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/clientPGPKeyPair(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteClientPGPKeyPair(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deletePGPKeys(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/deleteServerPGPPublicKey(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/isProfileEnrolled(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/serverPGPPublicKey(for:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeClientPGPKeyPair(_:profile:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthModel\/storeServerPGPPublicKey(_:profile:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1storeServerPGPPublicKey(_:profile:)\/title","value":"storeServerPGPPublicKey:profile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1storeServerPGPPublicKey(_:profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeServerPGPPublicKey:profile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deleteServerPGPPublicKey(for:)\/title","value":"deleteServerPGPPublicKeyForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deleteServerPGPPublicKey(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteServerPGPPublicKeyForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1isProfileEnrolled(forMobileAuth:)\/title","value":"isProfileEnrolledForMobileAuth:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1isProfileEnrolled(forMobileAuth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isProfileEnrolledForMobileAuth:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deletePGPKeys(for:)\/title","value":"deletePGPKeysForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deletePGPKeys(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deletePGPKeysForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deleteClientPGPKeyPair(for:)\/title","value":"deleteClientPGPKeyPairForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1deleteClientPGPKeyPair(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteClientPGPKeyPairForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1clientPGPKeyPair(for:)\/title","value":"clientPGPKeyPairForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1clientPGPKeyPair(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientPGPKeyPairForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1serverPGPPublicKey(for:)\/title","value":"serverPGPPublicKeyForProfile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1serverPGPPublicKey(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serverPGPPublicKeyForProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel\/title","value":"ONGMobileAuthModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1storeClientPGPKeyPair(_:profile:)\/title","value":"storeClientPGPKeyPair:profile:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthModel~1storeClientPGPKeyPair(_:profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeClientPGPKeyPair:profile:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}