{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)TyphoonAssembly"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)TyphoonComponentFactory"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientIdModel()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/mobileAuthenticationAction(with:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/oAuthSessionModel()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/sessionTokens()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"title":"ONGModelAssembly","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGModelAssembly","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGModelAssembly"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/sessionTokens()":{"role":"symbol","title":"sessionTokens()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/sessionTokens()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/sessiontokens()"},"doc://com.onegini.OneginiSDKiOS/objc(pl)TyphoonComponentFactory":{"type":"unresolvable","title":"Typhoon.TyphoonComponentFactoryProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)TyphoonComponentFactory"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/mobileAuthenticationAction(with:)":{"role":"symbol","title":"mobileAuthenticationAction(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequestDelegate","preciseIdentifier":"c:objc(pl)ONGMobileAuthRequestDelegate"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationActionDTO","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationActionDTO"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/mobileAuthenticationAction(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationActionWithDelegate:"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/mobileauthenticationaction(with:)"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/authenticatorProvider":{"role":"symbol","title":"authenticatorProvider","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticatorProvider"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/authenticatorProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticatorProvider"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/authenticatorprovider"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/oAuthSessionModel()":{"role":"symbol","title":"oAuthSessionModel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/oAuthSessionModel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/oauthsessionmodel()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/clientConfigModel":{"role":"symbol","title":"clientConfigModel","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientConfigModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientConfigModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientConfigModel"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/clientconfigmodel"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly":{"role":"symbol","title":"ONGModelAssembly","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGModelAssembly"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/clientIdModel()":{"role":"symbol","title":"clientIdModel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientIdModel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/clientidmodel()"},"doc://com.onegini.OneginiSDKiOS/objc(cs)TyphoonAssembly":{"type":"unresolvable","title":"TyphoonAssembly","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)TyphoonAssembly"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/clientCredentialsModel":{"role":"symbol","title":"clientCredentialsModel","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientCredentialsModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientCredentialsModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientCredentialsModel"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/clientcredentialsmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGModelAssembly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGModelAssembly"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGModelAssembly"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/authenticatorProvider","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientConfigModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientCredentialsModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientIdModel()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/mobileAuthenticationAction(with:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/oAuthSessionModel()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/sessionTokens()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)TyphoonAssembly"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"TyphoonAssembly","preciseIdentifier":"c:objc(cs)TyphoonAssembly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1sessionTokens()\/title","value":"sessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1sessionTokens()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1mobileAuthenticationAction(with:)\/title","value":"mobileAuthenticationActionWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1mobileAuthenticationAction(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mobileAuthenticationActionWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1oAuthSessionModel()\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1oAuthSessionModel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/title","value":"ONGModelAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/fragments","value":[{"kind":"identifier","text":"ONGModelAssembly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1clientIdModel()\/title","value":"clientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1clientIdModel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientIdModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}