{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See -[ONGUserClient enrollForMobileAuth:]"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterrordomain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentErrorDomain","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"ONGMobileAuthEnrollmentErrorDomain contains errors that happen during Mobile Authentication Enrollment."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"ONGMobileAuthEnrollmentErrorDomain","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@ONGMobileAuthEnrollmentErrorDomain","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentErrorDomain":{"role":"symbol","title":"ONGMobileAuthEnrollmentErrorDomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"ONGMobileAuthEnrollmentErrorDomain contains errors that happen during Mobile Authentication Enrollment."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentErrorDomain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterrordomain"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthEnrollmentErrorDomain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentErrorDomain\/title","value":"ONGMobileAuthEnrollmentErrorDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentErrorDomain\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDomain"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}