{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthEnrollmentErrorDomain"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"title":"ONGMobileAuthEnrollmentError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGMobileAuthEnrollmentError","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/deviceAlreadyEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/enrollmentNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/notEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userAlreadyEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userNotAuthenticated"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError":{"role":"symbol","title":"ONGMobileAuthEnrollmentError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthEnrollmentErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/userAlreadyEnrolled":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.userAlreadyEnrolled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAlreadyEnrolled"}],"abstract":[{"type":"text","text":"The user is already enrolled for mobile authentication on another device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userAlreadyEnrolled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/useralreadyenrolled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/userNotAuthenticated":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.userNotAuthenticated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotAuthenticated"}],"abstract":[{"type":"text","text":"No user is currently authenticated, possibly due to the fact that the access token has expired. A user must be authenticated in order to enroll for mobile authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userNotAuthenticated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserNotAuthenticated"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/usernotauthenticated"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorCode":{"role":"symbol","title":"ONGErrorCode","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongerrorcode"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/enrollmentNotAvailable":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.enrollmentNotAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enrollmentNotAvailable"}],"abstract":[{"type":"text","text":"The Mobile authentication feature is disabled in the Token Server configuration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/enrollmentNotAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/enrollmentnotavailable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/notEnrolled":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.notEnrolled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notEnrolled"}],"abstract":[{"type":"text","text":"The user is not enrolled for mobile authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/notEnrolled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorNotEnrolled"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/notenrolled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/deviceAlreadyEnrolled":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.deviceAlreadyEnrolled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceAlreadyEnrolled"}],"abstract":[{"type":"text","text":"The device is already enrolled for mobile authentication. This may happen in case an old push token is still left behind in the Token Server database and is reused by the OS."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/deviceAlreadyEnrolled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDeviceAlreadyEnrolled"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/devicealreadyenrolled"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthEnrollmentError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/deviceAlreadyEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/enrollmentNotAvailable","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/notEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userAlreadyEnrolled","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userNotAuthenticated"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode","text":"ONGErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/title","value":"ONGMobileAuthEnrollmentError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userAlreadyEnrolled\/title","value":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userAlreadyEnrolled\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userNotAuthenticated\/title","value":"ONGMobileAuthEnrollmentErrorUserNotAuthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userNotAuthenticated\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserNotAuthenticated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/title","value":"ONGErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1enrollmentNotAvailable\/title","value":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1enrollmentNotAvailable\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1notEnrolled\/title","value":"ONGMobileAuthEnrollmentErrorNotEnrolled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1notEnrolled\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorNotEnrolled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1deviceAlreadyEnrolled\/title","value":"ONGMobileAuthEnrollmentErrorDeviceAlreadyEnrolled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1deviceAlreadyEnrolled\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorDeviceAlreadyEnrolled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}