{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenticationmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenticationmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/OTP","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/biometric","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/customAuthenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/default","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/pin","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/undefined"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"title":"ONGMobileAuthenticationMethod","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGMobileAuthenticationMethod","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/customAuthenticator":{"role":"symbol","title":"ONGMobileAuthenticationMethod.customAuthenticator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customAuthenticator"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/customAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodCustomAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/customauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/default":{"role":"symbol","title":"ONGMobileAuthenticationMethod.default","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodDefault"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/default"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/OTP":{"role":"symbol","title":"ONGMobileAuthenticationMethod.OTP","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OTP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/OTP","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodOTP"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/otp"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/pin":{"role":"symbol","title":"ONGMobileAuthenticationMethod.pin","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pin"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/pin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodPin"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/pin"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod":{"role":"symbol","title":"ONGMobileAuthenticationMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/undefined":{"role":"symbol","title":"ONGMobileAuthenticationMethod.undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/undefined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodUndefined"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/undefined"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod/biometric":{"role":"symbol","title":"ONGMobileAuthenticationMethod.biometric","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometric"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/biometric","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodBiometric"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod\/biometric"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthenticationMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/OTP","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/biometric","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/customAuthenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/default","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/pin","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod\/undefined"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1customAuthenticator\/title","value":"ONGMobileAuthenticationMethodCustomAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1customAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodCustomAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1default\/title","value":"ONGMobileAuthenticationMethodDefault"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1default\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodDefault"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1OTP\/title","value":"ONGMobileAuthenticationMethodOTP"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1OTP\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodOTP"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1pin\/title","value":"ONGMobileAuthenticationMethodPin"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1pin\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodPin"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/title","value":"ONGMobileAuthenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1undefined\/title","value":"ONGMobileAuthenticationMethodUndefined"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1undefined\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodUndefined"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1biometric\/title","value":"ONGMobileAuthenticationMethodBiometric"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod~1biometric\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethodBiometric"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}