{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGOAuthSessionModel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongoauthsessionmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongoauthsessionmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class provides access to session scope properties."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGOAuthSessionModel"}],"title":"ONGOAuthSessionModel","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGOAuthSessionModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGOAuthSessionModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/additionalResourceUrls","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientSessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/configModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitSessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/serverPublicKey","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/sessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/x509PEMcertificates"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/accessToken()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearSession(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearTokens()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientAccessToken()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/customUserAgentHeader()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitAccessToken()"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/clientAccessToken()":{"role":"symbol","title":"clientAccessToken()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAccessToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientAccessToken()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientAccessToken"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/clientaccesstoken()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/clientSessionTokens":{"role":"symbol","title":"clientSessionTokens","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientSessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientSessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/clientsessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/sessionTokens":{"role":"symbol","title":"sessionTokens","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/sessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/sessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/accessToken()":{"role":"symbol","title":"accessToken()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/accessToken()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessToken"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/accesstoken()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel":{"role":"symbol","title":"ONGOAuthSessionModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGOAuthSessionModel"}],"abstract":[{"type":"text","text":"This class provides access to session scope properties."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGOAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/customUserAgentHeader()":{"role":"symbol","title":"customUserAgentHeader()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customUserAgentHeader"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/customUserAgentHeader()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customUserAgentHeader"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/customuseragentheader()"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/configModel":{"role":"symbol","title":"configModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGConfigModel","preciseIdentifier":"c:objc(cs)ONGConfigModel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/configModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configModel"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/configmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/implicitAccessToken()":{"role":"symbol","title":"implicitAccessToken()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitAccessToken"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitAccessToken()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"implicitAccessToken"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/implicitaccesstoken()"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/clearSession(_:)":{"role":"symbol","title":"clearSession(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGSessionTokensType","preciseIdentifier":"c:@E@ONGSessionTokensType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearSession(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearSession:"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/clearsession(_:)"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/x509PEMcertificates":{"role":"symbol","title":"x509PEMcertificates","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"x509PEMcertificates"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/x509PEMcertificates","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"x509PEMcertificates"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/x509pemcertificates"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/clearTokens()":{"role":"symbol","title":"clearTokens()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearTokens"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Clear the encrypted refresh token from the key chain and reset"},{"type":"text","text":" "},{"type":"text","text":"the pin attempt count and current the session."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearTokens()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearTokens"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/cleartokens()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/additionalResourceUrls":{"role":"symbol","title":"additionalResourceUrls","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalResourceUrls"},{"kind":"text","text":": ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/additionalResourceUrls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalResourceUrls"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/additionalresourceurls"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/implicitSessionTokens":{"role":"symbol","title":"implicitSessionTokens","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitSessionTokens"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitSessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"implicitSessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/implicitsessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGOAuthSessionModel/serverPublicKey":{"role":"symbol","title":"serverPublicKey","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"serverPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/serverPublicKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"serverPublicKey"}],"url":"\/documentation\/oneginisdkios\/ongoauthsessionmodel\/serverpublickey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGOAuthSessionModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGOAuthSessionModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGOAuthSessionModel"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/additionalResourceUrls","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientSessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/configModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitSessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/serverPublicKey","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/sessionTokens","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/x509PEMcertificates"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/accessToken()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearSession(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clearTokens()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/clientAccessToken()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/customUserAgentHeader()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGOAuthSessionModel\/implicitAccessToken()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGOAuthSessionModel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clientAccessToken()\/title","value":"clientAccessToken"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clientAccessToken()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientAccessToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clientSessionTokens\/title","value":"clientSessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clientSessionTokens\/fragments","value":[{"kind":"identifier","text":"clientSessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1sessionTokens\/title","value":"sessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1sessionTokens\/fragments","value":[{"kind":"identifier","text":"sessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1accessToken()\/title","value":"accessToken"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1accessToken()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"accessToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel\/title","value":"ONGOAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"ONGOAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1customUserAgentHeader()\/title","value":"customUserAgentHeader"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1customUserAgentHeader()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"customUserAgentHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1configModel\/title","value":"configModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1configModel\/fragments","value":[{"kind":"identifier","text":"configModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1implicitAccessToken()\/title","value":"implicitAccessToken"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1implicitAccessToken()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"implicitAccessToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clearSession(_:)\/title","value":"clearSession:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clearSession(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearSession:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1x509PEMcertificates\/title","value":"x509PEMcertificates"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1x509PEMcertificates\/fragments","value":[{"kind":"identifier","text":"x509PEMcertificates"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clearTokens()\/title","value":"clearTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1clearTokens()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1additionalResourceUrls\/title","value":"additionalResourceUrls"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1additionalResourceUrls\/fragments","value":[{"kind":"identifier","text":"additionalResourceUrls"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1implicitSessionTokens\/title","value":"implicitSessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1implicitSessionTokens\/fragments","value":[{"kind":"identifier","text":"implicitSessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1serverPublicKey\/title","value":"serverPublicKey"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGOAuthSessionModel~1serverPublicKey\/fragments","value":[{"kind":"identifier","text":"serverPublicKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}