{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerrormaxsimilardigitskey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerrormaxsimilardigitskey"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationErrorMaxSimilarDigitsKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The key for max similar digits value returned within userInfo. The value is defined by the received pin policy."},{"type":"text","text":" "},{"type":"text","text":"It is returned when Pin Validation fails with error ONGPinValidationErrorPinShouldNotUseSimilarDigits."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"ONGPinValidationErrorMaxSimilarDigitsKey","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@ONGPinValidationErrorMaxSimilarDigitsKey","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationErrorMaxSimilarDigitsKey":{"role":"symbol","title":"ONGPinValidationErrorMaxSimilarDigitsKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The key for max similar digits value returned within userInfo. The value is defined by the received pin policy."},{"type":"text","text":" "},{"type":"text","text":"It is returned when Pin Validation fails with error ONGPinValidationErrorPinShouldNotUseSimilarDigits."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationErrorMaxSimilarDigitsKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerrormaxsimilardigitskey"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinValidationErrorMaxSimilarDigitsKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationErrorMaxSimilarDigitsKey\/title","value":"ONGPinValidationErrorMaxSimilarDigitsKey"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationErrorMaxSimilarDigitsKey\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorMaxSimilarDigitsKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}