{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerrorrequiredlengthkey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerrorrequiredlengthkey"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationErrorRequiredLengthKey","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The key for recommended pin length returned within userInfo. The value is defined by the received pin policy."},{"type":"text","text":" "},{"type":"text","text":"It is returned when Pin Validation fails with error ONGPinValidationErrorWrongPinLength."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"ONGPinValidationErrorRequiredLengthKey","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@ONGPinValidationErrorRequiredLengthKey","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationErrorRequiredLengthKey":{"role":"symbol","title":"ONGPinValidationErrorRequiredLengthKey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The key for recommended pin length returned within userInfo. The value is defined by the received pin policy."},{"type":"text","text":" "},{"type":"text","text":"It is returned when Pin Validation fails with error ONGPinValidationErrorWrongPinLength."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationErrorRequiredLengthKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerrorrequiredlengthkey"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinValidationErrorRequiredLengthKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationErrorRequiredLengthKey\/title","value":"ONGPinValidationErrorRequiredLengthKey"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationErrorRequiredLengthKey\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorRequiredLengthKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}