{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinchallenge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinchallenge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents authentication with PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"}],"title":"ONGPinChallenge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGPinChallenge","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinChallenge"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/authenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/error","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/maxFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/previousFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/remainingFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/userProfile"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/previousFailureCount":{"role":"symbol","title":"previousFailureCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previousFailureCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Pin attempts used by the user on this device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/previousFailureCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"previousFailureCount"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/previousfailurecount"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/userProfile":{"role":"symbol","title":"userProfile","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"}],"abstract":[{"type":"text","text":"User profile for which authentication challenge was sent."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/userProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userProfile"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/userprofile"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge":{"role":"symbol","title":"ONGPinChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinChallenge"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/maxFailureCount":{"role":"symbol","title":"maxFailureCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFailureCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Maximum allowed pin attempts for the user."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/maxFailureCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxFailureCount"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/maxfailurecount"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/sender":{"role":"symbol","title":"sender","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGPinChallengeSender","preciseIdentifier":"c:objc(pl)ONGPinChallengeSender"}],"abstract":[{"type":"text","text":"Sender awaiting for response to the authenticate with PIN challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/sender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sender"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/sender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/authenticator":{"role":"symbol","title":"authenticator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"}],"abstract":[{"type":"text","text":"Authenticator object which authentication challenge was sent to."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/authenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticator"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/authenticator"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error describing cause of failure of previous challenge response."},{"type":"text","text":" "},{"type":"text","text":"Possible error domains: ONGAuthenticatorRegistrationErrorDomain, ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"error"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/error"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/remainingFailureCount":{"role":"symbol","title":"remainingFailureCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"remainingFailureCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Available pin attempts left for the user on this device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/remainingFailureCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"remainingFailureCount"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/remainingfailurecount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinChallenge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinChallenge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGPinChallenge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/authenticator","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/error","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/maxFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/previousFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/remainingFailureCount","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/sender","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/userProfile"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1previousFailureCount\/title","value":"previousFailureCount"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1previousFailureCount\/fragments","value":[{"kind":"identifier","text":"previousFailureCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1userProfile\/title","value":"userProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1userProfile\/fragments","value":[{"kind":"identifier","text":"userProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/title","value":"ONGPinChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/fragments","value":[{"kind":"identifier","text":"ONGPinChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1maxFailureCount\/title","value":"maxFailureCount"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1maxFailureCount\/fragments","value":[{"kind":"identifier","text":"maxFailureCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1sender\/title","value":"sender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1sender\/fragments","value":[{"kind":"identifier","text":"sender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1authenticator\/title","value":"authenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1authenticator\/fragments","value":[{"kind":"identifier","text":"authenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1error\/title","value":"error"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1error\/fragments","value":[{"kind":"identifier","text":"error"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1remainingFailureCount\/title","value":"remainingFailureCount"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1remainingFailureCount\/fragments","value":[{"kind":"identifier","text":"remainingFailureCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}