{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongregistrationdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete registration."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"}],"title":"ONGRegistrationDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)ONGRegistrationDelegate","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didFailToRegisterWith:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceive:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationFinish:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationInitChallenge:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceivePinRegistrationChallenge:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didRegisterUser:identityProvider:info:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClientDidStartRegistration(_:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didFailToRegisterWith:error:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}],"role":"symbol","title":"userClient(_:didFailToRegisterWith:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToRegisterWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when registration action failed with error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didFailToRegisterWith:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didfailtoregisterwith:error:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didReceiveCustomRegistrationFinish:)":{"role":"symbol","title":"userClient(_:didReceiveCustomRegistrationFinish:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveCustomRegistrationFinish"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when the second step of two step custom registration or one step custom registration requires a optional data to continue."},{"type":"text","text":" "},{"type":"text","text":"You now need to call the respondWithData:challenge: method of id"},{"type":"text","text":" instance, in order to provide optional data to the finish step and continue the two step registration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationFinish:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivecustomregistrationfinish:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didReceivePinRegistrationChallenge:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceivePinRegistrationChallenge:"}],"role":"symbol","title":"userClient(_:didReceivePinRegistrationChallenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceivePinRegistrationChallenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when registration action requires creation of a PIN to continue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceivePinRegistrationChallenge:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivepinregistrationchallenge:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate":{"role":"symbol","title":"ONGRegistrationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to complete registration."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didRegisterUser:identityProvider:info:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didRegisterUser:identityProvider:info:"}],"role":"symbol","title":"userClient(_:didRegisterUser:identityProvider:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"identityProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method called when registration action is completed with success."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didRegisterUser:identityProvider:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didregisteruser:identityprovider:info:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClientDidStartRegistration(_:)":{"role":"symbol","title":"userClientDidStartRegistration(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClientDidStartRegistration"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when registration action is started."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClientDidStartRegistration(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClientDidStartRegistration:"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclientdidstartregistration(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didReceive:)":{"navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveBrowserRegistrationChallenge:"}],"role":"symbol","title":"userClient(_:didReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGBrowserRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGBrowserRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when the registration action requires you to open a browser with the given URL. When the browser is finished processing it will use a"},{"type":"text","text":" "},{"type":"text","text":"custom URL scheme to hand over control to your application. You now need to call the respondWithURL:challenge: method of id"},{"type":"text","text":" "},{"type":"text","text":"instance in order to hand over control to the SDK and continue the registration action."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceive:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceive:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationDelegate/userClient(_:didReceiveCustomRegistrationInitChallenge:)":{"role":"symbol","title":"userClient(_:didReceiveCustomRegistrationInitChallenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceiveCustomRegistrationInitChallenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomRegistrationChallenge","preciseIdentifier":"c:objc(cs)ONGCustomRegistrationChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method called when the initialization of two step custom registration requires a optional data to continue. You now need to call the respondWithData:challenge:"},{"type":"text","text":" "},{"type":"text","text":"method of id"},{"type":"text","text":" instance, in order to provide optional data to the initialization step and continue the two step registration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationInitChallenge:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationInitChallenge:"}],"url":"\/documentation\/oneginisdkios\/ongregistrationdelegate\/userclient(_:didreceivecustomregistrationinitchallenge:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ONGRegistrationDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didFailToRegisterWith:error:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceive:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationFinish:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceiveCustomRegistrationInitChallenge:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didReceivePinRegistrationChallenge:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClient(_:didRegisterUser:identityProvider:info:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationDelegate\/userClientDidStartRegistration(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didFailToRegisterWith:error:)\/title","value":"userClient:didFailToRegisterWithIdentityProvider:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didFailToRegisterWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didFailToRegisterWithIdentityProvider:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationFinish:)\/title","value":"userClient:didReceiveCustomRegistrationFinishChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationFinish:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationFinishChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceivePinRegistrationChallenge:)\/title","value":"userClient:didReceivePinRegistrationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceivePinRegistrationChallenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceivePinRegistrationChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/title","value":"ONGRegistrationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didRegisterUser:identityProvider:info:)\/title","value":"userClient:didRegisterUser:identityProvider:info:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didRegisterUser:identityProvider:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didRegisterUser:identityProvider:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClientDidStartRegistration(_:)\/title","value":"userClientDidStartRegistration:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClientDidStartRegistration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClientDidStartRegistration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceive:)\/title","value":"userClient:didReceiveBrowserRegistrationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceive:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveBrowserRegistrationChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationInitChallenge:)\/title","value":"userClient:didReceiveCustomRegistrationInitChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationDelegate~1userClient(_:didReceiveCustomRegistrationInitChallenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didReceiveCustomRegistrationInitChallenge:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}