{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestbuilder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Object responsible for easier "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" construction."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"title":"ONGRequestBuilder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGRequestBuilder","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGRequestBuilder"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/build()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setBody(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setHeaders(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMethod(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMultipartData(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParameters(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParametersEncoding(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setPath(_:)"]}],"references":{"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setPath(_:)":{"role":"symbol","title":"setPath(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPath"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the path for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setPath(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setPath:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setpath(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setHeaders(_:)":{"role":"symbol","title":"setHeaders(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setHeaders"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the HTTP Headers for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setHeaders(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setHeaders:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setheaders(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/builder":{"role":"symbol","title":"builder","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"builder"}],"abstract":[{"type":"text","text":"Return a new instance of a builder"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/builder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"builder"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/builder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setParameters(_:)":{"role":"symbol","title":"setParameters(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParameters"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the parameters for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParameters(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setParameters:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setparameters(_:)"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder":{"role":"symbol","title":"ONGRequestBuilder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"}],"abstract":[{"type":"text","text":"Object responsible for easier "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestBuilder"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setParametersEncoding(_:)":{"role":"symbol","title":"setParametersEncoding(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setParametersEncoding"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the parametersEncoding for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParametersEncoding(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setParametersEncoding:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setparametersencoding(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/build()":{"role":"symbol","title":"build()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"The build instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" from the current parameters. Since the returned object is immutable any further parameter changes doesn’t"},{"type":"text","text":" "},{"type":"text","text":"have an effect on already build instances."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/build()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/build()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setBody(_:)":{"role":"symbol","title":"setBody(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBody"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the body for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setBody(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBody:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setbody(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setMethod(_:)":{"role":"symbol","title":"setMethod(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMethod"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the HTTP Method for the target "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":". The supported values are: "},{"type":"codeVoice","code":"GET"},{"type":"text","text":", "},{"type":"codeVoice","code":"POST"},{"type":"text","text":", "},{"type":"codeVoice","code":"PUT"},{"type":"text","text":", "},{"type":"codeVoice","code":"DELETE"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMethod(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMethod:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setmethod(_:)"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestBuilder/setMultipartData(_:)":{"role":"symbol","title":"setMultipartData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMultipartData"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData"},{"kind":"text","text":"]!) -> "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":"!"}],"abstract":[{"type":"text","text":"Set the multipartData for the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMultipartData(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMultipartData:"}],"url":"\/documentation\/oneginisdkios\/ongrequestbuilder\/setmultipartdata(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGRequestBuilder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/build()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setBody(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setHeaders(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMethod(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setMultipartData(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParameters(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setParametersEncoding(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/setPath(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestBuilder\/builder"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestBuilder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setPath(_:)\/title","value":"setPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setPath(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setHeaders(_:)\/title","value":"setHeaders:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setHeaders(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setHeaders:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParameters(_:)\/title","value":"setParameters:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParameters(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/title","value":"ONGRequestBuilder"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder\/fragments","value":[{"kind":"identifier","text":"ONGRequestBuilder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParametersEncoding(_:)\/title","value":"setParametersEncoding:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setParametersEncoding(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setParametersEncoding:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1build()\/title","value":"build"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1build()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setBody(_:)\/title","value":"setBody:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setBody(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setBody:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMethod(_:)\/title","value":"setMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMethod(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMultipartData(_:)\/title","value":"setMultipartData:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestBuilder~1setMultipartData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setMultipartData:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}