{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongregistrationerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongregistrationerror"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH","doc:\/\/com.onegini.OneginiSDKiOS\/SY","doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error codes in ONGRegistrationErrorDomain"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationError"}],"title":"ONGRegistrationError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@ONGRegistrationError","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationError"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationExpired","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/deviceRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/externalIdentityProviderFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidIdentityProvider","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidState"]},{"title":"Initializers","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/Equatable-Implementations","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/invalidIdentityProvider":{"role":"symbol","title":"ONGRegistrationError.invalidIdentityProvider","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidIdentityProvider"}],"abstract":[{"type":"text","text":"The specified custom IdP does not exist."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidIdentityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorInvalidIdentityProvider"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/invalididentityprovider"},"doc://com.onegini.OneginiSDKiOS/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SY"},"doc://com.onegini.OneginiSDKiOS/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s8SendableP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationerror\/equatable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationerror\/rawrepresentable-implementations"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorCode":{"role":"symbol","title":"ONGErrorCode","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongerrorcode"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios\/ongregistrationerror\/init(rawvalue:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/invalidState":{"role":"symbol","title":"ONGRegistrationError.invalidState","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidState"}],"abstract":[{"type":"text","text":"A possible security issue was detected during User Registration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorInvalidState"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/invalidstate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/externalIdentityProviderFailure":{"role":"symbol","title":"ONGRegistrationError.externalIdentityProviderFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"externalIdentityProviderFailure"}],"abstract":[{"type":"text","text":"Signing in to external identity provider failed. Please check the underlying for details."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/externalIdentityProviderFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorExternalIdentityProviderFailure"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/externalidentityproviderfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/deviceRegistrationFailure":{"role":"symbol","title":"ONGRegistrationError.deviceRegistrationFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceRegistrationFailure"}],"abstract":[{"type":"text","text":"The device could not be registered with the Token Server, verify that the SDK configuration, Token Server configuration and security features are correctly configured"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/deviceRegistrationFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorDeviceRegistrationFailure"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/deviceregistrationfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/customRegistrationExpired":{"role":"symbol","title":"ONGRegistrationError.customRegistrationExpired","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRegistrationExpired"}],"abstract":[{"type":"text","text":"Invalid transaction id\/state."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationExpired","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorCustomRegistrationExpired"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/customregistrationexpired"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError/customRegistrationFailure":{"role":"symbol","title":"ONGRegistrationError.customRegistrationFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRegistrationFailure"}],"abstract":[{"type":"text","text":"Authentication with the custom authenticator has failed. Please check the CustomInfo for details."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationErrorCustomRegistrationFailure"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror\/customregistrationfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRegistrationError":{"role":"symbol","title":"ONGRegistrationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationError"}],"abstract":[{"type":"text","text":"Error codes in ONGRegistrationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRegistrationError"}],"url":"\/documentation\/oneginisdkios\/ongregistrationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ONGRegistrationError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGRegistrationError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationExpired","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/customRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/deviceRegistrationFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/externalIdentityProviderFailure","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidIdentityProvider","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRegistrationError\/invalidState"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRegistrationError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorCode","preciseIdentifier":"c:ONGErrors.h@T@ONGErrorCode","text":"ONGErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1invalidIdentityProvider\/title","value":"ONGRegistrationErrorInvalidIdentityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1invalidIdentityProvider\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorInvalidIdentityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/title","value":"ONGErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1invalidState\/title","value":"ONGRegistrationErrorInvalidState"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1invalidState\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorInvalidState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1externalIdentityProviderFailure\/title","value":"ONGRegistrationErrorExternalIdentityProviderFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1externalIdentityProviderFailure\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorExternalIdentityProviderFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1deviceRegistrationFailure\/title","value":"ONGRegistrationErrorDeviceRegistrationFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1deviceRegistrationFailure\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorDeviceRegistrationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1customRegistrationExpired\/title","value":"ONGRegistrationErrorCustomRegistrationExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1customRegistrationExpired\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorCustomRegistrationExpired"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1customRegistrationFailure\/title","value":"ONGRegistrationErrorCustomRegistrationFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError~1customRegistrationFailure\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationErrorCustomRegistrationFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError\/title","value":"ONGRegistrationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRegistrationError\/fragments","value":[{"kind":"identifier","text":"ONGRegistrationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}