{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onguserclient"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onguserclient"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"title":"ONGUserClient","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)ONGUserClient","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/accessToken","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/preferredAuthenticator"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/allAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/appToWebSingleSignOn(withTargetUrl:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticateUser(_:authenticator:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticatedUserProfile()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/canHandleOTPMobileAuthRequest(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/changePin(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregister(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregisterUser(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enroll(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enrollForPushMobileAuth(withDeviceToken:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchImplicitResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handleOTPMobileAuthRequest(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handlePendingPush(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/identityProviders()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticateUser(_:scopes:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticatedUserProfile()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forPushMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/logoutUser(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/nonRegisteredAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingMobileAuthRequest(fromUserInfo:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingPushMobileAuthRequests(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/register(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registerUser(with:scopes:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registeredAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/userProfiles()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/validatePin(withPolicy:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/sharedInstance()"]}],"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/userProfiles()":{"role":"symbol","title":"userProfiles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProfiles"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"List of enrolled users stored locally"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/userProfiles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userProfiles"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/userprofiles()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/fetchResource(_:completion:)":{"role":"symbol","title":"fetchResource(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Perform an authenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediatelly (sychronously)."},{"type":"text","text":" "},{"type":"text","text":"The User needs to be authenticated, otherwise SDK will return the "},{"type":"codeVoice","code":"ONGFetchResourceErrorUserNotAuthenticated"},{"type":"text","text":" error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchResource(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchResource:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/fetchresource(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/implicitlyAuthenticateUser(_:scopes:completion:)":{"role":"symbol","title":"implicitlyAuthenticateUser(_:scopes:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitlyAuthenticateUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scopes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Main entry point into the implicit authentication process."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticateUser(_:scopes:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"implicitlyAuthenticateUser:scopes:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/implicitlyauthenticateuser(_:scopes:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/isUserEnrolled(forMobileAuth:)":{"role":"symbol","title":"isUserEnrolled(forMobileAuth:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserEnrolled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMobileAuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates whenever user is enrolled for mobile authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forMobileAuth:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUserEnrolledForMobileAuth:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/isuserenrolled(formobileauth:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/pendingPushMobileAuthRequests(_:)":{"role":"symbol","title":"pendingPushMobileAuthRequests(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingPushMobileAuthRequests"},{"kind":"text","text":"((["},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":"]?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetches the pending push mobile authentications."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingPushMobileAuthRequests(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pendingPushMobileAuthRequests:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/pendingpushmobileauthrequests(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/isUserEnrolled(forPushMobileAuth:)":{"role":"symbol","title":"isUserEnrolled(forPushMobileAuth:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserEnrolled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPushMobileAuth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates whenever user is enrolled for push mobile authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forPushMobileAuth:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isUserEnrolledForPushMobileAuth:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/isuserenrolled(forpushmobileauth:)"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/accessToken":{"role":"symbol","title":"accessToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns a access token for the currently authenticated user, or nil if no user is currently"},{"type":"text","text":" "},{"type":"text","text":"authenticated."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/accessToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accessToken"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/accesstoken"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/fetchImplicitResource(_:completion:)":{"role":"symbol","title":"fetchImplicitResource(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchImplicitResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Perform an implicitly authenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediatelly (sychronously)."},{"type":"text","text":" "},{"type":"text","text":"The User needs to be authenticated implicitly, otherwise SDK will return the "},{"type":"codeVoice","code":"ONGFetchImplicitResourceErrorUserNotAuthenticatedImplicitly"},{"type":"text","text":" error."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchImplicitResource(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchImplicitResource:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/fetchimplicitresource(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/canHandleOTPMobileAuthRequest(_:)":{"role":"symbol","title":"canHandleOTPMobileAuthRequest(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canHandleOTPMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Indicates if mobile authentication request can be handled by validating request string. The string should be in JSON"},{"type":"text","text":" "},{"type":"text","text":"format and it should contain valid transaction_id and otp code."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/canHandleOTPMobileAuthRequest(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canHandleOTPMobileAuthRequest:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/canhandleotpmobileauthrequest(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/changePin(_:)":{"role":"symbol","title":"changePin(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changePin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGChangePinDelegate","preciseIdentifier":"c:objc(pl)ONGChangePinDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initiates the PIN change sequence."},{"type":"text","text":" "},{"type":"text","text":"If no refresh token is registered then the sequence is cancelled."},{"type":"text","text":" "},{"type":"text","text":"This will invoke a call to the ONGAuthorizationDelegate - (void)askForPinChange:(NSUInteger)pinSize;"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/changePin(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changePin:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/changepin(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/identityProviders()":{"role":"symbol","title":"identityProviders()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identityProviders"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns a set of identity providers."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/identityProviders()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identityProviders"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/identityproviders()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/enrollForPushMobileAuth(withDeviceToken:completion:)":{"role":"symbol","title":"enrollForPushMobileAuth(withDeviceToken:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enrollForPushMobileAuth"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withDeviceToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Enrolls the currently connected user for mobile authentication with Push."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enrollForPushMobileAuth(withDeviceToken:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enrollForPushMobileAuthWithDeviceToken:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/enrollforpushmobileauth(withdevicetoken:completion:)"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/registeredAuthenticators(forUser:)":{"role":"symbol","title":"registeredAuthenticators(forUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registeredAuthenticators"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns a set of registered authenticators."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registeredAuthenticators(forUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registeredAuthenticatorsForUser:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/registeredauthenticators(foruser:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/authenticateUser(_:authenticator:delegate:)":{"role":"symbol","title":"authenticateUser(_:authenticator:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticateUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Main entry point into the authentication process."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticateUser(_:authenticator:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticateUser:authenticator:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/authenticateuser(_:authenticator:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/deregister(_:delegate:)":{"role":"symbol","title":"deregister(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorDeregistrationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticatorDeregistrationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Deregisters an authenticator. Use one of the registered authenticators returned by "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregister(_:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/deregister(_:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/enroll(forMobileAuth:)":{"role":"symbol","title":"enroll(forMobileAuth:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"enroll"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forMobileAuth"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Enrolls the currently connected device for mobile authentication."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enroll(forMobileAuth:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"enrollForMobileAuth:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/enroll(formobileauth:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/logoutUser(_:)":{"role":"symbol","title":"logoutUser(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logoutUser"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Performs a user logout, by invalidating the access token."},{"type":"text","text":" "},{"type":"text","text":"The refresh token and client credentials remain untouched."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/logoutUser(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logoutUser:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/logoutuser(_:)"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/handleOTPMobileAuthRequest(_:delegate:)":{"role":"symbol","title":"handleOTPMobileAuthRequest(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleOTPMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequestDelegate","preciseIdentifier":"c:objc(pl)ONGMobileAuthRequestDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handles mobile authentication done with the one time password (OTP)."},{"type":"text","text":" "},{"type":"text","text":"The client will then fetch the actual encrypted payload and invoke the delegate with the embedded message."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handleOTPMobileAuthRequest(_:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleOTPMobileAuthRequest:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/handleotpmobileauthrequest(_:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/appToWebSingleSignOn(withTargetUrl:completion:)":{"role":"symbol","title":"appToWebSingleSignOn(withTargetUrl:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appToWebSingleSignOn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withTargetUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method allows to take a session from mobile application and extend it to a browser on the same device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/appToWebSingleSignOn(withTargetUrl:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appToWebSingleSignOnWithTargetUrl:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/apptowebsinglesignon(withtargeturl:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/allAuthenticators(forUser:)":{"role":"symbol","title":"allAuthenticators(forUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allAuthenticators"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns a set of both registered and nonregistered authenticators."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/allAuthenticators(forUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allAuthenticatorsForUser:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/allauthenticators(foruser:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/handlePendingPush(_:delegate:)":{"role":"symbol","title":"handlePendingPush(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handlePendingPush"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthRequestDelegate","preciseIdentifier":"c:objc(pl)ONGMobileAuthRequestDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Handles pending push mobile authentication request."},{"type":"text","text":" "},{"type":"text","text":"The client will then fetch the actual encrypted payload and invoke the delegate with the embedded message."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handlePendingPush(_:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handlePendingPushMobileAuthRequest:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/handlependingpush(_:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/preferredAuthenticator":{"role":"symbol","title":"preferredAuthenticator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredAuthenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents preferred authenticator. By default SDK uses PIN as preferred authenticator."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/preferredAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredAuthenticator"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/preferredauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/authenticatedUserProfile()":{"role":"symbol","title":"authenticatedUserProfile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatedUserProfile"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return currently authenticated user."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticatedUserProfile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticatedUserProfile"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/authenticateduserprofile()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/deregisterUser(_:completion:)":{"role":"symbol","title":"deregisterUser(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregisterUser"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Delete user locally and revoke it from token server"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregisterUser(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deregisterUser:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/deregisteruser(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/registerUser(with:scopes:delegate:)":{"role":"symbol","title":"registerUser(with:scopes:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGIdentityProvider","preciseIdentifier":"c:objc(cs)ONGIdentityProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"scopes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRegistrationDelegate","preciseIdentifier":"c:objc(pl)ONGRegistrationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Main entry point into the registration process."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registerUser(with:scopes:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerUserWithIdentityProvider:scopes:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/registeruser(with:scopes:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/implicitlyAuthenticatedUserProfile()":{"role":"symbol","title":"implicitlyAuthenticatedUserProfile()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitlyAuthenticatedUserProfile"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return currently implicitly authenticated user."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticatedUserProfile()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"implicitlyAuthenticatedUserProfile"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/implicitlyauthenticateduserprofile()"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/sharedInstance()":{"role":"symbol","title":"sharedInstance()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharedInstance"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"}],"abstract":[{"type":"text","text":"Access to the initialized and configured instance of the "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":". Before calling this method You have to initialize"},{"type":"text","text":" "},{"type":"text","text":"SDK by calling "},{"type":"codeVoice","code":"-[ONGClientBuilder build]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/sharedInstance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedInstance"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/sharedinstance()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/register(_:delegate:)":{"role":"symbol","title":"register(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorRegistrationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticatorRegistrationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Registers an authenticator. Use one of the non registered authenticators returned by "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" method."},{"type":"text","text":" "},{"type":"text","text":"Registering an authenticator may require user authentication which is handled by the delegate."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/register(_:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerAuthenticator:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/register(_:delegate:)"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/validatePin(withPolicy:completion:)":{"role":"symbol","title":"validatePin(withPolicy:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validatePin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Checks if the pin satisfies all pin policy constraints."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/validatePin(withPolicy:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validatePinWithPolicy:completion:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/validatepin(withpolicy:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/nonRegisteredAuthenticators(forUser:)":{"role":"symbol","title":"nonRegisteredAuthenticators(forUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonRegisteredAuthenticators"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns a set of authenticators which are supported both, client and server side, and are not yet registered."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/nonRegisteredAuthenticators(forUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nonRegisteredAuthenticatorsForUser:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/nonregisteredauthenticators(foruser:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/pendingMobileAuthRequest(fromUserInfo:)":{"role":"symbol","title":"pendingMobileAuthRequest(fromUserInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUserInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parses user info object (from notification that is received by the application) into ONGPendingMobileAuthRequest."},{"type":"text","text":" "},{"type":"text","text":"The returned ONGPendingMobileAuthRequest object should be used to handle received notification "},{"type":"codeVoice","code":"-handlePendingPushMobileAuthRequest:delegate:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingMobileAuthRequest(fromUserInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/pendingmobileauthrequest(fromuserinfo:)"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ONGUserClient"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/accessToken","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/preferredAuthenticator"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/allAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/appToWebSingleSignOn(withTargetUrl:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticateUser(_:authenticator:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/authenticatedUserProfile()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/canHandleOTPMobileAuthRequest(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/changePin(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregister(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregisterUser(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enroll(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/enrollForPushMobileAuth(withDeviceToken:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchImplicitResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/fetchResource(_:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handleOTPMobileAuthRequest(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/handlePendingPush(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/identityProviders()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticateUser(_:scopes:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/implicitlyAuthenticatedUserProfile()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/isUserEnrolled(forPushMobileAuth:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/logoutUser(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/nonRegisteredAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingMobileAuthRequest(fromUserInfo:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingPushMobileAuthRequests(_:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/register(_:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registerUser(with:scopes:delegate:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/registeredAuthenticators(forUser:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/userProfiles()","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/validatePin(withPolicy:completion:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/sharedInstance()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1userProfiles()\/title","value":"userProfiles"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1userProfiles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userProfiles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1fetchResource(_:completion:)\/title","value":"fetchResource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1fetchResource(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchResource:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1implicitlyAuthenticateUser(_:scopes:completion:)\/title","value":"implicitlyAuthenticateUser:scopes:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1implicitlyAuthenticateUser(_:scopes:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"implicitlyAuthenticateUser:scopes:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1isUserEnrolled(forMobileAuth:)\/title","value":"isUserEnrolledForMobileAuth:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1isUserEnrolled(forMobileAuth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isUserEnrolledForMobileAuth:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingPushMobileAuthRequests(_:)\/title","value":"pendingPushMobileAuthRequests:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingPushMobileAuthRequests(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pendingPushMobileAuthRequests:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1isUserEnrolled(forPushMobileAuth:)\/title","value":"isUserEnrolledForPushMobileAuth:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1isUserEnrolled(forPushMobileAuth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isUserEnrolledForPushMobileAuth:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1accessToken\/title","value":"accessToken"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1accessToken\/fragments","value":[{"kind":"identifier","text":"accessToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1fetchImplicitResource(_:completion:)\/title","value":"fetchImplicitResource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1fetchImplicitResource(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchImplicitResource:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1canHandleOTPMobileAuthRequest(_:)\/title","value":"canHandleOTPMobileAuthRequest:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1canHandleOTPMobileAuthRequest(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canHandleOTPMobileAuthRequest:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1changePin(_:)\/title","value":"changePin:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1changePin(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changePin:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1identityProviders()\/title","value":"identityProviders"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1identityProviders()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"identityProviders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1enrollForPushMobileAuth(withDeviceToken:completion:)\/title","value":"enrollForPushMobileAuthWithDeviceToken:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1enrollForPushMobileAuth(withDeviceToken:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enrollForPushMobileAuthWithDeviceToken:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1registeredAuthenticators(forUser:)\/title","value":"registeredAuthenticatorsForUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1registeredAuthenticators(forUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registeredAuthenticatorsForUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1authenticateUser(_:authenticator:delegate:)\/title","value":"authenticateUser:authenticator:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1authenticateUser(_:authenticator:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticateUser:authenticator:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregister(_:delegate:)\/title","value":"deregisterAuthenticator:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregister(_:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1enroll(forMobileAuth:)\/title","value":"enrollForMobileAuth:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1enroll(forMobileAuth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"enrollForMobileAuth:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1logoutUser(_:)\/title","value":"logoutUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1logoutUser(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logoutUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1handleOTPMobileAuthRequest(_:delegate:)\/title","value":"handleOTPMobileAuthRequest:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1handleOTPMobileAuthRequest(_:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleOTPMobileAuthRequest:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1appToWebSingleSignOn(withTargetUrl:completion:)\/title","value":"appToWebSingleSignOnWithTargetUrl:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1appToWebSingleSignOn(withTargetUrl:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"appToWebSingleSignOnWithTargetUrl:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1allAuthenticators(forUser:)\/title","value":"allAuthenticatorsForUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1allAuthenticators(forUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"allAuthenticatorsForUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1handlePendingPush(_:delegate:)\/title","value":"handlePendingPushMobileAuthRequest:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1handlePendingPush(_:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handlePendingPushMobileAuthRequest:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1preferredAuthenticator\/title","value":"preferredAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1preferredAuthenticator\/fragments","value":[{"kind":"identifier","text":"preferredAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1authenticatedUserProfile()\/title","value":"authenticatedUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1authenticatedUserProfile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticatedUserProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregisterUser(_:completion:)\/title","value":"deregisterUser:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregisterUser(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deregisterUser:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1registerUser(with:scopes:delegate:)\/title","value":"registerUserWithIdentityProvider:scopes:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1registerUser(with:scopes:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerUserWithIdentityProvider:scopes:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1implicitlyAuthenticatedUserProfile()\/title","value":"implicitlyAuthenticatedUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1implicitlyAuthenticatedUserProfile()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"implicitlyAuthenticatedUserProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1sharedInstance()\/title","value":"sharedInstance"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1sharedInstance()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sharedInstance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1register(_:delegate:)\/title","value":"registerAuthenticator:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1register(_:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerAuthenticator:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1validatePin(withPolicy:completion:)\/title","value":"validatePinWithPolicy:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1validatePin(withPolicy:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validatePinWithPolicy:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1nonRegisteredAuthenticators(forUser:)\/title","value":"nonRegisteredAuthenticatorsForUser:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1nonRegisteredAuthenticators(forUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nonRegisteredAuthenticatorsForUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingMobileAuthRequest(fromUserInfo:)\/title","value":"pendingMobileAuthRequestFromUserInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingMobileAuthRequest(fromUserInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}