{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/clientAssertionService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}],"title":"PendingMobileAuthRequestsNetworkService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OneginiSDKiOS@objc(cs)PendingMobileAuthRequestsNetworkService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/clientAssertionService":{"role":"symbol","title":"clientAssertionService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAssertionService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientAssertionServiceProtocol","preciseIdentifier":"c:objc(pl)ClientAssertionServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/clientAssertionService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientAssertionService"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/clientassertionservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/init"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService":{"role":"symbol","title":"PendingMobileAuthRequestsNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)":{"role":"symbol","title":"fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPendingPushMobileAuthRequests"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Array","preciseIdentifier":"s:Sa"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchPendingPushMobileAuthRequestsWithClientId:privateKey:uuid:completion:"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/fetchpendingpushmobileauthrequests(clientid:privatekey:uuid:completion:)"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/oAuthSessionModel":{"role":"symbol","title":"oAuthSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/oAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/oauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PendingMobileAuthRequestsNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/pendingmobileauthrequestsnetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PendingMobileAuthRequestsNetworkService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/clientAssertionService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PendingMobileAuthRequestsNetworkService\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1clientAssertionService\/title","value":"clientAssertionService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1clientAssertionService\/fragments","value":[{"kind":"identifier","text":"clientAssertionService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService\/title","value":"PendingMobileAuthRequestsNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService\/fragments","value":[{"kind":"identifier","text":"PendingMobileAuthRequestsNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)\/title","value":"fetchPendingPushMobileAuthRequestsWithClientId:privateKey:uuid:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1fetchPendingPushMobileAuthRequests(clientId:privateKey:uuid:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPendingPushMobileAuthRequestsWithClientId:privateKey:uuid:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1oAuthSessionModel\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1oAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PendingMobileAuthRequestsNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}