{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/revoketokennetworkservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/revoketokennetworkservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/clientAssertionService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeToken(_:clientId:privateKey:uuid:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkService"}],"title":"RevokeTokenNetworkService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OneginiSDKiOS@objc(cs)RevokeTokenNetworkService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/init"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/oAuthSessionModel":{"role":"symbol","title":"oAuthSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/oAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/oauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/revokeToken(_:clientId:privateKey:uuid:completion:)":{"role":"symbol","title":"revokeToken(_:clientId:privateKey:uuid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokeToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeToken(_:clientId:privateKey:uuid:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"revokeToken:clientId:privateKey:uuid:completion:"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/revoketoken(_:clientid:privatekey:uuid:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)":{"role":"symbol","title":"revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokeProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/revokeprofile(_:clientid:privatekey:uuid:token:tokentype:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/clientAssertionService":{"role":"symbol","title":"clientAssertionService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAssertionService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientAssertionServiceProtocol","preciseIdentifier":"c:objc(pl)ClientAssertionServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/clientAssertionService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientAssertionService"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/clientassertionservice"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkServiceProtocol":{"role":"symbol","title":"RevokeTokenNetworkServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService":{"role":"symbol","title":"RevokeTokenNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkService"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"RevokeTokenNetworkService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RevokeTokenNetworkService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/clientAssertionService","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/init","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService\/revokeToken(_:clientId:privateKey:uuid:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1oAuthSessionModel\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1oAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1revokeToken(_:clientId:privateKey:uuid:completion:)\/title","value":"revokeToken:clientId:privateKey:uuid:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1revokeToken(_:clientId:privateKey:uuid:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revokeToken:clientId:privateKey:uuid:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)\/title","value":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1clientAssertionService\/title","value":"clientAssertionService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1clientAssertionService\/fragments","value":[{"kind":"identifier","text":"clientAssertionService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol\/title","value":"RevokeTokenNetworkServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService\/title","value":"RevokeTokenNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}