{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeToken(_:clientId:privateKey:uuid:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}],"title":"RevokeTokenNetworkServiceProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)RevokeTokenNetworkServiceProtocol","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkServiceProtocol/revokeToken(_:clientId:privateKey:uuid:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"revokeToken:clientId:privateKey:uuid:completion:"}],"role":"symbol","title":"revokeToken(_:clientId:privateKey:uuid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokeToken"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeToken(_:clientId:privateKey:uuid:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol\/revoketoken(_:clientid:privatekey:uuid:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkService":{"role":"symbol","title":"RevokeTokenNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkService"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkServiceProtocol/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"}],"role":"symbol","title":"revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"revokeProfile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"tokenType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol\/revokeprofile(_:clientid:privatekey:uuid:token:tokentype:completion:)"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RevokeTokenNetworkServiceProtocol":{"role":"symbol","title":"RevokeTokenNetworkServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/revoketokennetworkserviceprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"RevokeTokenNetworkServiceProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkServiceProtocol\/revokeToken(_:clientId:privateKey:uuid:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RevokeTokenNetworkService"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol~1revokeToken(_:clientId:privateKey:uuid:completion:)\/title","value":"revokeToken:clientId:privateKey:uuid:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol~1revokeToken(_:clientId:privateKey:uuid:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revokeToken:clientId:privateKey:uuid:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService\/title","value":"RevokeTokenNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkService\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol~1revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)\/title","value":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol~1revokeProfile(_:clientId:privateKey:uuid:token:tokenType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"revokeProfile:clientId:privateKey:uuid:token:tokenType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol\/title","value":"RevokeTokenNetworkServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RevokeTokenNetworkServiceProtocol\/fragments","value":[{"kind":"identifier","text":"RevokeTokenNetworkServiceProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}