{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/submitsignaturenetworkservice"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject","doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP","doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP","doc:\/\/com.onegini.OneginiSDKiOS\/SQ","doc:\/\/com.onegini.OneginiSDKiOS\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/clientIdModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthenticationCryptor","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/rsaCryptor","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/submitSignature(mobileAuthenticationAction:completion:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"title":"SubmitSignatureNetworkService","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@OneginiSDKiOS@objc(cs)SubmitSignatureNetworkService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS"]]},"references":{"doc://com.onegini.OneginiSDKiOS/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SQ"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/submitSignature(mobileAuthenticationAction:completion:)":{"role":"symbol","title":"submitSignature(mobileAuthenticationAction:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"submitSignature"},{"kind":"text","text":"("},{"kind":"externalParam","text":"mobileAuthenticationAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationActionDTO","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationActionDTO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/submitSignature(mobileAuthenticationAction:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"submitSignatureWithMobileAuthenticationAction:completion:"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/submitsignature(mobileauthenticationaction:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/init"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService":{"role":"symbol","title":"SubmitSignatureNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/mobileAuthenticationCryptor":{"role":"symbol","title":"mobileAuthenticationCryptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationCryptor","preciseIdentifier":"c:objc(cs)ONGMobileAuthenticationCryptor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthenticationCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthenticationcryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/requestSerializerModel":{"role":"symbol","title":"requestSerializerModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializerModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRequestSerializerModel","preciseIdentifier":"c:objc(cs)ONGRequestSerializerModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/requestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/requestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/rsaCryptor":{"role":"symbol","title":"rsaCryptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rsaCryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGRSACryptor","preciseIdentifier":"c:objc(cs)ONGRSACryptor"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/rsaCryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rsaCryptor"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/rsacryptor"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/mobileAuthModel":{"role":"symbol","title":"mobileAuthModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthModel","preciseIdentifier":"c:objc(cs)ONGMobileAuthModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/mobileauthmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/oAuthSessionModel":{"role":"symbol","title":"oAuthSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"oAuthSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGOAuthSessionModel","preciseIdentifier":"c:objc(cs)ONGOAuthSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/oAuthSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"oAuthSessionModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/oauthsessionmodel"},"doc://com.onegini.OneginiSDKiOS/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/SubmitSignatureNetworkService/clientIdModel":{"role":"symbol","title":"clientIdModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/clientIdModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}],"url":"\/documentation\/oneginisdkios\/submitsignaturenetworkservice\/clientidmodel"},"doc://com.onegini.OneginiSDKiOS/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/SH"},"doc://com.onegini.OneginiSDKiOS/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s28CustomDebugStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s7CVarArgP"},"doc://com.onegini.OneginiSDKiOS/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/s23CustomStringConvertibleP"},"doc://com.onegini.OneginiSDKiOS/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/clientIdModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/mobileAuthenticationCryptor","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/oAuthSessionModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/requestSerializerModel","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/rsaCryptor","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/urlSessionModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/init","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/SubmitSignatureNetworkService\/submitSignature(mobileAuthenticationAction:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.onegini.OneginiSDKiOS\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SubmitSignatureNetworkService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1submitSignature(mobileAuthenticationAction:completion:)\/title","value":"submitSignatureWithMobileAuthenticationAction:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1submitSignature(mobileAuthenticationAction:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"submitSignatureWithMobileAuthenticationAction:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/title","value":"SubmitSignatureNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService\/fragments","value":[{"kind":"identifier","text":"SubmitSignatureNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthenticationCryptor\/title","value":"mobileAuthenticationCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthenticationCryptor\/fragments","value":[{"kind":"identifier","text":"mobileAuthenticationCryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1requestSerializerModel\/title","value":"requestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1requestSerializerModel\/fragments","value":[{"kind":"identifier","text":"requestSerializerModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1rsaCryptor\/title","value":"rsaCryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1rsaCryptor\/fragments","value":[{"kind":"identifier","text":"rsaCryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthModel\/title","value":"mobileAuthModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1mobileAuthModel\/fragments","value":[{"kind":"identifier","text":"mobileAuthModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1oAuthSessionModel\/title","value":"oAuthSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1oAuthSessionModel\/fragments","value":[{"kind":"identifier","text":"oAuthSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1clientIdModel\/title","value":"clientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1SubmitSignatureNetworkService~1clientIdModel\/fragments","value":[{"kind":"identifier","text":"clientIdModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}