{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestServerPublicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPublicKey","preciseIdentifier":"c:objc(cs)ONGPublicKey","text":"ONGPublicKey"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/pgpkeyexchangenetworkservice\/requestserverpublickey(accesstoken:clientpublickey:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/pgpkeyexchangenetworkservice\/requestserverpublickey(accesstoken:clientpublickey:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PGPKeyExchangeNetworkService\/requestServerPublicKey(accessToken:clientPublicKey:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestServerPublicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGPublicKey","preciseIdentifier":"c:objc(cs)ONGPublicKey"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"requestServerPublicKey(accessToken:clientPublicKey:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)PGPKeyExchangeNetworkService(im)requestServerPublicKeyWithAccessToken:clientPublicKey:completion:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PGPKeyExchangeNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PGPKeyExchangeNetworkService/requestServerPublicKey(accessToken:clientPublicKey:completion:)":{"role":"symbol","title":"requestServerPublicKey(accessToken:clientPublicKey:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestServerPublicKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGPublicKey","preciseIdentifier":"c:objc(cs)ONGPublicKey"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PGPKeyExchangeNetworkService\/requestServerPublicKey(accessToken:clientPublicKey:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"}],"url":"\/documentation\/oneginisdkios\/pgpkeyexchangenetworkservice\/requestserverpublickey(accesstoken:clientpublickey:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPublicKey":{"role":"symbol","title":"ONGPublicKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPublicKey"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPublicKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPublicKey"}],"url":"\/documentation\/oneginisdkios\/ongpublickey"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/PGPKeyExchangeNetworkService":{"role":"symbol","title":"PGPKeyExchangeNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPKeyExchangeNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/PGPKeyExchangeNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPKeyExchangeNetworkService"}],"url":"\/documentation\/oneginisdkios\/pgpkeyexchangenetworkservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestServerPublicKeyWithAccessToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"accessToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientPublicKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientPublicKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ONGPublicKey *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)ONGPublicKey#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PGPKeyExchangeNetworkService~1requestServerPublicKey(accessToken:clientPublicKey:completion:)\/title","value":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PGPKeyExchangeNetworkService~1requestServerPublicKey(accessToken:clientPublicKey:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestServerPublicKeyWithAccessToken:clientPublicKey:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPublicKey\/title","value":"ONGPublicKey"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPublicKey\/fragments","value":[{"kind":"identifier","text":"ONGPublicKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PGPKeyExchangeNetworkService\/title","value":"PGPKeyExchangeNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1PGPKeyExchangeNetworkService\/fragments","value":[{"kind":"identifier","text":"PGPKeyExchangeNetworkService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}