{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"basicHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"clientCredentials"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials","text":"ONGClientCredentials"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongbasicauthorizationformatter\/basicheader(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongbasicauthorizationformatter\/basicheader(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBasicAuthorizationFormatter\/basicHeader(with:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"basicHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"basicHeader(with:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGBasicAuthorizationFormatter(cm)basicHeaderWithCredentials:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"basicHeaderWithCredentials:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBasicAuthorizationFormatter"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientCredentials":{"role":"symbol","title":"ONGClientCredentials","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientCredentials"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientCredentials"}],"url":"\/documentation\/oneginisdkios\/ongclientcredentials"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBasicAuthorizationFormatter":{"role":"symbol","title":"ONGBasicAuthorizationFormatter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGBasicAuthorizationFormatter"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBasicAuthorizationFormatter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGBasicAuthorizationFormatter"}],"url":"\/documentation\/oneginisdkios\/ongbasicauthorizationformatter"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGBasicAuthorizationFormatter/basicHeader(with:)":{"role":"symbol","title":"basicHeader(with:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"basicHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGBasicAuthorizationFormatter\/basicHeader(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"basicHeaderWithCredentials:"}],"url":"\/documentation\/oneginisdkios\/ongbasicauthorizationformatter\/basicheader(with:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"basicHeaderWithCredentials:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"basicHeaderWithCredentials:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"basicHeaderWithCredentials:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientCredentials","preciseIdentifier":"c:objc(cs)ONGClientCredentials","text":"ONGClientCredentials"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientCredentials"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientCredentials\/title","value":"ONGClientCredentials"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientCredentials\/fragments","value":[{"kind":"identifier","text":"ONGClientCredentials"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBasicAuthorizationFormatter\/title","value":"ONGBasicAuthorizationFormatter"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBasicAuthorizationFormatter\/fragments","value":[{"kind":"identifier","text":"ONGBasicAuthorizationFormatter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBasicAuthorizationFormatter~1basicHeader(with:)\/title","value":"basicHeaderWithCredentials:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGBasicAuthorizationFormatter~1basicHeader(with:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"basicHeaderWithCredentials:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}