{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipartData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData","text":"ONGMultipartData"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"multipart\/form-data"},{"type":"text","text":" Content-Type header is added automatically."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When you add multipart data to a request the "},{"type":"codeVoice","code":"parametersEncoding"},{"type":"text","text":" property will be neglected."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongresourcerequest\/multipartdata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongresourcerequest\/multipartdata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest\/multipartData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The array of data to send using the "},{"type":"codeVoice","code":"multipart\/form-data"},{"type":"text","text":" content type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipartData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData"},{"kind":"text","text":"]?"}],"title":"multipartData","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGResourceRequest(py)multipartData","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"multipartData"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest/multipartData":{"role":"symbol","title":"multipartData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multipartData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ONGMultipartData","preciseIdentifier":"c:objc(cs)ONGMultipartData"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The array of data to send using the "},{"type":"codeVoice","code":"multipart\/form-data"},{"type":"text","text":" content type."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest\/multipartData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multipartData"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest\/multipartdata"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest":{"role":"symbol","title":"ONGResourceRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceRequest"}],"abstract":[{"type":"text","text":"The object that encapsulates arguments required for performing a network request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceRequest"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMultipartData":{"role":"symbol","title":"ONGMultipartData","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMultipartData"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMultipartData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMultipartData"}],"url":"\/documentation\/oneginisdkios\/ongmultipartdata"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"multipartData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"multipartData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<ONGMultipartData *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"multipartData"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest~1multipartData\/title","value":"multipartData"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest~1multipartData\/fragments","value":[{"kind":"identifier","text":"multipartData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/title","value":"ONGResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/fragments","value":[{"kind":"identifier","text":"ONGResourceRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMultipartData\/title","value":"ONGMultipartData"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMultipartData\/fragments","value":[{"kind":"identifier","text":"ONGMultipartData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}