{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parametersEncoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding","text":"ONGParametersEncoding"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The default value is ONGParametersEncodingJSON."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongresourcerequest\/parametersencoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongresourcerequest\/parametersencoding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest\/parametersEncoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The type of parameters encoding. It affects on how "},{"type":"codeVoice","code":"parameters"},{"type":"text","text":" get appended to the request. Sets the "},{"type":"codeVoice","code":"Content-Type"},{"type":"text","text":" header value:"},{"type":"text","text":" "},{"type":"text","text":"ONGParametersEncodingFormURL - application\/x-www-form-urlencoded"},{"type":"text","text":" "},{"type":"text","text":"ONGParametersEncodingJSON - application\/json"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parametersEncoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding"}],"title":"parametersEncoding","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGResourceRequest(py)parametersEncoding","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"parametersEncoding"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest/parametersEncoding":{"role":"symbol","title":"parametersEncoding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"parametersEncoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding"}],"abstract":[{"type":"text","text":"The type of parameters encoding. It affects on how "},{"type":"codeVoice","code":"parameters"},{"type":"text","text":" get appended to the request. Sets the "},{"type":"codeVoice","code":"Content-Type"},{"type":"text","text":" header value:"},{"type":"text","text":" "},{"type":"text","text":"ONGParametersEncodingFormURL - application\/x-www-form-urlencoded"},{"type":"text","text":" "},{"type":"text","text":"ONGParametersEncodingJSON - application\/json"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest\/parametersEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"parametersEncoding"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest\/parametersencoding"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGParametersEncoding":{"role":"symbol","title":"ONGParametersEncoding","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGParametersEncoding"}],"abstract":[{"type":"text","text":"Supported types of parameters encoding during network request construction."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGParametersEncoding"}],"url":"\/documentation\/oneginisdkios\/ongparametersencoding"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest":{"role":"symbol","title":"ONGResourceRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceRequest"}],"abstract":[{"type":"text","text":"The object that encapsulates arguments required for performing a network request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceRequest"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"parametersEncoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"parametersEncoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGParametersEncoding","preciseIdentifier":"c:@E@ONGParametersEncoding","text":"ONGParametersEncoding"},{"kind":"text","text":" "},{"kind":"identifier","text":"parametersEncoding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest~1parametersEncoding\/title","value":"parametersEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest~1parametersEncoding\/fragments","value":[{"kind":"identifier","text":"parametersEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGParametersEncoding\/title","value":"ONGParametersEncoding"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGParametersEncoding\/fragments","value":[{"kind":"identifier","text":"ONGParametersEncoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/title","value":"ONGResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/fragments","value":[{"kind":"identifier","text":"ONGResourceRequest"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}