{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokensType","preciseIdentifier":"c:@E@ONGSessionTokensType","text":"ONGSessionTokensType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongsessiontokenstype\/accesstoken"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongsessiontokenstype\/accesstoken"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokensType\/accessToken","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokensType","preciseIdentifier":"c:@E@ONGSessionTokensType"}],"title":"accessToken","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@ONGSessionTokensType@ONGSessionTokensTypeAccessToken","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokensTypeAccessToken"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokensType"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGSessionTokensType":{"role":"symbol","title":"ONGSessionTokensType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGSessionTokensType"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokensType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokensType"}],"url":"\/documentation\/oneginisdkios\/ongsessiontokenstype"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGSessionTokensType/accessToken":{"role":"symbol","title":"accessToken","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGSessionTokensType","preciseIdentifier":"c:@E@ONGSessionTokensType"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokensType\/accessToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokensTypeAccessToken"}],"url":"\/documentation\/oneginisdkios\/ongsessiontokenstype\/accesstoken"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGSessionTokensTypeAccessToken"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokensTypeAccessToken"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGSessionTokensTypeAccessToken"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokensType\/title","value":"ONGSessionTokensType"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokensType\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokensType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokensType~1accessToken\/title","value":"ONGSessionTokensTypeAccessToken"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokensType~1accessToken\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokensTypeAccessToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}