{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localDeregistration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongderegistrationerror\/localderegistration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongderegistrationerror\/localderegistration"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeregistrationError\/localDeregistration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user was only deregistered on the device. The device registration has not been removed on the server-side due to a connection problem. This does not pose a problem but you might want to inform the end-user as he might be able to see that he\/she is still registered through a web portal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localDeregistration"}],"title":"ONGDeregistrationError.localDeregistration","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGDeregistrationError@ONGDeregistrationErrorLocalDeregistration","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGDeregistrationErrorLocalDeregistration"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeregistrationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeregistrationError/localDeregistration":{"role":"symbol","title":"ONGDeregistrationError.localDeregistration","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localDeregistration"}],"abstract":[{"type":"text","text":"The user was only deregistered on the device. The device registration has not been removed on the server-side due to a connection problem. This does not pose a problem but you might want to inform the end-user as he might be able to see that he\/she is still registered through a web portal."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeregistrationError\/localDeregistration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGDeregistrationErrorLocalDeregistration"}],"url":"\/documentation\/oneginisdkios\/ongderegistrationerror\/localderegistration"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeregistrationError":{"role":"symbol","title":"ONGDeregistrationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeregistrationError"}],"abstract":[{"type":"text","text":"Error codes in ONGDeregistrationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeregistrationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGDeregistrationError"}],"url":"\/documentation\/oneginisdkios\/ongderegistrationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGDeregistrationErrorLocalDeregistration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGDeregistrationErrorLocalDeregistration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGDeregistrationErrorLocalDeregistration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeregistrationError~1localDeregistration\/title","value":"ONGDeregistrationErrorLocalDeregistration"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeregistrationError~1localDeregistration\/fragments","value":[{"kind":"identifier","text":"ONGDeregistrationErrorLocalDeregistration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeregistrationError\/title","value":"ONGDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeregistrationError\/fragments","value":[{"kind":"identifier","text":"ONGDeregistrationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}