{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenServerEncryptedSessionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFURLSessionManager","preciseIdentifier":"c:objc(cs)AFURLSessionManager"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongurlsessionmodel\/tokenserverencryptedsessionmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongurlsessionmodel\/tokenserverencryptedsessionmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel\/tokenServerEncryptedSessionManager","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenServerEncryptedSessionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFURLSessionManager","preciseIdentifier":"c:objc(cs)AFURLSessionManager"},{"kind":"text","text":"!"}],"title":"tokenServerEncryptedSessionManager","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGURLSessionModel(py)tokenServerEncryptedSessionManager","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"tokenServerEncryptedSessionManager"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGURLSessionModel/tokenServerEncryptedSessionManager":{"role":"symbol","title":"tokenServerEncryptedSessionManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tokenServerEncryptedSessionManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFURLSessionManager","preciseIdentifier":"c:objc(cs)AFURLSessionManager"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel\/tokenServerEncryptedSessionManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tokenServerEncryptedSessionManager"}],"url":"\/documentation\/oneginisdkios\/ongurlsessionmodel\/tokenserverencryptedsessionmanager"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGURLSessionModel":{"role":"symbol","title":"ONGURLSessionModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGURLSessionModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGURLSessionModel"}],"url":"\/documentation\/oneginisdkios\/ongurlsessionmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"tokenServerEncryptedSessionManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tokenServerEncryptedSessionManager"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AFURLSessionManager","preciseIdentifier":"c:objc(cs)AFURLSessionManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"tokenServerEncryptedSessionManager"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel~1tokenServerEncryptedSessionManager\/title","value":"tokenServerEncryptedSessionManager"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel~1tokenServerEncryptedSessionManager\/fragments","value":[{"kind":"identifier","text":"tokenServerEncryptedSessionManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel\/title","value":"ONGURLSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel\/fragments","value":[{"kind":"identifier","text":"ONGURLSessionModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}