{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWT"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":" "},{"kind":"internalParam","text":"payload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/jsonwebtokenservice\/generatejwt(withpayload:privatekey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/jsonwebtokenservice\/generatejwt(withpayload:privatekey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService\/generateJWT(withPayload:privateKey:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"JSONWebTokenServiceProtocol.generateJWT(withPayload:privateKey:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWT"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"generateJWT(withPayload:privateKey:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)JSONWebTokenService(im)generateJWTWithPayload:privateKey:error:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenService":{"role":"symbol","title":"JSONWebTokenService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebTokenService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebTokenService"}],"url":"\/documentation\/oneginisdkios\/jsonwebtokenservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebTokenService/generateJWT(withPayload:privateKey:)":{"role":"symbol","title":"generateJWT(withPayload:privateKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWT"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withPayload"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebTokenService\/generateJWT(withPayload:privateKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}],"url":"\/documentation\/oneginisdkios\/jsonwebtokenservice\/generatejwt(withpayload:privatekey:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"generateJWTWithPayload:privateKey:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateJWTWithPayload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"payload"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateKey:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__SecKey","preciseIdentifier":"c:@S@__SecKey"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"privateKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService\/title","value":"JSONWebTokenService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService\/fragments","value":[{"kind":"identifier","text":"JSONWebTokenService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService~1generateJWT(withPayload:privateKey:)\/title","value":"generateJWTWithPayload:privateKey:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebTokenService~1generateJWT(withPayload:privateKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateJWTWithPayload:privateKey:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}