{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregister"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticatorDeregistrationDelegate","text":"ONGAuthenticatorDeregistrationDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned errors will be within the ONGGenericErrorDomain, ONGAuthenticatorDeregistrationErrorDomain or ONGAuthenticationErrorDomain."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onguserclient\/deregister(_:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onguserclient\/deregister(_:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregister(_:delegate:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deregisters an authenticator. Use one of the registered authenticators returned by "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":" method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorDeregistrationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticatorDeregistrationDelegate"},{"kind":"text","text":")"}],"title":"deregister(_:delegate:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGUserClient(im)deregisterAuthenticator:delegate:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationDelegate":{"role":"symbol","title":"ONGAuthenticatorDeregistrationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorDeregistrationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to deregister authenticator."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/deregister(_:delegate:)":{"role":"symbol","title":"deregister(_:delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deregister"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorDeregistrationDelegate","preciseIdentifier":"c:objc(pl)ONGAuthenticatorDeregistrationDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Deregisters an authenticator. Use one of the registered authenticators returned by "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/deregister(_:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/deregister(_:delegate:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticator":{"role":"symbol","title":"ONGAuthenticator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents an authenticator. Authenticator objects can be obtained using "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deregisterAuthenticator:delegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deregisterAuthenticator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ONGAuthenticatorDeregistrationDelegate>","preciseIdentifier":"c:Qoobjc(pl)ONGAuthenticatorDeregistrationDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationDelegate\/title","value":"ONGAuthenticatorDeregistrationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregister(_:delegate:)\/title","value":"deregisterAuthenticator:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1deregister(_:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deregisterAuthenticator:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/title","value":"ONGAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}