{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUserInfo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] = [:]) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest","text":"ONGPendingMobileAuthRequest"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This should be invoked from the UIApplicationDelegate"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned error will be either within the ONGGenericErrorDomain, ONGAuthenticationErrorDomain or ONGMobileAuthRequestErrorDomain."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onguserclient\/pendingmobileauthrequest(fromuserinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onguserclient\/pendingmobileauthrequest(fromuserinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingMobileAuthRequest(fromUserInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parses user info object (from notification that is received by the application) into ONGPendingMobileAuthRequest."},{"type":"text","text":" "},{"type":"text","text":"The returned ONGPendingMobileAuthRequest object should be used to handle received notification "},{"type":"codeVoice","code":"-handlePendingPushMobileAuthRequest:delegate:"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUserInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":"?"}],"title":"pendingMobileAuthRequest(fromUserInfo:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGUserClient(im)pendingMobileAuthRequestFromUserInfo:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient/pendingMobileAuthRequest(fromUserInfo:)":{"role":"symbol","title":"pendingMobileAuthRequest(fromUserInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pendingMobileAuthRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUserInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Parses user info object (from notification that is received by the application) into ONGPendingMobileAuthRequest."},{"type":"text","text":" "},{"type":"text","text":"The returned ONGPendingMobileAuthRequest object should be used to handle received notification "},{"type":"codeVoice","code":"-handlePendingPushMobileAuthRequest:delegate:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient\/pendingMobileAuthRequest(fromUserInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}],"url":"\/documentation\/oneginisdkios\/onguserclient\/pendingmobileauthrequest(fromuserinfo:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPendingMobileAuthRequest":{"role":"symbol","title":"ONGPendingMobileAuthRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPendingMobileAuthRequest"}],"abstract":[{"type":"text","text":"The class representing pending mobile authentication request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPendingMobileAuthRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPendingMobileAuthRequest"}],"url":"\/documentation\/oneginisdkios\/ongpendingmobileauthrequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"pendingMobileAuthRequestFromUserInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPendingMobileAuthRequest","preciseIdentifier":"c:objc(cs)ONGPendingMobileAuthRequest","text":"ONGPendingMobileAuthRequest"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingMobileAuthRequest(fromUserInfo:)\/title","value":"pendingMobileAuthRequestFromUserInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient~1pendingMobileAuthRequest(fromUserInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pendingMobileAuthRequestFromUserInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPendingMobileAuthRequest\/title","value":"ONGPendingMobileAuthRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPendingMobileAuthRequest\/fragments","value":[{"kind":"identifier","text":"ONGPendingMobileAuthRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}