{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel","text":"ONGURLSessionModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/urlsessionmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/urlsessionmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/urlSessionModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"title":"urlSessionModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)ClientRegistrationNetworkService(py)urlSessionModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGURLSessionModel":{"role":"symbol","title":"ONGURLSessionModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGURLSessionModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGURLSessionModel"}],"url":"\/documentation\/oneginisdkios\/ongurlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService/urlSessionModel":{"role":"symbol","title":"urlSessionModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService\/urlSessionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlSessionModel"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice\/urlsessionmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientRegistrationNetworkService":{"role":"symbol","title":"ClientRegistrationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientRegistrationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}],"url":"\/documentation\/oneginisdkios\/clientregistrationnetworkservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"urlSessionModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGURLSessionModel","preciseIdentifier":"c:objc(cs)ONGURLSessionModel","text":"ONGURLSessionModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"urlSessionModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel\/title","value":"ONGURLSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGURLSessionModel\/fragments","value":[{"kind":"identifier","text":"ONGURLSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1urlSessionModel\/title","value":"urlSessionModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService~1urlSessionModel\/fragments","value":[{"kind":"identifier","text":"urlSessionModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService\/title","value":"ClientRegistrationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientRegistrationNetworkService\/fragments","value":[{"kind":"identifier","text":"ClientRegistrationNetworkService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}