{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinchallenge\/authenticator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinchallenge\/authenticator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/authenticator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authenticator object which authentication challenge was sent to."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"}],"title":"authenticator","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGPinChallenge(py)authenticator","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"authenticator"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge/authenticator":{"role":"symbol","title":"authenticator","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"}],"abstract":[{"type":"text","text":"Authenticator object which authentication challenge was sent to."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge\/authenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticator"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge\/authenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticator":{"role":"symbol","title":"ONGAuthenticator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents an authenticator. Authenticator objects can be obtained using "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge":{"role":"symbol","title":"ONGPinChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinChallenge"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"authenticator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"authenticator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" * "},{"kind":"identifier","text":"authenticator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1authenticator\/title","value":"authenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge~1authenticator\/fragments","value":[{"kind":"identifier","text":"authenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/title","value":"ONGAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/title","value":"ONGPinChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/fragments","value":[{"kind":"identifier","text":"ONGPinChallenge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}