{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAssertionService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientAssertionServiceProtocol","preciseIdentifier":"c:objc(pl)ClientAssertionServiceProtocol","text":"ClientAssertionServiceProtocol"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/customauthfinishauthenticationnetworkservice\/clientassertionservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/customauthfinishauthenticationnetworkservice\/clientassertionservice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationNetworkService\/clientAssertionService","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAssertionService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientAssertionServiceProtocol","preciseIdentifier":"c:objc(pl)ClientAssertionServiceProtocol"},{"kind":"text","text":"?"}],"title":"clientAssertionService","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@OneginiSDKiOS@objc(cs)CustomAuthFinishAuthenticationNetworkService(py)clientAssertionService","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"clientAssertionService"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/CustomAuthFinishAuthenticationNetworkService":{"role":"symbol","title":"CustomAuthFinishAuthenticationNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomAuthFinishAuthenticationNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomAuthFinishAuthenticationNetworkService"}],"url":"\/documentation\/oneginisdkios\/customauthfinishauthenticationnetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ClientAssertionServiceProtocol":{"role":"symbol","title":"ClientAssertionServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientAssertionServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ClientAssertionServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientAssertionServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/clientassertionserviceprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/CustomAuthFinishAuthenticationNetworkService/clientAssertionService":{"role":"symbol","title":"clientAssertionService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientAssertionService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ClientAssertionServiceProtocol","preciseIdentifier":"c:objc(pl)ClientAssertionServiceProtocol"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/CustomAuthFinishAuthenticationNetworkService\/clientAssertionService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientAssertionService"}],"url":"\/documentation\/oneginisdkios\/customauthfinishauthenticationnetworkservice\/clientassertionservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clientAssertionService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientAssertionService"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<ClientAssertionServiceProtocol>","preciseIdentifier":"c:Qoobjc(pl)ClientAssertionServiceProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"clientAssertionService"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1CustomAuthFinishAuthenticationNetworkService\/title","value":"CustomAuthFinishAuthenticationNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1CustomAuthFinishAuthenticationNetworkService\/fragments","value":[{"kind":"identifier","text":"CustomAuthFinishAuthenticationNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientAssertionServiceProtocol\/title","value":"ClientAssertionServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ClientAssertionServiceProtocol\/fragments","value":[{"kind":"identifier","text":"ClientAssertionServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1CustomAuthFinishAuthenticationNetworkService~1clientAssertionService\/title","value":"clientAssertionService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1CustomAuthFinishAuthenticationNetworkService~1clientAssertionService\/fragments","value":[{"kind":"identifier","text":"clientAssertionService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}