{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appToWebSingleSignOnDisabled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/apptowebsinglesignondisabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/apptowebsinglesignondisabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError\/appToWebSingleSignOnDisabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Token Server configuration does not allow you to use single sign on."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appToWebSingleSignOnDisabled"}],"title":"ONGAppToWebSingleSignOnError.appToWebSingleSignOnDisabled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGAppToWebSingleSignOnError@ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAppToWebSingleSignOnError/appToWebSingleSignOnDisabled":{"role":"symbol","title":"ONGAppToWebSingleSignOnError.appToWebSingleSignOnDisabled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appToWebSingleSignOnDisabled"}],"abstract":[{"type":"text","text":"The Token Server configuration does not allow you to use single sign on."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError\/appToWebSingleSignOnDisabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"}],"url":"\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/apptowebsinglesignondisabled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAppToWebSingleSignOnError":{"role":"symbol","title":"ONGAppToWebSingleSignOnError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}],"url":"\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError~1appToWebSingleSignOnDisabled\/title","value":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError~1appToWebSingleSignOnDisabled\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorAppToWebSingleSignOnDisabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError\/title","value":"ONGAppToWebSingleSignOnError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}