{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotAuthenticated"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/usernotauthenticated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/usernotauthenticated"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError\/userNotAuthenticated","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No user is currently authenticated, possibly due to the fact that the access token has expired. A user must be authenticated in order to use single sign on feature."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotAuthenticated"}],"title":"ONGAppToWebSingleSignOnError.userNotAuthenticated","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGAppToWebSingleSignOnError@ONGAppToWebSingleSignOnErrorUserNotAuthenticated","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAppToWebSingleSignOnError/userNotAuthenticated":{"role":"symbol","title":"ONGAppToWebSingleSignOnError.userNotAuthenticated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userNotAuthenticated"}],"abstract":[{"type":"text","text":"No user is currently authenticated, possibly due to the fact that the access token has expired. A user must be authenticated in order to use single sign on feature."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError\/userNotAuthenticated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"}],"url":"\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror\/usernotauthenticated"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAppToWebSingleSignOnError":{"role":"symbol","title":"ONGAppToWebSingleSignOnError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAppToWebSingleSignOnError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}],"url":"\/documentation\/oneginisdkios\/ongapptowebsinglesignonerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError~1userNotAuthenticated\/title","value":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError~1userNotAuthenticated\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnErrorUserNotAuthenticated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError\/title","value":"ONGAppToWebSingleSignOnError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAppToWebSingleSignOnError\/fragments","value":[{"kind":"identifier","text":"ONGAppToWebSingleSignOnError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}