{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitAuthentication"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongerrorcontext\/implicitauthentication"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongerrorcontext\/implicitauthentication"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext\/implicitAuthentication","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitAuthentication"}],"title":"ONGErrorContext.implicitAuthentication","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGErrorContext@ONGErrorContextImplicitAuthentication","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextImplicitAuthentication"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext/implicitAuthentication":{"role":"symbol","title":"ONGErrorContext.implicitAuthentication","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"implicitAuthentication"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext\/implicitAuthentication","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextImplicitAuthentication"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext\/implicitauthentication"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext":{"role":"symbol","title":"ONGErrorContext","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContext"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGErrorContextImplicitAuthentication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextImplicitAuthentication"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGErrorContextImplicitAuthentication"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext~1implicitAuthentication\/title","value":"ONGErrorContextImplicitAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext~1implicitAuthentication\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextImplicitAuthentication"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/title","value":"ONGErrorContext"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/fragments","value":[{"kind":"identifier","text":"ONGErrorContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}