{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationEnrollment"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongerrorcontext\/mobileauthenticationenrollment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongerrorcontext\/mobileauthenticationenrollment"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext\/mobileAuthenticationEnrollment","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationEnrollment"}],"title":"ONGErrorContext.mobileAuthenticationEnrollment","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGErrorContext@ONGErrorContextMobileAuthenticationEnrollment","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextMobileAuthenticationEnrollment"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext/mobileAuthenticationEnrollment":{"role":"symbol","title":"ONGErrorContext.mobileAuthenticationEnrollment","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationEnrollment"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext\/mobileAuthenticationEnrollment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContextMobileAuthenticationEnrollment"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext\/mobileauthenticationenrollment"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext":{"role":"symbol","title":"ONGErrorContext","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContext"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGErrorContextMobileAuthenticationEnrollment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextMobileAuthenticationEnrollment"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGErrorContextMobileAuthenticationEnrollment"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext~1mobileAuthenticationEnrollment\/title","value":"ONGErrorContextMobileAuthenticationEnrollment"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext~1mobileAuthenticationEnrollment\/fragments","value":[{"kind":"identifier","text":"ONGErrorContextMobileAuthenticationEnrollment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/title","value":"ONGErrorContext"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/fragments","value":[{"kind":"identifier","text":"ONGErrorContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}