{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWKS"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withEcPublicKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"publicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/jsonwebkeysetserviceprotocol\/generatejwks(withecpublickey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/jsonwebkeysetserviceprotocol\/generatejwks(withecpublickey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol\/generateJWKS(withEcPublicKey:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"generateJWKSWithEcPublicKey:error:"}],"role":"symbol","title":"generateJWKS(withEcPublicKey:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWKS"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withEcPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"symbolKind":"method","externalID":"c:objc(pl)JSONWebKeySetServiceProtocol(im)generateJWKSWithEcPublicKey:error:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebKeySetServiceProtocol":{"role":"symbol","title":"JSONWebKeySetServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}],"url":"\/documentation\/oneginisdkios\/jsonwebkeysetserviceprotocol"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/JSONWebKeySetServiceProtocol/generateJWKS(withEcPublicKey:)":{"navigatorTitle":[{"kind":"identifier","text":"generateJWKSWithEcPublicKey:error:"}],"role":"symbol","title":"generateJWKS(withEcPublicKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateJWKS"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withEcPublicKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/JSONWebKeySetServiceProtocol\/generateJWKS(withEcPublicKey:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/jsonwebkeysetserviceprotocol\/generatejwks(withecpublickey:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"generateJWKSWithEcPublicKey:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateJWKSWithEcPublicKey:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateJWKSWithEcPublicKey:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__SecKey","preciseIdentifier":"c:@S@__SecKey"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"publicKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol\/title","value":"JSONWebKeySetServiceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol\/fragments","value":[{"kind":"identifier","text":"JSONWebKeySetServiceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol~1generateJWKS(withEcPublicKey:)\/title","value":"generateJWKSWithEcPublicKey:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1JSONWebKeySetServiceProtocol~1generateJWKS(withEcPublicKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateJWKSWithEcPublicKey:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}