{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyPairGenerationErrorKeyPairAlreadyExists"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongkeychainmanagererrorcode\/keypairgenerationerrorkeypairalreadyexists"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongkeychainmanagererrorcode\/keypairgenerationerrorkeypairalreadyexists"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManagerErrorCode\/keyPairGenerationErrorKeyPairAlreadyExists","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyPairGenerationErrorKeyPairAlreadyExists"}],"title":"ONGKeychainManagerErrorCode.keyPairGenerationErrorKeyPairAlreadyExists","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGKeychainManagerErrorCode@ONGKeyPairGenerationErrorKeyPairAlreadyExists","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManagerErrorCode"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManagerErrorCode/keyPairGenerationErrorKeyPairAlreadyExists":{"role":"symbol","title":"ONGKeychainManagerErrorCode.keyPairGenerationErrorKeyPairAlreadyExists","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyPairGenerationErrorKeyPairAlreadyExists"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManagerErrorCode\/keyPairGenerationErrorKeyPairAlreadyExists","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanagererrorcode\/keypairgenerationerrorkeypairalreadyexists"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGKeychainManagerErrorCode":{"role":"symbol","title":"ONGKeychainManagerErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGKeychainManagerErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGKeychainManagerErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGKeychainManagerErrorCode"}],"url":"\/documentation\/oneginisdkios\/ongkeychainmanagererrorcode"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManagerErrorCode~1keyPairGenerationErrorKeyPairAlreadyExists\/title","value":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManagerErrorCode~1keyPairGenerationErrorKeyPairAlreadyExists\/fragments","value":[{"kind":"identifier","text":"ONGKeyPairGenerationErrorKeyPairAlreadyExists"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManagerErrorCode\/title","value":"ONGKeychainManagerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGKeychainManagerErrorCode\/fragments","value":[{"kind":"identifier","text":"ONGKeychainManagerErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}