{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCreatedPin"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge","text":"ONGCreatePinChallenge"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallengesender\/respond(withcreatedpin:challenge:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongcreatepinchallengesender\/respond(withcreatedpin:challenge:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/respond(withCreatedPin:challenge:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method providing the PIN to the SDK."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}],"role":"symbol","title":"respond(withCreatedPin:challenge:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCreatedPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)ONGCreatePinChallengeSender(im)respondWithCreatedPin:challenge:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallenge":{"role":"symbol","title":"ONGCreatePinChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallenge"}],"abstract":[{"type":"text","text":"Represents create PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallenge"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallenge"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallengeSender":{"role":"symbol","title":"ONGCreatePinChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCreatePinChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to create PIN challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongcreatepinchallengesender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCreatePinChallengeSender/respond(withCreatedPin:challenge:)":{"navigatorTitle":[{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}],"role":"symbol","title":"respond(withCreatedPin:challenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"respond"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCreatedPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method providing the PIN to the SDK."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallengeSender\/respond(withCreatedPin:challenge:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongcreatepinchallengesender\/respond(withcreatedpin:challenge:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"respondWithCreatedPin:challenge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"respondWithCreatedPin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"pin"},{"kind":"text","text":" "},{"kind":"identifier","text":"challenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCreatePinChallenge","preciseIdentifier":"c:objc(cs)ONGCreatePinChallenge","text":"ONGCreatePinChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge\/title","value":"ONGCreatePinChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallenge\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallenge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender\/title","value":"ONGCreatePinChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGCreatePinChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1respond(withCreatedPin:challenge:)\/title","value":"respondWithCreatedPin:challenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCreatePinChallengeSender~1respond(withCreatedPin:challenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"respondWithCreatedPin:challenge:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}