{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enrollmentNotAvailable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/enrollmentnotavailable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/enrollmentnotavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/enrollmentNotAvailable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Mobile authentication feature is disabled in the Token Server configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enrollmentNotAvailable"}],"title":"ONGMobileAuthEnrollmentError.enrollmentNotAvailable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGMobileAuthEnrollmentError@ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/enrollmentNotAvailable":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.enrollmentNotAvailable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"enrollmentNotAvailable"}],"abstract":[{"type":"text","text":"The Mobile authentication feature is disabled in the Token Server configuration."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/enrollmentNotAvailable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/enrollmentnotavailable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError":{"role":"symbol","title":"ONGMobileAuthEnrollmentError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthEnrollmentErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1enrollmentNotAvailable\/title","value":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1enrollmentNotAvailable\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorEnrollmentNotAvailable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/title","value":"ONGMobileAuthEnrollmentError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}