{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAlreadyEnrolled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/useralreadyenrolled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/useralreadyenrolled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userAlreadyEnrolled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The user is already enrolled for mobile authentication on another device."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAlreadyEnrolled"}],"title":"ONGMobileAuthEnrollmentError.userAlreadyEnrolled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGMobileAuthEnrollmentError@ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError/userAlreadyEnrolled":{"role":"symbol","title":"ONGMobileAuthEnrollmentError.userAlreadyEnrolled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAlreadyEnrolled"}],"abstract":[{"type":"text","text":"The user is already enrolled for mobile authentication on another device."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError\/userAlreadyEnrolled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror\/useralreadyenrolled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError":{"role":"symbol","title":"ONGMobileAuthEnrollmentError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthEnrollmentErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userAlreadyEnrolled\/title","value":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError~1userAlreadyEnrolled\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentErrorUserAlreadyEnrolled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/title","value":"ONGMobileAuthEnrollmentError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}