{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge","text":"ONGPinChallenge"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinchallengesender\/cancel(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinchallengesender\/cancel(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallengeSender\/cancel(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method to cancel challenge"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:"}],"role":"symbol","title":"cancel(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)ONGPinChallengeSender(im)cancelChallenge:","required":true,"modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallengeSender"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallengeSender":{"role":"symbol","title":"ONGPinChallengeSender","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallengeSender"}],"abstract":[{"type":"text","text":"Protocol describing SDK object waiting for response to authentication with PIN challenge."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallengeSender","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinChallengeSender"}],"url":"\/documentation\/oneginisdkios\/ongpinchallengesender"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallengeSender/cancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cancelChallenge:"}],"role":"symbol","title":"cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Method to cancel challenge"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallengeSender\/cancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/oneginisdkios\/ongpinchallengesender\/cancel(_:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinChallenge":{"role":"symbol","title":"ONGPinChallenge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinChallenge"}],"abstract":[{"type":"text","text":"Represents authentication with PIN challenge. It provides all information about the challenge and a sender awaiting for a response."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinChallenge"}],"url":"\/documentation\/oneginisdkios\/ongpinchallenge"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cancelChallenge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancelChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinChallenge","preciseIdentifier":"c:objc(cs)ONGPinChallenge","text":"ONGPinChallenge"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallengeSender\/title","value":"ONGPinChallengeSender"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallengeSender\/fragments","value":[{"kind":"identifier","text":"ONGPinChallengeSender"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallengeSender~1cancel(_:)\/title","value":"cancelChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallengeSender~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/title","value":"ONGPinChallenge"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinChallenge\/fragments","value":[{"kind":"identifier","text":"ONGPinChallenge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}