{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatorDeregistrationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError","preciseIdentifier":"c:@E@ONGAuthenticatorDeregistrationError","text":"ONGAuthenticatorDeregistrationError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/authenticatorderegistrationerror(withcode:underlyingerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/authenticatorderegistrationerror(withcode:underlyingerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/authenticatorDeregistrationError(withCode:underlyingError:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatorDeregistrationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorDeregistrationError","preciseIdentifier":"c:@E@ONGAuthenticatorDeregistrationError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"authenticatorDeregistrationError(withCode:underlyingError:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)authenticatorDeregistrationErrorWithCode:underlyingError:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"authenticatorDeregistrationErrorWithCode:underlyingError:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorDeregistrationError":{"role":"symbol","title":"ONGAuthenticatorDeregistrationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"abstract":[{"type":"text","text":"Error codes in ONGAuthenticatorDeregistrationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorderegistrationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/authenticatorDeregistrationError(withCode:underlyingError:)":{"role":"symbol","title":"authenticatorDeregistrationError(withCode:underlyingError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticatorDeregistrationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticatorDeregistrationError","preciseIdentifier":"c:@E@ONGAuthenticatorDeregistrationError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/authenticatorDeregistrationError(withCode:underlyingError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticatorDeregistrationErrorWithCode:underlyingError:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/authenticatorderegistrationerror(withcode:underlyingerror:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticatorDeregistrationErrorWithCode:underlyingError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"authenticatorDeregistrationErrorWithCode:underlyingError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authenticatorDeregistrationErrorWithCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorDeregistrationError","preciseIdentifier":"c:@E@ONGAuthenticatorDeregistrationError","text":"ONGAuthenticatorDeregistrationError"},{"kind":"text","text":")"},{"kind":"internalParam","text":"errorCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlyingError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"underlyingError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/title","value":"ONGAuthenticatorDeregistrationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorDeregistrationError\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorDeregistrationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1authenticatorDeregistrationError(withCode:underlyingError:)\/title","value":"authenticatorDeregistrationErrorWithCode:underlyingError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1authenticatorDeregistrationError(withCode:underlyingError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"authenticatorDeregistrationErrorWithCode:underlyingError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}