{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customAuthenticatorError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":" "},{"kind":"internalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus","text":"ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/customauthenticatorerror(fromnetworkerror:status:authenticator:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/customauthenticatorerror(fromnetworkerror:status:authenticator:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customAuthenticatorError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)":{"role":"symbol","title":"customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customAuthenticatorError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/customauthenticatorerror(fromnetworkerror:status:authenticator:swifterrorresponse:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticator":{"role":"symbol","title":"ONGAuthenticator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents an authenticator. Authenticator objects can be obtained using "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ErrorResponse":{"role":"symbol","title":"ErrorResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorResponse"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorResponse"}],"url":"\/documentation\/oneginisdkios\/errorresponse"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGHTTPStatus":{"role":"symbol","title":"ONGHTTPStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGHTTPStatus"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGHTTPStatus"}],"url":"\/documentation\/oneginisdkios\/onghttpstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"customAuthenticatorErrorFromNetworkError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":" "},{"kind":"identifier","text":"status:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus","text":"ONGHTTPStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"statusCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftErrorResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)\/title","value":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1customAuthenticatorError(fromNetworkError:status:authenticator:swiftErrorResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"customAuthenticatorErrorFromNetworkError:status:authenticator:swiftErrorResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/title","value":"ONGAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/title","value":"ErrorResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/fragments","value":[{"kind":"identifier","text":"ErrorResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGHTTPStatus\/title","value":"ONGHTTPStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGHTTPStatus\/fragments","value":[{"kind":"identifier","text":"ONGHTTPStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}