{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRegistrationRequestNetworkError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/customregistrationrequestnetworkerror(_:statuscode:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/customregistrationrequestnetworkerror(_:statuscode:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"}],"role":"symbol","title":"customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRegistrationRequestNetworkError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:","extendedModule":"OneginiSDKiOS","modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ErrorResponse":{"role":"symbol","title":"ErrorResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorResponse"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorResponse"}],"url":"\/documentation\/oneginisdkios\/errorresponse"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)":{"role":"symbol","title":"customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customRegistrationRequestNetworkError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/customregistrationrequestnetworkerror(_:statuscode:swifterrorresponse:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"customRegistrationRequestNetworkError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"statusCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftErrorResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/title","value":"ErrorResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/fragments","value":[{"kind":"identifier","text":"ErrorResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)\/title","value":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1customRegistrationRequestNetworkError(_:statusCode:swiftErrorResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"customRegistrationRequestNetworkError:statusCode:swiftErrorResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}