{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","preciseIdentifier":"c:@E@ONGGenericError","text":"ONGGenericError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/genericerror(withcode:context:underlyingerror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/genericerror(withcode:context:underlyingerror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/genericError(withCode:context:underlyingError:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGGenericError","preciseIdentifier":"c:@E@ONGGenericError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"title":"genericError(withCode:context:underlyingError:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)genericErrorWithCode:context:underlyingError:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"genericErrorWithCode:context:underlyingError:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGGenericError":{"role":"symbol","title":"ONGGenericError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGGenericError"}],"abstract":[{"type":"text","text":"Error codes in ONGGenericErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGGenericError"}],"url":"\/documentation\/oneginisdkios\/onggenericerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGErrorContext":{"role":"symbol","title":"ONGErrorContext","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGErrorContext"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGErrorContext"}],"url":"\/documentation\/oneginisdkios\/ongerrorcontext"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/genericError(withCode:context:underlyingError:)":{"role":"symbol","title":"genericError(withCode:context:underlyingError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"genericError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGGenericError","preciseIdentifier":"c:@E@ONGGenericError"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"underlyingError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/genericError(withCode:context:underlyingError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"genericErrorWithCode:context:underlyingError:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/genericerror(withcode:context:underlyingerror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"genericErrorWithCode:context:underlyingError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"genericErrorWithCode:context:underlyingError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"genericErrorWithCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGGenericError","preciseIdentifier":"c:@E@ONGGenericError","text":"ONGGenericError"},{"kind":"text","text":")"},{"kind":"internalParam","text":"code"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGErrorContext","preciseIdentifier":"c:@E@ONGErrorContext","text":"ONGErrorContext"},{"kind":"text","text":")"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlyingError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"underlyingError"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/title","value":"ONGGenericError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGGenericError\/fragments","value":[{"kind":"identifier","text":"ONGGenericError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/title","value":"ONGErrorContext"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGErrorContext\/fragments","value":[{"kind":"identifier","text":"ONGErrorContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1genericError(withCode:context:underlyingError:)\/title","value":"genericErrorWithCode:context:underlyingError:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1genericError(withCode:context:underlyingError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"genericErrorWithCode:context:underlyingError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}