{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":" "},{"kind":"internalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","preciseIdentifier":"c:@E@ONGMobileAuthEnrollmentError","text":"ONGMobileAuthEnrollmentError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/mobileauthenticationerror(withcode:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/mobileauthenticationerror(withcode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/mobileAuthenticationError(withCode:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationErrorWithCode:"}],"role":"symbol","title":"mobileAuthenticationError(withCode:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthEnrollmentError","preciseIdentifier":"c:@E@ONGMobileAuthEnrollmentError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)mobileAuthenticationErrorWithCode:","extendedModule":"OneginiSDKiOS","modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthEnrollmentError":{"role":"symbol","title":"ONGMobileAuthEnrollmentError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthEnrollmentErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenrollmenterror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/mobileAuthenticationError(withCode:)":{"role":"symbol","title":"mobileAuthenticationError(withCode:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthenticationError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthEnrollmentError","preciseIdentifier":"c:@E@ONGMobileAuthEnrollmentError"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/mobileAuthenticationError(withCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthenticationErrorWithCode:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/mobileauthenticationerror(withcode:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"mobileAuthenticationErrorWithCode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mobileAuthenticationErrorWithCode:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mobileAuthenticationErrorWithCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthEnrollmentError","preciseIdentifier":"c:@E@ONGMobileAuthEnrollmentError","text":"ONGMobileAuthEnrollmentError"},{"kind":"text","text":")"},{"kind":"internalParam","text":"code"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/title","value":"ONGMobileAuthEnrollmentError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthEnrollmentError\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthEnrollmentError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1mobileAuthenticationError(withCode:)\/title","value":"mobileAuthenticationErrorWithCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1mobileAuthenticationError(withCode:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mobileAuthenticationErrorWithCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}