{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthAnswerError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mobileAuthMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"method"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod","text":"ONGMobileAuthenticationMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus","text":"ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile","text":"ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/mobileauthanswererror(fromnetworkerror:mobileauthmethod:statuscode:userprofile:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/onginternalerror\/mobileauthanswererror(fromnetworkerror:mobileauthmethod:statuscode:userprofile:swifterrorresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"}],"role":"symbol","title":"mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthAnswerError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mobileAuthMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"symbolKind":"method","externalID":"c:objc(cs)ONGInternalError(cm)mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:","extendedModule":"OneginiSDKiOS","modules":[{"name":"OneginiSDKiOS"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthenticationMethod":{"role":"symbol","title":"ONGMobileAuthenticationMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthenticationmethod"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError/mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)":{"role":"symbol","title":"mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthAnswerError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromNetworkError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mobileAuthMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"swiftErrorResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError\/mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"}],"url":"\/documentation\/oneginisdkios\/onginternalerror\/mobileauthanswererror(fromnetworkerror:mobileauthmethod:statuscode:userprofile:swifterrorresponse:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserProfile":{"role":"symbol","title":"ONGUserProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserProfile"}],"abstract":[{"type":"text","text":"Object representing the user profile."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserProfile"}],"url":"\/documentation\/oneginisdkios\/onguserprofile"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGHTTPStatus":{"role":"symbol","title":"ONGHTTPStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGHTTPStatus"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGHTTPStatus"}],"url":"\/documentation\/oneginisdkios\/onghttpstatus"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGInternalError":{"role":"symbol","title":"ONGInternalError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGInternalError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGInternalError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGInternalError"}],"url":"\/documentation\/oneginisdkios\/onginternalerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ErrorResponse":{"role":"symbol","title":"ErrorResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorResponse"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorResponse"}],"url":"\/documentation\/oneginisdkios\/errorresponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mobileAuthAnswerErrorFromNetworkError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"networkError"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobileAuthMethod:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthenticationMethod","preciseIdentifier":"c:@E@ONGMobileAuthenticationMethod","text":"ONGMobileAuthenticationMethod"},{"kind":"text","text":")"},{"kind":"internalParam","text":"method"},{"kind":"text","text":" "},{"kind":"identifier","text":"statusCode:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGHTTPStatus","preciseIdentifier":"c:@E@ONGHTTPStatus","text":"ONGHTTPStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"statusCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"userProfile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile","text":"ONGUserProfile"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userProfile"},{"kind":"text","text":" "},{"kind":"identifier","text":"swiftErrorResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ErrorResponse","preciseIdentifier":"c:@M@OneginiSDKiOS@objc(cs)ErrorResponse","text":"ErrorResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"errorResponse"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/title","value":"ONGMobileAuthenticationMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthenticationMethod\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthenticationMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)\/title","value":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError~1mobileAuthAnswerError(fromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"mobileAuthAnswerErrorFromNetworkError:mobileAuthMethod:statusCode:userProfile:swiftErrorResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserProfile\/title","value":"ONGUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserProfile\/fragments","value":[{"kind":"identifier","text":"ONGUserProfile"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGHTTPStatus\/title","value":"ONGHTTPStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGHTTPStatus\/fragments","value":[{"kind":"identifier","text":"ONGHTTPStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/title","value":"ONGInternalError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGInternalError\/fragments","value":[{"kind":"identifier","text":"ONGInternalError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/title","value":"ErrorResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ErrorResponse\/fragments","value":[{"kind":"identifier","text":"ErrorResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}