{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCreateLoginTokenRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"targetURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/apptowebsinglesignonnetworkservice\/sendcreatelogintokenrequest(targeturl:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/apptowebsinglesignonnetworkservice\/sendcreatelogintokenrequest(targeturl:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppToWebSingleSignOnNetworkService\/sendCreateLoginTokenRequest(targetURL:completion:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCreateLoginTokenRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"targetURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"sendCreateLoginTokenRequest(targetURL:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)AppToWebSingleSignOnNetworkService(im)sendCreateLoginTokenRequestWithTargetURL:completion:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"sendCreateLoginTokenRequestWithTargetURL:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppToWebSingleSignOnNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppToWebSingleSignOnNetworkService/sendCreateLoginTokenRequest(targetURL:completion:)":{"role":"symbol","title":"sendCreateLoginTokenRequest(targetURL:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCreateLoginTokenRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"targetURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppToWebSingleSignOnNetworkService\/sendCreateLoginTokenRequest(targetURL:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendCreateLoginTokenRequestWithTargetURL:completion:"}],"url":"\/documentation\/oneginisdkios\/apptowebsinglesignonnetworkservice\/sendcreatelogintokenrequest(targeturl:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppToWebSingleSignOnNetworkService":{"role":"symbol","title":"AppToWebSingleSignOnNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppToWebSingleSignOnNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppToWebSingleSignOnNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppToWebSingleSignOnNetworkService"}],"url":"\/documentation\/oneginisdkios\/apptowebsinglesignonnetworkservice"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendCreateLoginTokenRequestWithTargetURL:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendCreateLoginTokenRequestWithTargetURL:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendCreateLoginTokenRequestWithTargetURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"targetURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSURL *, NSString *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSURL#*$objc(cs)NSString#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppToWebSingleSignOnNetworkService~1sendCreateLoginTokenRequest(targetURL:completion:)\/title","value":"sendCreateLoginTokenRequestWithTargetURL:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppToWebSingleSignOnNetworkService~1sendCreateLoginTokenRequest(targetURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendCreateLoginTokenRequestWithTargetURL:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppToWebSingleSignOnNetworkService\/title","value":"AppToWebSingleSignOnNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppToWebSingleSignOnNetworkService\/fragments","value":[{"kind":"identifier","text":"AppToWebSingleSignOnNetworkService"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}