{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegister"},{"kind":"text","text":" "},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userProfile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile","text":"ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":" "},{"kind":"internalParam","text":"customAuthInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo","text":"ONGCustomInfo"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorregistrationdelegate\/userclient(_:didregister:foruser:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticatorregistrationdelegate\/userclient(_:didregister:foruser:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorRegistrationDelegate\/userClient(_:didRegister:forUser:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Method called when authenticator registration is completed with success."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"title":"userClient(_:didRegister:forUser:info:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)ONGAuthenticatorRegistrationDelegate(im)userClient:didRegisterAuthenticator:forUser:info:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"userClient:didRegisterAuthenticator:forUser:info:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorRegistrationDelegate"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGCustomInfo":{"role":"symbol","title":"ONGCustomInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGCustomInfo"}],"abstract":[{"type":"text","text":"The class representing Custom Authenticator related response from Extension Engine."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGCustomInfo"}],"url":"\/documentation\/oneginisdkios\/ongcustominfo"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticator":{"role":"symbol","title":"ONGAuthenticator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticator"}],"abstract":[{"type":"text","text":"Represents an authenticator. Authenticator objects can be obtained using "},{"type":"codeVoice","code":"ONGUserClient"},{"type":"text","text":" "},{"type":"codeVoice","code":"nonRegisteredAuthenticatorsForUser:"},{"type":"text","text":" or"},{"type":"text","text":" "},{"type":"codeVoice","code":"registeredAuthenticatorsForUser:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticator"}],"url":"\/documentation\/oneginisdkios\/ongauthenticator"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorRegistrationDelegate/userClient(_:didRegister:forUser:info:)":{"role":"symbol","title":"userClient(_:didRegister:forUser:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userClient"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegister"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Method called when authenticator registration is completed with success."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorRegistrationDelegate\/userClient(_:didRegister:forUser:info:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userClient:didRegisterAuthenticator:forUser:info:"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorregistrationdelegate\/userclient(_:didregister:foruser:info:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticatorRegistrationDelegate":{"role":"symbol","title":"ONGAuthenticatorRegistrationDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticatorRegistrationDelegate"}],"abstract":[{"type":"text","text":"Protocol describing interface for objects implementing methods required to register authenticator."},{"type":"text","text":" "},{"type":"text","text":"All invocations are performed on the main queue."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticatorRegistrationDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticatorRegistrationDelegate"}],"url":"\/documentation\/oneginisdkios\/ongauthenticatorregistrationdelegate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserClient":{"role":"symbol","title":"ONGUserClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserClient"}],"abstract":[{"type":"text","text":"This is the main entry point into the SDK."},{"type":"text","text":" "},{"type":"text","text":"The public API of the SDK consists of this client and an authorization delegate."},{"type":"text","text":" "},{"type":"text","text":"The client must be instantiated early in the App lifecycle and thereafter only referred to by it’s shared instance."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserClient"}],"url":"\/documentation\/oneginisdkios\/onguserclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGUserProfile":{"role":"symbol","title":"ONGUserProfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGUserProfile"}],"abstract":[{"type":"text","text":"Object representing the user profile."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGUserProfile"}],"url":"\/documentation\/oneginisdkios\/onguserprofile"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userClient:didRegisterAuthenticator:forUser:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didRegisterAuthenticator:forUser:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userClient:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserClient","preciseIdentifier":"c:objc(cs)ONGUserClient","text":"ONGUserClient"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userClient"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterAuthenticator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticator","preciseIdentifier":"c:objc(cs)ONGAuthenticator","text":"ONGAuthenticator"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authenticator"},{"kind":"text","text":" "},{"kind":"identifier","text":"forUser:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGUserProfile","preciseIdentifier":"c:objc(cs)ONGUserProfile","text":"ONGUserProfile"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userProfile"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGCustomInfo","preciseIdentifier":"c:objc(cs)ONGCustomInfo","text":"ONGCustomInfo"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customAuthInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomInfo\/title","value":"ONGCustomInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGCustomInfo\/fragments","value":[{"kind":"identifier","text":"ONGCustomInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/title","value":"ONGAuthenticator"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticator\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorRegistrationDelegate~1userClient(_:didRegister:forUser:info:)\/title","value":"userClient:didRegisterAuthenticator:forUser:info:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorRegistrationDelegate~1userClient(_:didRegister:forUser:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userClient:didRegisterAuthenticator:forUser:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorRegistrationDelegate\/title","value":"ONGAuthenticatorRegistrationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticatorRegistrationDelegate\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticatorRegistrationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/title","value":"ONGUserClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserClient\/fragments","value":[{"kind":"identifier","text":"ONGUserClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserProfile\/title","value":"ONGUserProfile"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGUserProfile\/fragments","value":[{"kind":"identifier","text":"ONGUserProfile"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}