{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotAuthenticated"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/devicenotauthenticated"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/devicenotauthenticated"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError\/deviceNotAuthenticated","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A device access token could not be retrieved. Check your Application configuration in the Token Server"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotAuthenticated"}],"title":"ONGFetchAnonymousResourceError.deviceNotAuthenticated","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchAnonymousResourceError@ONGFetchAnonymousResourceErrorDeviceNotAuthenticated","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchAnonymousResourceError/deviceNotAuthenticated":{"role":"symbol","title":"ONGFetchAnonymousResourceError.deviceNotAuthenticated","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceNotAuthenticated"}],"abstract":[{"type":"text","text":"A device access token could not be retrieved. Check your Application configuration in the Token Server"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError\/deviceNotAuthenticated","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"}],"url":"\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/devicenotauthenticated"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchAnonymousResourceError":{"role":"symbol","title":"ONGFetchAnonymousResourceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}],"abstract":[{"type":"text","text":"Error codes in ONGFetchAnonymousResourceErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}],"url":"\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError~1deviceNotAuthenticated\/title","value":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError~1deviceNotAuthenticated\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorDeviceNotAuthenticated"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError\/title","value":"ONGFetchAnonymousResourceError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}