{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMethod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/invalidmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/invalidmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError\/invalidMethod","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"provided request method is not valid, use one of @“GET”, @“POST”, @“DELETE”, @“PUT”"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMethod"}],"title":"ONGFetchAnonymousResourceError.invalidMethod","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGFetchAnonymousResourceError@ONGFetchAnonymousResourceErrorInvalidMethod","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorInvalidMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchAnonymousResourceError/invalidMethod":{"role":"symbol","title":"ONGFetchAnonymousResourceError.invalidMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMethod"}],"abstract":[{"type":"text","text":"provided request method is not valid, use one of @“GET”, @“POST”, @“DELETE”, @“PUT”"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError\/invalidMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorInvalidMethod"}],"url":"\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror\/invalidmethod"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGFetchAnonymousResourceError":{"role":"symbol","title":"ONGFetchAnonymousResourceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}],"abstract":[{"type":"text","text":"Error codes in ONGFetchAnonymousResourceErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGFetchAnonymousResourceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}],"url":"\/documentation\/oneginisdkios\/ongfetchanonymousresourceerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGFetchAnonymousResourceErrorInvalidMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorInvalidMethod"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorInvalidMethod"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError~1invalidMethod\/title","value":"ONGFetchAnonymousResourceErrorInvalidMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError~1invalidMethod\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceErrorInvalidMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError\/title","value":"ONGFetchAnonymousResourceError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGFetchAnonymousResourceError\/fragments","value":[{"kind":"identifier","text":"ONGFetchAnonymousResourceError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}