{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongnetworktaskstate\/cancelled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongnetworktaskstate\/cancelled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTaskState\/cancelled","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"title":"ONGNetworkTaskState.cancelled","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGNetworkTaskState@ONGNetworkTaskStateCancelled","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTaskStateCancelled"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTaskState"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTaskState":{"role":"symbol","title":"ONGNetworkTaskState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGNetworkTaskState"}],"abstract":[{"type":"text","text":"Possible values for ONGNetworkTask.state."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTaskState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTaskState"}],"url":"\/documentation\/oneginisdkios\/ongnetworktaskstate"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTaskState/cancelled":{"role":"symbol","title":"ONGNetworkTaskState.cancelled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTaskState\/cancelled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTaskStateCancelled"}],"url":"\/documentation\/oneginisdkios\/ongnetworktaskstate\/cancelled"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGNetworkTaskStateCancelled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTaskStateCancelled"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGNetworkTaskStateCancelled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTaskState\/title","value":"ONGNetworkTaskState"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTaskState\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTaskState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTaskState~1cancelled\/title","value":"ONGNetworkTaskStateCancelled"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTaskState~1cancelled\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTaskStateCancelled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}