{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUnauthenticatedResource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse","text":"ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask","text":"ONGNetworkTask"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned errors will be within the ONGGenericErrorDomain, ONGFetchUnauthenticatedResourceErrorDomain or NSURLErrorDomain."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongdeviceclient\/fetchunauthenticatedresource(_:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongdeviceclient\/fetchunauthenticatedresource(_:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchUnauthenticatedResource(_:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Perform an unauthenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediately (synchronously)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUnauthenticatedResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"title":"fetchUnauthenticatedResource(_:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGDeviceClient(im)fetchUnauthenticatedResource:completion:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient":{"role":"symbol","title":"ONGDeviceClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGDeviceClient"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGDeviceClient"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceRequest":{"role":"symbol","title":"ONGResourceRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceRequest"}],"abstract":[{"type":"text","text":"The object that encapsulates arguments required for performing a network request."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceRequest"}],"url":"\/documentation\/oneginisdkios\/ongresourcerequest"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGResourceResponse":{"role":"symbol","title":"ONGResourceResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGResourceResponse"}],"abstract":[{"type":"text","text":"The object that encapsulates response values."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGResourceResponse"}],"url":"\/documentation\/oneginisdkios\/ongresourceresponse"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGNetworkTask":{"role":"symbol","title":"ONGNetworkTask","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGNetworkTask"}],"abstract":[{"type":"codeVoice","code":"ONGNetworkTask"},{"type":"text","text":" is a cancelable object, representing the actual network request."},{"type":"text","text":" "},{"type":"text","text":"It offers cancelling, pausing and resuming requests."},{"type":"text","text":" "},{"type":"text","text":"Produced by "},{"type":"codeVoice","code":"-[ONGUserClient fetchResource:completion:]"},{"type":"text","text":", "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchResource:completion:]"},{"type":"text","text":" and "},{"type":"codeVoice","code":"-[ONGDeviceClient fetchUnauthenticatedResource:completion:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGNetworkTask"}],"url":"\/documentation\/oneginisdkios\/ongnetworktask"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGDeviceClient/fetchUnauthenticatedResource(_:completion:)":{"role":"symbol","title":"fetchUnauthenticatedResource(_:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchUnauthenticatedResource"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGResourceResponse","preciseIdentifier":"c:objc(cs)ONGResourceResponse"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Perform an unauthenticated network request. It requires passing an instance of the "},{"type":"codeVoice","code":"ONGResourceRequest"},{"type":"text","text":" as parameter."},{"type":"text","text":" "},{"type":"text","text":"In case of a malformed request no task will be returned and the completion block is called immediately (synchronously)."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGDeviceClient\/fetchUnauthenticatedResource(_:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}],"url":"\/documentation\/oneginisdkios\/ongdeviceclient\/fetchunauthenticatedresource(_:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fetchUnauthenticatedResource:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGNetworkTask","preciseIdentifier":"c:objc(cs)ONGNetworkTask","text":"ONGNetworkTask"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fetchUnauthenticatedResource:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGResourceRequest","preciseIdentifier":"c:objc(cs)ONGResourceRequest","text":"ONGResourceRequest"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"request"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ONGResourceResponse *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)ONGResourceResponse#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient\/title","value":"ONGDeviceClient"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient\/fragments","value":[{"kind":"identifier","text":"ONGDeviceClient"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/title","value":"ONGResourceRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceRequest\/fragments","value":[{"kind":"identifier","text":"ONGResourceRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceResponse\/title","value":"ONGResourceResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGResourceResponse\/fragments","value":[{"kind":"identifier","text":"ONGResourceResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/title","value":"ONGNetworkTask"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGNetworkTask\/fragments","value":[{"kind":"identifier","text":"ONGNetworkTask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchUnauthenticatedResource(_:completion:)\/title","value":"fetchUnauthenticatedResource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGDeviceClient~1fetchUnauthenticatedResource(_:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchUnauthenticatedResource:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}