{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestClientAccessToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withScopes"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scopes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens","text":"ONGSessionTokens"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/requesttokennetworkservice\/requestclientaccesstoken(withscopes:clientid:privatekey:uuid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/requesttokennetworkservice\/requestclientaccesstoken(withscopes:clientid:privatekey:uuid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RequestTokenNetworkService\/requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RequestTokenNetworkServiceProtocol.requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestClientAccessToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withScopes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"title":"requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)RequestTokenNetworkService(im)requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RequestTokenNetworkService"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RequestTokenNetworkService":{"role":"symbol","title":"RequestTokenNetworkService","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestTokenNetworkService"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RequestTokenNetworkService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RequestTokenNetworkService"}],"url":"\/documentation\/oneginisdkios\/requesttokennetworkservice"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGSessionTokens":{"role":"symbol","title":"ONGSessionTokens","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGSessionTokens"}],"abstract":[{"type":"text","text":"Access token data transfer object, part of the OAUTH data model"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongsessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/RequestTokenNetworkService/requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)":{"role":"symbol","title":"requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestClientAccessToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withScopes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"clientId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"privateKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SecKey","preciseIdentifier":"c:@T@SecKeyRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uuid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/RequestTokenNetworkService\/requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"}],"url":"\/documentation\/oneginisdkios\/requesttokennetworkservice\/requestclientaccesstoken(withscopes:clientid:privatekey:uuid:completion:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestClientAccessTokenWithScopes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scopes"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"clientId"},{"kind":"text","text":" "},{"kind":"identifier","text":"privateKey:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"__SecKey","preciseIdentifier":"c:@S@__SecKey"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"privateKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"uuid:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"uuid"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(ONGSessionTokens *, NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)ONGSessionTokens#*$objc(cs)NSError)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RequestTokenNetworkService\/title","value":"RequestTokenNetworkService"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RequestTokenNetworkService\/fragments","value":[{"kind":"identifier","text":"RequestTokenNetworkService"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/title","value":"ONGSessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RequestTokenNetworkService~1requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)\/title","value":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1RequestTokenNetworkService~1requestClientAccessToken(withScopes:clientId:privateKey:uuid:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestClientAccessTokenWithScopes:clientId:privateKey:uuid:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}