{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinBlackListed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinblacklisted"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinblacklisted"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/pinBlackListed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The provided PIN was marked as blacklisted on the Token Server."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinBlackListed"}],"title":"ONGPinValidationError.pinBlackListed","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGPinValidationError@ONGPinValidationErrorPinBlackListed","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorPinBlackListed"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError/pinBlackListed":{"role":"symbol","title":"ONGPinValidationError.pinBlackListed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinBlackListed"}],"abstract":[{"type":"text","text":"The provided PIN was marked as blacklisted on the Token Server."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/pinBlackListed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorPinBlackListed"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinblacklisted"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError":{"role":"symbol","title":"ONGPinValidationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationError"}],"abstract":[{"type":"text","text":"Error codes in ONGPinValidationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationError"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinValidationErrorPinBlackListed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorPinBlackListed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGPinValidationErrorPinBlackListed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1pinBlackListed\/title","value":"ONGPinValidationErrorPinBlackListed"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1pinBlackListed\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorPinBlackListed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/title","value":"ONGPinValidationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}