{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinShouldNotBeASequence"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinshouldnotbeasequence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinshouldnotbeasequence"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/pinShouldNotBeASequence","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The provided PIN contains a not allowed sequence"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinShouldNotBeASequence"}],"title":"ONGPinValidationError.pinShouldNotBeASequence","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGPinValidationError@ONGPinValidationErrorPinShouldNotBeASequence","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorPinShouldNotBeASequence"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError/pinShouldNotBeASequence":{"role":"symbol","title":"ONGPinValidationError.pinShouldNotBeASequence","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinShouldNotBeASequence"}],"abstract":[{"type":"text","text":"The provided PIN contains a not allowed sequence"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/pinShouldNotBeASequence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorPinShouldNotBeASequence"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror\/pinshouldnotbeasequence"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError":{"role":"symbol","title":"ONGPinValidationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationError"}],"abstract":[{"type":"text","text":"Error codes in ONGPinValidationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationError"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinValidationErrorPinShouldNotBeASequence"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorPinShouldNotBeASequence"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGPinValidationErrorPinShouldNotBeASequence"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1pinShouldNotBeASequence\/title","value":"ONGPinValidationErrorPinShouldNotBeASequence"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1pinShouldNotBeASequence\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorPinShouldNotBeASequence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/title","value":"ONGPinValidationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}