{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongPinLength"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/wrongpinlength"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongpinvalidationerror\/wrongpinlength"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/wrongPinLength","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The provided PIN length is wrong"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongPinLength"}],"title":"ONGPinValidationError.wrongPinLength","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGPinValidationError@ONGPinValidationErrorWrongPinLength","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorWrongPinLength"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError":{"role":"symbol","title":"ONGPinValidationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGPinValidationError"}],"abstract":[{"type":"text","text":"Error codes in ONGPinValidationErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationError"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGPinValidationError/wrongPinLength":{"role":"symbol","title":"ONGPinValidationError.wrongPinLength","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrongPinLength"}],"abstract":[{"type":"text","text":"The provided PIN length is wrong"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGPinValidationError\/wrongPinLength","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGPinValidationErrorWrongPinLength"}],"url":"\/documentation\/oneginisdkios\/ongpinvalidationerror\/wrongpinlength"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGPinValidationErrorWrongPinLength"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorWrongPinLength"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGPinValidationErrorWrongPinLength"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/title","value":"ONGPinValidationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1wrongPinLength\/title","value":"ONGPinValidationErrorWrongPinLength"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGPinValidationError~1wrongPinLength\/fragments","value":[{"kind":"identifier","text":"ONGPinValidationErrorWrongPinLength"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}