{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notHandleable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequesterror\/nothandleable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmobileauthrequesterror\/nothandleable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestError\/notHandleable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The mobile authentication request cannot be handled by the Onegini SDK. It might be due to the fact that the request was not meant for the Onegini SDK or that it is malformed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notHandleable"}],"title":"ONGMobileAuthRequestError.notHandleable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGMobileAuthRequestError@ONGMobileAuthRequestErrorNotHandleable","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequestErrorNotHandleable"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestError":{"role":"symbol","title":"ONGMobileAuthRequestError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGMobileAuthRequestError"}],"abstract":[{"type":"text","text":"Error codes in ONGMobileAuthRequestErrorDomain"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequestError"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequesterror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGMobileAuthRequestError/notHandleable":{"role":"symbol","title":"ONGMobileAuthRequestError.notHandleable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notHandleable"}],"abstract":[{"type":"text","text":"The mobile authentication request cannot be handled by the Onegini SDK. It might be due to the fact that the request was not meant for the Onegini SDK or that it is malformed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGMobileAuthRequestError\/notHandleable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGMobileAuthRequestErrorNotHandleable"}],"url":"\/documentation\/oneginisdkios\/ongmobileauthrequesterror\/nothandleable"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGMobileAuthRequestErrorNotHandleable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequestErrorNotHandleable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGMobileAuthRequestErrorNotHandleable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestError\/title","value":"ONGMobileAuthRequestError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestError\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequestError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestError~1notHandleable\/title","value":"ONGMobileAuthRequestErrorNotHandleable"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGMobileAuthRequestError~1notHandleable\/fragments","value":[{"kind":"identifier","text":"ONGMobileAuthRequestErrorNotHandleable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}