{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricAuthenticatorFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError","preciseIdentifier":"c:@E@ONGAuthenticationError","text":"ONGAuthenticationError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticationerror\/biometricauthenticatorfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticationerror\/biometricauthenticatorfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError\/biometricAuthenticatorFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Authentication with the biometric authenticator has failed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricAuthenticatorFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticationError","preciseIdentifier":"c:@E@ONGAuthenticationError"}],"title":"biometricAuthenticatorFailure","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@ONGAuthenticationError@ONGAuthenticationErrorBiometricAuthenticatorFailure","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationErrorBiometricAuthenticatorFailure"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationError/biometricAuthenticatorFailure":{"role":"symbol","title":"biometricAuthenticatorFailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"biometricAuthenticatorFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ONGAuthenticationError","preciseIdentifier":"c:@E@ONGAuthenticationError"}],"abstract":[{"type":"text","text":"Authentication with the biometric authenticator has failed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError\/biometricAuthenticatorFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationErrorBiometricAuthenticatorFailure"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationerror\/biometricauthenticatorfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationError":{"role":"symbol","title":"ONGAuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationError"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticationErrorBiometricAuthenticatorFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationErrorBiometricAuthenticatorFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAuthenticationErrorBiometricAuthenticatorFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError~1biometricAuthenticatorFailure\/title","value":"ONGAuthenticationErrorBiometricAuthenticatorFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError~1biometricAuthenticatorFailure\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationErrorBiometricAuthenticatorFailure"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError\/title","value":"ONGAuthenticationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}