{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchIDAuthenticatorFailure"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongauthenticationerror\/touchidauthenticatorfailure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongauthenticationerror\/touchidauthenticatorfailure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError\/touchIDAuthenticatorFailure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deprecated Error. Authentication with the touchID has failed."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchIDAuthenticatorFailure"}],"title":"ONGAuthenticationError.touchIDAuthenticatorFailure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@ONGAuthenticationError@ONGAuthenticationErrorTouchIDAuthenticatorFailure","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationError":{"role":"symbol","title":"ONGAuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGAuthenticationError"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationError"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationerror"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGAuthenticationError/touchIDAuthenticatorFailure":{"role":"symbol","title":"ONGAuthenticationError.touchIDAuthenticatorFailure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchIDAuthenticatorFailure"}],"abstract":[{"type":"text","text":"Deprecated Error. Authentication with the touchID has failed."}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGAuthenticationError\/touchIDAuthenticatorFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"}],"url":"\/documentation\/oneginisdkios\/ongauthenticationerror\/touchidauthenticatorfailure"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError\/title","value":"ONGAuthenticationError"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError~1touchIDAuthenticatorFailure\/title","value":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGAuthenticationError~1touchIDAuthenticatorFailure\/fragments","value":[{"kind":"identifier","text":"ONGAuthenticationErrorTouchIDAuthenticatorFailure"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}