{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactory\/authorizationcontroller(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactory\/authorizationcontroller(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory\/authorizationController(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AppleIdAuthorizationControllerFactoryProtocol.authorizationController(with:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"authorizationControllerWithDelegate:"}],"role":"symbol","title":"authorizationController(with:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"symbolKind":"method","externalID":"c:@M@OneginiSDKiOS@objc(cs)AppleIdAuthorizationControllerFactory(im)authorizationControllerWithDelegate:","modules":[{"name":"OneginiSDKiOS"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactory/authorizationController(with:)":{"role":"symbol","title":"authorizationController(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizationController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ASAuthorizationControllerDelegate","preciseIdentifier":"c:objc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory\/authorizationController(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authorizationControllerWithDelegate:"}],"url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactory\/authorizationcontroller(with:)"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/AppleIdAuthorizationControllerFactory":{"role":"symbol","title":"AppleIdAuthorizationControllerFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/AppleIdAuthorizationControllerFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}],"url":"\/documentation\/oneginisdkios\/appleidauthorizationcontrollerfactory"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authorizationControllerWithDelegate:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"ASAuthorizationController","preciseIdentifier":"c:objc(cs)ASAuthorizationController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ASAuthorizationControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)ASAuthorizationControllerDelegate"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory~1authorizationController(with:)\/title","value":"authorizationControllerWithDelegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory~1authorizationController(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authorizationControllerWithDelegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory\/title","value":"AppleIdAuthorizationControllerFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1AppleIdAuthorizationControllerFactory\/fragments","value":[{"kind":"identifier","text":"AppleIdAuthorizationControllerFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}