{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel","text":"ONGClientIdModel"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly\/clientidmodel()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly\/clientidmodel()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientIdModel()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"!"}],"title":"clientIdModel()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGModelAssembly(im)clientIdModel","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGClientIdModel":{"role":"symbol","title":"ONGClientIdModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGClientIdModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGClientIdModel"}],"url":"\/documentation\/oneginisdkios\/ongclientidmodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/clientIdModel()":{"role":"symbol","title":"clientIdModel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/clientIdModel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientIdModel"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/clientidmodel()"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly":{"role":"symbol","title":"ONGModelAssembly","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGModelAssembly"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clientIdModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientIdModel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGClientIdModel","preciseIdentifier":"c:objc(cs)ONGClientIdModel","text":"ONGClientIdModel"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"clientIdModel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientIdModel\/title","value":"ONGClientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGClientIdModel\/fragments","value":[{"kind":"identifier","text":"ONGClientIdModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1clientIdModel()\/title","value":"clientIdModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1clientIdModel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clientIdModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/title","value":"ONGModelAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/fragments","value":[{"kind":"identifier","text":"ONGModelAssembly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}