{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens","text":"ONGSessionTokens"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly\/sessiontokens()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongmodelassembly\/sessiontokens()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/sessionTokens()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"title":"sessionTokens()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)ONGModelAssembly(im)sessionTokens","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly":{"role":"symbol","title":"ONGModelAssembly","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGModelAssembly"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGModelAssembly"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGSessionTokens":{"role":"symbol","title":"ONGSessionTokens","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGSessionTokens"}],"abstract":[{"type":"text","text":"Access token data transfer object, part of the OAUTH data model"}],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGSessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongsessiontokens"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGModelAssembly/sessionTokens()":{"role":"symbol","title":"sessionTokens()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGModelAssembly\/sessionTokens()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionTokens"}],"url":"\/documentation\/oneginisdkios\/ongmodelassembly\/sessiontokens()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sessionTokens"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokens"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGSessionTokens","preciseIdentifier":"c:objc(cs)ONGSessionTokens","text":"ONGSessionTokens"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sessionTokens"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/title","value":"ONGModelAssembly"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly\/fragments","value":[{"kind":"identifier","text":"ONGModelAssembly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/title","value":"ONGSessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGSessionTokens\/fragments","value":[{"kind":"identifier","text":"ONGSessionTokens"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1sessionTokens()\/title","value":"sessionTokens"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGModelAssembly~1sessionTokens()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sessionTokens"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}