{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonRequestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFJSONRequestSerializer","preciseIdentifier":"c:objc(cs)AFJSONRequestSerializer"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestserializermodel\/jsonrequestserializer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestserializermodel\/jsonrequestserializer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel\/jsonRequestSerializer","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonRequestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFJSONRequestSerializer","preciseIdentifier":"c:objc(cs)AFJSONRequestSerializer"},{"kind":"text","text":"!"}],"title":"jsonRequestSerializer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGRequestSerializerModel(py)JSONRequestSerializer","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"JSONRequestSerializer"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestSerializerModel":{"role":"symbol","title":"ONGRequestSerializerModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestSerializerModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/ongrequestserializermodel"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestSerializerModel/jsonRequestSerializer":{"role":"symbol","title":"jsonRequestSerializer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonRequestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFJSONRequestSerializer","preciseIdentifier":"c:objc(cs)AFJSONRequestSerializer"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel\/jsonRequestSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONRequestSerializer"}],"url":"\/documentation\/oneginisdkios\/ongrequestserializermodel\/jsonrequestserializer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"JSONRequestSerializer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JSONRequestSerializer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AFJSONRequestSerializer","preciseIdentifier":"c:objc(cs)AFJSONRequestSerializer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"JSONRequestSerializer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/title","value":"ONGRequestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/fragments","value":[{"kind":"identifier","text":"ONGRequestSerializerModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel~1jsonRequestSerializer\/title","value":"JSONRequestSerializer"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel~1jsonRequestSerializer\/fragments","value":[{"kind":"identifier","text":"JSONRequestSerializer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}