{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFHTTPRequestSerializer","preciseIdentifier":"c:objc(cs)AFHTTPRequestSerializer"},{"kind":"text","text":"! { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/oneginisdkios\/ongrequestserializermodel\/requestserializer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/oneginisdkios\/ongrequestserializermodel\/requestserializer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel\/requestSerializer","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFHTTPRequestSerializer","preciseIdentifier":"c:objc(cs)AFHTTPRequestSerializer"},{"kind":"text","text":"!"}],"title":"requestSerializer","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)ONGRequestSerializerModel(py)requestSerializer","modules":[{"name":"OneginiSDKiOS"}],"navigatorTitle":[{"kind":"identifier","text":"requestSerializer"}]},"hierarchy":{"paths":[["doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel"]]},"references":{"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS":{"role":"collection","title":"OneginiSDKiOS","abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS","kind":"symbol","type":"topic","url":"\/documentation\/oneginisdkios"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestSerializerModel/requestSerializer":{"role":"symbol","title":"requestSerializer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AFHTTPRequestSerializer","preciseIdentifier":"c:objc(cs)AFHTTPRequestSerializer"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel\/requestSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestSerializer"}],"url":"\/documentation\/oneginisdkios\/ongrequestserializermodel\/requestserializer"},"doc://com.onegini.OneginiSDKiOS/documentation/OneginiSDKiOS/ONGRequestSerializerModel":{"role":"symbol","title":"ONGRequestSerializerModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ONGRequestSerializerModel"}],"abstract":[],"identifier":"doc:\/\/com.onegini.OneginiSDKiOS\/documentation\/OneginiSDKiOS\/ONGRequestSerializerModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ONGRequestSerializerModel"}],"url":"\/documentation\/oneginisdkios\/ongrequestserializermodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"requestSerializer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requestSerializer"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"AFHTTPRequestSerializer","preciseIdentifier":"c:objc(cs)AFHTTPRequestSerializer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requestSerializer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel~1requestSerializer\/title","value":"requestSerializer"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel~1requestSerializer\/fragments","value":[{"kind":"identifier","text":"requestSerializer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/title","value":"ONGRequestSerializerModel"},{"op":"replace","path":"\/references\/doc:~1~1com.onegini.OneginiSDKiOS~1documentation~1OneginiSDKiOS~1ONGRequestSerializerModel\/fragments","value":[{"kind":"identifier","text":"ONGRequestSerializerModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}